### ISSUE TITLE
Allowing HolB on header compression and DoS

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1011]
There's a memory exhaustion exposure that is generated by header compression if we allow head of line blocking.  Head of line blocking means buffering, which is currently not accounted for in the protocol.

We could decide that head of line blocking is not worth the effort, in which this becomes a non-event.  We could decide that this is not interesting.  Or we could decide to build a mechanism for accounting for the memory cost.

**Comment by ianswett** [comment]
I would think the memory issue would be dealt with by flow control.  I believe that does allow the remote possibility of a connection ending up flow control blocked on HolB data.  Is there any other issue?

**Comment by martinthomson** [comment]
Flow control can't help here.  You don't learn about the head of line blocking until the application consumes data and then it's out of the receive buffers.  You could imagine using peek-style APIs, but I don't think that it's reasonable to essentially force that on everyone.

**Comment by krasic** [comment]
Am I correct that this can be further simplified:  gigantic headers not finished, followed by a gap in the stream.   If processing of headers isn't done in streaming fashion, the attacker can force the server into holding partial requests not tracked by flow control.  

Even if one does process headers in streaming fashion, it's arguable that higher level state will likely consume a proportionate amount memory while the stream/transaction remains alive.   

At the end of the day, a server might have to make it's own judgement that memory is too tight, and take action, e.g. refuse new streams.

There was some discussion way back about stream refusals and the mechanics of stream limits.  If I recall correctly, we dropped the capability of servers to refuse streams when the stream limits were not exceeded.    I think/thought it was a mistake, exactly because it's an important line of defense to control memory usage.   When I asked our server folks if dropping the right to refuse was reasonable,  their answer was a definite no.

**Comment by dtikhonov** [comment]
> Even if one does process headers in streaming fashion, it's arguable that higher level state will likely consume a proportionate amount memory while the stream/transaction remains alive.

I think this is correct.

> At the end of the day, a server might have to make it's own judgement that memory is too tight, and take action, e.g. refuse new streams.

The problem is that the unfinished header exists somewhere between the transport and the application layers.  It is difficult to make judgment there.

**Comment by martinthomson** [comment]
The idea that was discussed was - in combination with the checkpointing scheme @dtikhonov proposes - is to advertise the checkpoint that a block depends on.  The decoder would advertise how many streams it would allow to be blocked on an unfulfilled dependency.

**Comment by MikeBishop** [comment]
The first piece of this means that a decoder could read only up to that point (the first few bytes of a HEADERS frame), then decide whether to proceed.  If it chooses not to proceed yet, then the data sits at the QUIC layer and flow control provides the back-pressure to manage memory consumption.

**Comment by ianswett** [comment]
The Editors believe the QPACK design addresses this by preceding the header frame by a QPACK varint, which allows QUIC to use flow control to provide back pressure.
