### ISSUE TITLE
Timestamp Block - Zero indexing?

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#102]
NumTimestamps is supposed to specify the "total number of pairs following, including the First Timestamp."  If this is zero, presumably the Delta Largest Acked and First Timestamp fields are absent.  If this is one, presumably these fields are present, but no others are.

The *subsequent* fields then say they are repeated "Num Timestamps" times, which contradicts my logic above.  I'm guessing this should actually be "Num Timestamps - 1" times?

**Comment by swarmer** [comment]
The "including the First Timestamp" text seems to be gone and now I have no idea how to determine if this first optional timestamp is actually there. Can someone who understands how this is supposed to work please clarify?

**Comment by ianswett** [comment]
If the num_timestamps byte is 0, the timestamp section is not present..  

The currentt text also says "Delta Largest Acked 1..N(opt, repeated)" and Time Since Previous Timestamp 1..N(opt, repeated)" but I believe these should be 0..N.

I'm going to update the timestamp section in the near future, so I'll ensure that's fixed and clarify that if the num timestamps is 0, the timestamp section is absent.

**Comment by swarmer** [comment]
So if num_timestamps is 1, then one delta and the first timestamp must be present for a total of 40 bytes in this section?

If so, I don't see how 0..N makes sense for the additional timestamps. Maybe there should be text saying that N = num_timestamps - 1.

**Comment by martinthomson** [comment]
@ianswett fixed this in #360.  Reopen if you think that this is wrong.
