### ISSUE TITLE
Invariant: the first packet on a connection uses the long header

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1040]
We need this for version negotiation to work.

**Comment by MikeBishop** [comment]
Agreed -- this is generally assumed, but not actually written down.

**Comment by ianswett** [comment]
In order for this not to be true, that implies you have done out of band version negotiation and key negotiation?  At that point, I would call it migration rather than a new connection.

One use case is to migrate a connection from a TLS 1.3 TCP connection to a QUIC connection.  A similar use might be WebRTC using QUIC?

It seems like we could do these no matter what we decide here.

**Comment by martinthomson** [comment]
Yes.  There's always this little annoying insect that reminds me that people start QUIC from not-QUIC with keys and context already established.  Those people are welcome to do so, but they aren't really using the same protocol and so wouldn't be bound by the same constraints.  In this case, they would have to understand that they don't get to use version negotiation.

**Comment by martinthomson** [comment]
Closed in e6ac5c1.

**Comment by MikeBishop** [comment]
And if they need it, all they have to do is define a version that has the long-header 1-RTT packet types put back.
