### ISSUE TITLE
"CanSendPacket" function or equivalent function

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1056]
The congestion control section doesn't provide a function that describes how a sender might decide whether to send a packet (or, similarly, but more complicated, a function that describes what can be sent in a packet at the current moment).

Ideally this would include pacing and congestion limits.  And it would include the exclusion for ACK-only packets (#1055).  

Anyone addressing this might consider #837 at the same time.

**Comment by ianswett** [comment]
Getting into the mechanics of pacing is potentially complex and implementation dependent, so currently the editor's draft just recommends using pacing.

#837 is not editorial, whereas I am fairly sure this suggestion is, so I don't see a need to resolve them at once.

**Comment by martinthomson** [comment]
It's only really an editorial issue if you consider an omission like this to be editorial.  That is, you consider the design to be implied.  I don't think that it's that trivial.

Pacing inclusion might only be exemplary in the sense that choosing the value might still be left to implementations, but it seems feasible to describe one potential integration into the algorithm.

**Comment by janaiyengar** [comment]
Without pacing, the design is implied IMO -- the congestion controller allows a packet to be sent if inflight is below the congestion window.

I don't think we should specify pacing here, since there's no current equivalent spec for TCP that we can simply "re-map". There are multiple implementations of pacers for TCP out there (for different OSes), and we'd either end up describing one of them, or litigate the right way to pace. I'm not convinced either of these options is useful.

**Comment by janaiyengar** [comment]
From editors meeting: Add text to say something about how a sender should compose congestion control and pacer, comparable to FQ, for example.
