### ISSUE TITLE
Greasing version negotiation

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#112]
Shout out to @davidben and the recently adopted draft-davidben-tls-grease.

**Comment by janaiyengar** [comment]
Yes!

**Comment by ianswett** [comment]
We should grease all the public flag bits to ensure they're all usable in the future.

**Comment by MikeBishop** [comment]
So the text would be something like "In version N, the following bits are unused and MAY be set randomly by clients and servers."  In version N+1, where a bit acquires a meaning, we can stop using it for GREASE?  Scoping it to versions seems to neatly sidestep the problem of making things unusable in the future *because* they've been used as grease.

**Comment by mnot** [comment]
Discussed in Tokyo: consensus in the room.

**Comment by martinthomson** [comment]
Caveat: we need to ensure that there is a way to grease consistently between the stateless version negotiation packet AND the copy of that in the ServerHello.

**Comment by janaiyengar** [comment]
I thought martinthomson said to leave this open -- if I misheard, feel free to close.

**Comment by mnot** [comment]
That was a different one.

**Comment by mnot** [comment]
Oh, no - that was this.
