### ISSUE TITLE
QPACK encoding requires two passes

### ISSUE THREAD

**Issue by afrind** [quicwg/base-drafts#1138]
According to the spec "Base index is the cumulative number of entries added to the dynamic table prior to encoding the current block, including any entries already evicted."

However if you try to make a single pass encoder, you may end up with references to headers inserted while encoding the current block, which will be larger than the encoded base.  The hybrid representation would be negative, and HPACK cannot encode negative numbers.

```
encodedBase = baseIndex
writeBaseIndex(encodedBase, requestStream)
# save space for Depends
for h in headers:
  absIndex = getAbsoluteIndex(h)
  if absIndex == 0:
    if shouldIndex(h):
      absIndex = writeTableUpdate(h, controlStream)
    else:
      writeLiteral(h, requestStream)
      continue
  hybridIndex = encodedBase - absIndex
  # oops, absIndex may be larger than encodedBase
  writeIndexRef(hybridIndex, requestStream)
 ```

The only solution to implement the draft as specific is to make two passes, one that performs all necessary table inserts to get the right value of Base Index, and another to encode all the references relative to Base Index.

My QCRAM prototype did something bizarre to make this work in a single pass (https://goo.gl/nghK89) - using the maximum length of the dynamic table (MAX_HEADER_TABLE_SIZE / 32) to normalize negative numbers.  With the default maximum of 4KB, the first hybrid index after encodedBase is 128, then 127 and so on.

**Comment by MikeBishop** [comment]
While I agree it's a desirable property to add if we can, I also don't think this is debilitating.  In the worst case, an encoder which must stream could opt to double-encode -- a literal now, and an insert at its leisure if it thinks it will use the entry again.  There's a size penalty, but it's still compliant.

**Comment by afrind** [comment]
Are folks ok with using literals if headers must be streamed?  Another approach is to extend the wire-format to efficiently encode negative Hybrid indexes (Depends would need this also).  

Single pass encoding that references newly indexed headers may also be challenging for implementations that don't use scatter-gather, since going back to write a variable length int at the beginning of a buffer is tricky.

The number of headers in a pass is likely small in a lot of common cases, and with some intermediate memory you can capture the required absolute indexes in the first pass.

**Comment by dtikhonov** [comment]
> My QCRAM prototype did something bizarre to make this work in a single pass

I say if it works, it's not bizarre.

**Comment by dtikhonov** [comment]
Upon reflection, I believe that the two-pass approach is untenable:
- Extra copy;
- Buffering;
- Delayed write.  (Imagine converting HTTP to QUIC and having to delay sending while all HTTP headers are read).

Using literals is a solution, but I don't like it, since compression suffers.

Note that it is not relevant which API is used -- streaming or scatter/gather.  A proxy may not have all HTTP headers. It wants to be able to send out what it has read ASAP, without having to wait to read all headers.

**Comment by afrind** [comment]
If you want the proxy case to work without literals, then we would need to change the rules around BLOCKING and Depends, since the proxy cannot compute Depends correctly on the first header if it is allowed to insert and make references.  So far the only thing I can come up with is a flag/format which allows Depends to appear at the end of the block, and missing references are not treated as errors unless they turn out to be greater than Depends.  But this is ugly and has all sorts of problems.  At least some proxies will need the entire header block to make routing decisions, so I'm not sure how often the compression degradation will be a problem.

**Comment by dtikhonov** [comment]
> If you want the proxy case to work without literals, then we would need to change the rules around BLOCKING and Depends, since the proxy cannot compute Depends correctly on the first header if it is allowed to insert and make references.

I don't understand this; but this may be because I need to re-read the draft.

As for the proxy -- I meant anything that translates HTTP to QUIC.  For example, imagine a QUIC frontend in front of an application server, for example.  What's the correct term -- gateway?  Why couldn't it write headers as soon as it received them?

Are you arguing that this scenario is something that is unlikely to be encountered and can therefore be ignored?

**Comment by martinthomson** [comment]
Right now, there is either no blocking references, or two passes.  That is, concurrent table updates and inserts.   Well, references can still block - you don't have to wait for a full round trip - they just can't block based on the current set of header fields.

I think that this is fundamentally hard if you want blocking references to things that might be inserted as a result of the current set of header fields AND a single pass over the table.  If concurrent table inserts are being made, you have to rewrite any references that were made before the insert.  You also want a signal at the start of the header block about the expected table state so that you can use flow control for back pressure, which means that you have to hold the header block until you decide to stop making table updates.  Putting Depends at the end regresses functionality already agreed.

A gateway (yes that was correct) can write as it receives header fields, but it can't rely on any inserts that it makes concurrent with those writes.  That's all.  And I'm OK with that.

@dtikhonov, you were previously a champion of non-blocking.  Maybe you are OK with this too.

**Comment by dtikhonov** [comment]
I agree that the case of concurrent table inserts is hard -- header blocks that are being encoded concurrently cannot reference _each other's_ entries. I am, indeed, OK with _that._

On the other hand, a header block should be able to (at least it seems that way to me!) reference entries that it itself adds.

I think it was mentioned before -- could we use a relative indexing scheme inside the header block? As in "reference 3rd entry added by this header block."

**Comment by afrind** [comment]
Header blocks on request streams do not contain any table modifications.  We're talking about inserts on the control stream generated while encoding a block on a request stream. 
 There's no guarantee in what order the inserts and references will arrive, hence Depends would need to be updated to reflect the highest entry referenced in the block.  

Older QCRAM drafts allowed the block itself to do the inserts, but we've stripped that complexity (resend on reset, out of order inserts, etc) out for now.

**Comment by MikeBishop** [comment]
Actually, we have this problem regardless of Depends.  The HEADERS frame is length-prefixed, so you have to have fully generated the output before you can send any of it.  We broke streaming compression when we removed CONTINUATION frames, except that I haven't heard of anyone actually using CONTINUATION that way.

**Comment by dtikhonov** [comment]
> Header blocks on request streams do not contain any table modifications [...] referenced in the block.

Oh yes, how silly of me -- I forgot about that.

**Comment by krasic** [comment]
I will poke around here too see if there are strong feelings about loosing the option for streaming mode.   My fuzzy recollection is that it was valued for hardening against memory spikes associated with clusters of pathologically large headers.

FWIW, when I extended my QCRAM protype in the proxygen simulator to split updates from the request-response steram,  it became effectively double encode:  

https://github.com/facebook/proxygen/blob/master/proxygen/lib/http/codec/compress/experimental/qcram/QCRAMEncoder.cpp#L45

**Comment by MikeBishop** [comment]
The responses, both on-list and from folks I've asked, suggest that streaming decode is much higher priority than streaming encode.

**Comment by dtikhonov** [comment]
> The responses, both on-list and from folks I've asked, suggest that streaming decode is much higher priority than streaming encode.

If you are referring to the recent httpbis thread: varnish, haproxy, and squid is a single use case.

**Comment by MikeBishop** [comment]
Speaking as former owner of a client and server implementation:

- our client API permitted the caller to supply headers onto the request one at a time
- our server API required all response headers be delivered at once (but could stream body)
- our header compression library processed all headers as a single input

Remember, the headers cannot be streamed onto the wire in HTTP/2, nor can you compress headers on any other streams in parallel.  QCRAM is already better than that because, if desired, multiple streams can be actively compressing at once.  (Either queuing their additions into a single table update frame, or compressing against a table state without modifications.)

**Comment by afrind** [comment]
Here's my proposal for single pass encoding.  

In addition to Base and Depends, encode Length, the number of valid dynamic table entries prior to encoding the block.  Dynamic indexes 1..Length are older than Base Index.  Dynamic indexes larger than Length count up from Base Index.  Since Depends can be larger than Base Index, rename Depends to Base Index (the largest entry referenced in the block) and encode the Delta between Base Index and the value of Base Index used for encoding.

Remove the BLOCKING flag, which is now implicit upon receiving a request stream with Base Index higher than the decoder's Base Index.  Instead, add a flag 'EXTENDED_BASE', which is present if the encoder's Base Index changed during an encode.

The wire format for frames with EXTENDED_BASE flag is:

```
    0 1 2 3 4 5 6 7
   +-+-+-+-+-+-+-+-+
   | Base Index(8+)|
   +---------------+
   | Base Delta(8+)|
   +---------------+
   | Length    (8+)|
   +---------------+
```

Here's an example where the encoder began encoding with four entries in the table, and added two during an encode.  Let's assume Base Index prior to encoding was 18.  Here's how entries would be referenced:

```
              E       B
+---+---+---+---+---+---+
+ 4 + 3 + 2 + 1 + 5 + 6 +
+---+---+---+---+---+---+
 15  16  17  18  19  20

E = Encoding Base
B = Base Index
```

The encoder would produce a block that begin with `0x14 0x02 0x04`

Encode algorithm:
```
baseIndex = dynamicTable.baseIndex
length = dynamicTable.numEntries
numInserts = 0
largestReference = 0
for header in headers:
  i = staticTable.getIndex(header)
  if i > 0:
    encodeIndexReference(streamBuffer, i)
    continue
  i = dynamicTable.getAbsoluteIndex(header)
  if i == 0:
    largestReference = max(largestReference, i)
  else if dynamicTable.canIndex(header):
    encodeInsert(controlBuffer, header)
    dynamicTable.add(header)
    numInserts += 1
    i = baseIndex + numInserts  # absolute index of new entry
    largestReference = max(largestReference, i)
  else:
    encodeLiteral(header)
    continue

  if i <= baseIndex:
    i = baseIndex - i + 1
    assert(i <= length)
  else:
    i = i - baseIndex + length

  encodeIndexReference(streamBuffer, i + staticTable.size())

# Write the prefix
encodeInteger(prefixBuffer, largestReference, 8)
if largestReference > baseIndex:
  extendedBase = True
  encodeInteger(prefixBuffer, largestReference - baseIndex, 8)
  encodeInteger(prefixBuffer, length, 8)
else 
  extendedBase = False

return (controlBuffer, prefixBuffer + streamBuffer, extendedBase)
```

Decode Algorithm:

Header:
```
if extendedBase:
  largestReference = decodeInteger(buf, 8)
  encodingBaseIndex = largestReference - decodeInteger(buf, 8)
  length = decodeInteger(buf, 8)
else:
  largestReference = encodingBaseIndex = decodeInteger(buf, 8)
  length = 0
```

Index Processing:
```
index = decodeIndex(buf, N)
if index <= staticTable.size():
  header = staticTable[index]
else:
  index -= staticTable.size()
  if length == 0 or index <= length:
    absoluteIndex = encodingBaseIndex - index + 1
  else
    absoluteIndex = index + encodingBaseIndex - length
  index = dynamicTable.baseIndex - index + 1
  header = dynamicTable[index]
}
```

**Comment by afrind** [comment]
@martinthomson mentioned that he didn't like this approach.  Specifically:

1) He disliked the out-of-band flag

I got rid of the flag and encoded 2 varints (the largest reference and the encoding base) in all stream blocks.  In one-pass encoding, largest reference may be smaller than the encoding base (eg: the block didn't reference the most recent table entry) or larger (the block triggered an insert/duplication).  Just eyeballing it, both are required about half the time, and the delta was always small enough to fit in a single byte.  Note the delta needs to be encoded with a sign bit.

```
[   Depends Index(8+) ]
[ S | Base Delta (7+) ]
```

Where Depends Index is the largest reference in the block, and 
`baseIndex = (S) ? dependsIndex - delta : dependsIndex + delta`

If someone really wanted to save the byte when they are the same, we could encode a flag in the MSB of Depends Index and give it a 7 bit prefix.

2) He thought including length was messy/large and could maybe do it with different instructions, possibly reusing some unused HPACK ones.

Fortunately, there are two unused HPACK instructions on QPACK request streams that can be repurposed.  I changed 'Literal with incremental indexing' to 'Literal with name index higher than base', and 'Table size update' to 'Indexed with index higher than base'.   Indexes in these instructions are found at absolute index = baseIndex + index (- 61 optional, I did it for consistency).  This also leaves only a single HPACK instruction invalid in QPACK (literal on control stream).  I like this approach better than using length.

**Comment by MikeBishop** [comment]
Fixed by #1320.

**Comment by hvenev** [comment]
Does it make sense for the base index to be greater than the largest reference? Won't then all post-base references be illegal?

**Comment by MikeBishop** [comment]
Yes, they would be illegal because they would by definition be referring to values greater than the Largest Reference.  That doesn't mean it's nonsensical -- a single-pass encoder will pick a Base Index before it knows what references it will make; if it doesn't insert any entries, then it won't need to make post-base references.

A two-pass encoder will probably make them always equal and never make post-base references.
