### ISSUE TITLE
0-based indexing

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1145]
QPACK (?) uses the same 1-based indexing that HPACK does.  But if we contemplate #1144, then all that 1-based indexing does is create an unused value.  That's annoying.  0-based indexes are more common and are natural.  We tolerated 1-based indexing in HPACK because it make name indexes somewhat easier to manage.

**Comment by MikeBishop** [comment]
We tolerated it because losing one value to a sentinel was deemed better than losing an entire bit.  However, with the reworked instruction space, we wouldn't be able to reclaim a bit by using a sentinel, so I'd be fine with reclaiming the value.  (Of course, as with each step in this direction, that means we're departing further and further from HPACK equivalence.)
