### ISSUE TITLE
ICMP and ICMPv6 PMTUD with asymmetric connection-ids

### ISSUE THREAD

**Issue by enygren** [quicwg/base-drafts#1243]
Asymmetric connection-ids introduce problems for handling ICMP and ICMPv6 PMTUD messages (such as ICMPv6 packet-too-big) in conjunction with stateless load balancers.  For example, if a server sends out a packet containing a client connection-id that is too big, a router or tunnel end-point may send back an ICMPv6 PTB message containing the packet header.  Because the PTB message with the packet header only contains the client connecton-id, it isn't possible to route to the proper server.

While ICMP/ICMPv6 PTB messages are best treated as optimizations, being able to get them can be very useful for identifying the source off loss quickly as being a too-large packet.

Note that other ICMP(v6) messages such as destination-unreachable also have a similar problem with asymmetric connection-ids.

Note that related topics are under active discussion in other working groups, such as:
* draft-bonica-intarea-frag fragile-01
* draft-ietf-tsvwg-datagram-plpmtud

**Comment by enygren** [comment]
One proposal based on discussions would be to allow Long headers (with both client and server connection-ids) in certain situations following the handshake.  In particular, when performing a PMTUD probe (or otherwise sending a packet with a larger size than the current PMTU), using a Long form header would mean that a stateless load balancer would still be able to route it based on the payload of the ICMP(v6) message, plus it might make it safer and easier for the server to validate that the packet was send by a device on-path.  Both endpoints would still of course need to have reasonable lower bounds on PMTU as well.

Similarly, such a scheme could also make it more reasonable to support ICMP(v6) destination-unreachable messages in a way that wasn't vulnerable to parallel-to-path resets but could allow devices such as NATs to eventually squelch connections where state is no longer present.  For example, if the Nth and subsequent (3rd?) retransmits of the same data was sent with a full Long header (with both connection-ids) and an ICMP(v6) response is returned that contains both connection-ids (plus enough data from what was sent for validation) then this is a good sign that the node sending is both on-path and that this is a degenerate situation that should only have been reached after multiple losses and thus likely from a legitimate active middle-box.

(Note that client/server above are symmetric as both end-points have the same challenge with roles reversed.)

**Comment by igorlord** [comment]
We used to allow long-header packets after handshake, but got rid of them for the lack of a use case.  This is a valid use case, so it would be good to bring back these long-header packets.

**Comment by martinthomson** [comment]
@enygren, @igorlord, the solutions that you are contemplating here are fairly disruptive to the design.  If you feel strongly about this, you should take it to the list and get the attention of the working group.

**Comment by kazuho** [comment]
FWIW, let me point out that under the current draft it is possible for an endpoint to send a long header packet at any time it wants to observe the MTU, even after the handshake is complete. It's just that the long header packet will be ignored by the client in case it reaches the client.

And with the introduction of coalesced packets, the cost of doing this type of PMTUD has become small.

Whenever an endpoint wants to do PMTUD and it has some outstanding data, is creates a datagram that consists of the following two QUIC packets:
* a long header packet with zero-length payload that contains the server CID (or some other payload that is sufficient to route the ICMP response back to the origin server)
* a short header packet carrying outstanding data

This type of datagram never harms the conncection, because the draft requires the receiver to process each QUIC packet as if it was received as a separate datagram.

Assuming that the server will be performing PMTUD and assuming that the client's CID is zero-sized, the overhead of the long header packet is: 1 (type) + 4 (version) + 1 (cidl) + len(server_CID) + 1 (payload-length).

Actually, this approach (i.e. sending a compound datagram to contain arbitrary information) is flexible enough to carry any data that needs to be exposed to an on-path device. We could use it to expose packet drop rate for example.

I'm not saying we should support these kinds of exposures, but we cannot prohibit such thing to happen, because the receiver cannot determine if an incoming packet was sent from the peer (to expose signal to on-path devices) or from an attacker (to disrupt connection).

**Comment by mikkelfj** [comment]
> This type of datagram never harms the conncection, because the draft requires the receiver to process each QUIC packet as if it was received as a separate datagram.

That is not necessarily true because that is under a cooperative assumption. Any party that keeps dumping invalid packets might be flagged, also otherwise competent QUIC peers. Seeing something suspect in a packet is reasonable cause for rejecting the entire transmission.

Hence, if this is considered a good idea, both endpoints should understand  and agree  on this and avoid confusing each other.

**Comment by kazuho** [comment]
> Any party that keeps dumping invalid packets might be flagged, also otherwise competent QUIC peers. Seeing something suspect in a packet is reasonable cause for rejecting the entire transmission.

I disagree. As stated in my comment above, terminating the connection due to seeing suspicious QUIC packets is equal to allowing attackers reset the connection. That goes against our principal of having "authenticated reset."

I believe that the same holds for coalesced packets. An attacker can break the packet by modifying it. But that should not lead to the connection being terminated.

FWIW, section 4.6 of the transport draft says: "The receiver of coalesced QUIC packets MUST individually process each QUIC packet and separately acknowledge them, as if they were received as the payload of different UDP datagrams."

**Comment by mikkelfj** [comment]
I didn't mean to say dump the connection. By dump transmission I meant the single UDP datagram - either someone messed with it, or the peer is misbehaving. In that case it makes limited sense to further process the datagram since it is obviously not up to specs.

This opens up to an on-path attack where a third party can attach content to a datagram and here you are right, but compound packets are only used during the early handshake, no? And here the best approach is to reject as much nonsense as possible.

If the peer volunteers to sign a packet that makes non sense it becomes suspecious and repeat offences might lead to disconnection and black listing. Therefore it is IMO not a good idea to use invalid packets for path discovery or any other purpose.

**Comment by kazuho** [comment]
> This opens up to an on-path attack where a third party can attach content to a datagram and here you are right, but compound packets are only used during the early handshake, no? And here the best approach is to reject as much nonsense as possible.

It is true that compound packets are only used during the handshake. OTOH I do not see why we should reject compound packets after the handshake even though we agree that doing so creates an attack vector.

**Comment by gorryfair** [comment]
Maybe it is worth identifying this design consideration in  dplpmtud - some of this is generic to working with icmp with any cooperating middle-boxes

**Comment by martinduke** [comment]
I agree with @gorryfair -- this is a generic problem with load balancers and ICMP, and there are several workarounds which are outside the scope of QUIC itself.

**Comment by igorlord** [comment]
ICMP and Load Balancers is a generic problem, but QUIC has some protocol elements specifically designed to help load balancers (Server CID).  It stands to reason that enable those protocol elements to help with ICMP processing in QUIC context.

@martinduke, which workarounds do you have in mind (unless it is PLPMTUD)?  PLPMTUD, for example, specifically states that it works most efficiently with ICMP.  So this issue is about enabling ICMP to for for PMTU in the presence of load balancers.

**Comment by gorryfair** [comment]
Just to be sure myself ..  how does that help a QUIC sender to process a PTB ICMP message?

Gorry

**Comment by igorlord** [comment]
All ICMPv6 and a growing number of ICMPv4 packets include a few hundred octets of the packet that triggered that ICMP.

A QUIC sender can be behind a load balancer that requires a Server CID to route packets to that server (this is what we designed Server CID for). However, short header packets do not contain Server CID. Hence, when doing a PMTUD probe, such servers may need to use something that would ensure the presence of Server CID in the UDP datagram. (I.e. they may want to use this method when sending packets larger than any packet for which they had received an ACK from this path before.)

**Comment by martinthomson** [comment]
Assigning to @igorlord.  Some advice on @kazuho's hack around the use of bogus long header fields would be appreciated in the form of a PR.
