### ISSUE TITLE
Gratuitous change of QHKDF-Expand in draft 10

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#1255]
Draft 10 introduces a change in the definition of the QHKDF-Expand function.

It used to be
~~~
QHKDF-Expand(Secret, Label, Length) =             
                HKDF-Expand(Secret, QuicHkdfLabel, Length)

struct {
   uint16 length = Length;
   opaque label<6..255> = "QUIC " + Label;
   uint8 hashLength = 0;
} QuicHkdfLabel;
~~~
Now it's:
~~~
QHKDF-Expand(Secret, Label, Length) =    
                   HKDF-Expand(Secret, QhkdfExpandInfo, Length)

struct {
  uint16 length = Length;
  opaque label<6..255> = "QUIC " + Label;
} QhkdfExpandInfo;
~~~
Notice that the "hashlength" parameter has disappeared. The effect is to make the implementation incompatible with the TLS implementations of HKDF-Expand that assume the presence of an HKDF label. Now QUIC implementations need specific code to implement key derivation, and cannot easily reuse the TLS implementations. And that's a pain point.

**Comment by MikeBishop** [comment]
This happened in #1077.

**Comment by huitema** [comment]
Yes, I guess it happened some time ago. But it only made its way into draft 10, we are just starting interop tests on draft-10, and of course we are finding out the issue now rather than when reviewing #1077.

**Comment by larseggert** [comment]
Agree with Christian on these TLS changes being a pain.

**Comment by ekr** [comment]
As do I. Actually the prefix change is also a pain...

**Comment by nibanks** [comment]
Just to provide a counter side of things; the label change wasn't a big issue for my implementation. The logic was already QUIC specific. Just a two line change:

![image](https://user-images.githubusercontent.com/20663557/38098669-87b21796-332d-11e8-9a8e-61d2d28691f2.png)

**Comment by kazuho** [comment]
I also feel the pain.

I think it is beneficial for most of us to be able to reuse the AEAD construction function that we have in our TLS stacks.

It might make sense to change BaseLabel  to something other than `tls13 `.

But I would prefer to keep all other parameters the same, so that the only change we need to make to our TLS stacks would be to provide a way of passing the BaseLabel as the argument.

**Comment by alagoutte** [comment]
+1 with kazuho

**Comment by huitema** [comment]
Proposing PR #1256 to restore compatibility and resolve this issue.

**Comment by tatsuhiro-t** [comment]
OpenSSL is not affected by this.  It is just a label.  Is this TLS implementation specific?

**Comment by kazuho** [comment]
@tatsuhiro-t I'd assume that it is because you are not reusing the AEAD function of OpenSSL.

Some TLS libraries provide AEAD construction functions so that application developers do not need to figure out how to use HKDF.

In case of picotls, the library provides a function named [`ptls_aead_new`](https://github.com/h2o/picotls/blob/master/lib/picotls.c#L3683-L3709) that _internally_ calls the HKDF with two different parameters; i.e. "key" and "iv", at the same time allowing the application to specify BaseLabel.

Reading https://github.com/quicwg/base-drafts/issues/1255#issuecomment-377276565, I'd assume that the case is similar with NSS, except for the fact that NSS does not provide a way to specify BaseLabel other than "tls13 ".

The voice behind this issue is that we want to continue using those functions.

**Comment by tatsuhiro-t** [comment]
@kazuho Thank you for clarifying the issue.  And no, I don't reuse AEAD function in OpenSSL because I think there are no such functions in OpenSSL.  It has only HKDF function.
I have no preference between the two; keeping as is or getting hashLength back in label because it is not a big change for me in either way.

**Comment by martinthomson** [comment]
The future is bigger than the past.  And I've already been asked why this string is null-terminated once.  This is pure cruft.  

See also https://github.com/quicwg/base-drafts/pull/1256#pullrequestreview-109208113

> Reading #1255 (comment), I'd assume that the case is similar with NSS, except for the fact that NSS does not provide a way to specify BaseLabel other than "tls13 ".

NSS doesn't export an HKDF wrapper, so anyone who wants to do this rolls their own, as Patrick has done.

**Comment by kazuho** [comment]
>> Reading #1255 (comment), I'd assume that the case is similar with NSS, except for the fact that NSS does not provide a way to specify BaseLabel other than "tls13 ".
> 
> NSS doesn't export an HKDF wrapper, so anyone who wants to do this rolls their own, as Patrick has done.

Sorry for the confusion. Reading https://github.com/quicwg/base-drafts/issues/1255#issuecomment-377276565, I assumed that it was NSS. It was minq, actually (https://github.com/quicwg/base-drafts/pull/1256#issuecomment-378590889).

**Comment by mcmanus** [comment]
I did it for mozquic/nss too.. except i actually did it from day 1 so the
recent changes were easy.

**Comment by huitema** [comment]
No point in keeping this open any further.
