### ISSUE TITLE
Connection migration optional?

### ISSUE THREAD

**Issue by pravb** [quicwg/base-drafts#1271]
Explicit connection migration is an optional feature of the QUIC transport protocol and should be negotiated. 

Server considerations:
Scalable  server deployment requires load balancing. Connection migration will require QUIC aware support from the load balancer. Most load balancers available today do not have this support. If a server does not support connection migration or is behind a load balancer that is known to not support QUIC, then all migrated traffic looks like attack traffic and will likely trip up DoS mitigation and cause a lot of traffic to failover to TCP unnecessarily.

Client considerations:
Many client devices will only have one network card or only one network available at a time. Most desktops, laptops and many tablets will qualify. Even of mobile devices, OS policy may dictate that metered connections must not be used aggressively or automatically. Applications may have policy or requirement that their traffic must not flow over specific interfaces - for example update traffic today must not flow over metered networks. There could also be cases where re-doing a fresh connection is better compared to migration because client has fresh data available to send.

For these reasons, clients which do implement migration, should make a negotiate attempt for connection migration support based on application and OS policy. Servers that know that they can support migration should negotiate and accept the request. 

Possible negotiation mechanisms are either QUIC versions or transport parameters.

Comparison with NAT rebinding:
For connection migration the only option for deployment is to upgrade the load balancers. Until load balancers add QUIC support, we have two options for incremental deployment with NAT rebinding:
1. Use two-tuple (src IP, dst IP) load balancing to continue working when NAT rebinding happens (port number change).
2. Or use four-tuple load balancing and client can do keep-alives to keep the NAT mapping open for long running persistent connections. We already have precedence for this with long poll TCP "push notification" connections.

Note that this is specifically not mentioning anything about packet number transforms and privacy considerations. But closing this issue may simplify that discussion.

**Comment by nibanks** [comment]
On the client vs server option, I think it would be fine to state that if a client doesn't want to allow/support connection migration, it just doesn't do it. No negotiation needed. This is because server migration isn't currently a supported scenario for V1.

As to how to negotiate it server side, I'd prefer to use QUIC transport parameters, instead of different version numbers. A new, optional TP could be defined, `disallow_connection_migration`, that the server could set to indicate it doesn't allow/support connection migration. Instead, if needed, the client should close existing connections and start a new (0-RTT) connection.

**Comment by ianswett** [comment]
From an operational perspective, I definitely support having a way to indicate to the client that connection migration is not supported, since there are servers that don't support connection migration in the gQUIC deployment, for various reasons.

Currently gQUIC has the equivalent of a tranport param to indicate it's not supported.

**Comment by tfpauly** [comment]
@pravb I disagree that this would be an uncommon client use case. It's important to distinguish migration from multipath; the former does not imply simultaneous use of two interfaces, just a transition between interfaces. This is exceedingly common on all mobile devices (moving between Wi-Fi, LTE, and back again), and even quite common for laptops that get plugged into Ethernet, and may be unplugged. The lack of support for resiliency at the transport layer has plagued many connections.

I agree that if there *is* an option to be negotiated, it should be an explicit disabling of the feature, and we should assume that migration is enabled by default. Opt-out is fine, opt-in is too limiting.

**Comment by pravb** [comment]
Not all devices are mobile :-), please see "client considerations" section or various reasons the client app needs control over whether to do connection migration. I believe Apple devices also have a setting to prevent aggressive use of metered connections. So app and OS policy should dictate opt-in. Of course you may choose to design the API as default opt-in but currently I am leaning the other way. This is crucial because many apps are on top of HTTP and unaware of the QUIC/TCP fork underneath and I would prefer making it opt-in to avoid things like user bill shock.

**Comment by pravb** [comment]
Also decades of protocol design has always followed the negotiate pattern for any optional functionality. Case in point TCP options. Side initiating the connection requests support and the other side agrees or vetoes. Any deviation from this common design pattern will need justification.

**Comment by tfpauly** [comment]
A few points:
- Generally, restrictions are around using metered interfaces when unmetered interfaces are available; when only a metered interface is available, things are more open. Migration in this case should be generally allowed.
- Preventing use of interfaces based on metering is separate from allowing migration. I can either let user policy or API specify that a connection should never use metered interfaces, but still migrate a connection between two Wi-Fi networks as my association changes. This also works for going between Wired Ethernet and Wi-Fi.

My main concern is that implementations, especially server implementations, MUST implement migration support, even if they allow it to be configured "off".

One of the points of migration is the path validation, which applies even in the case of NAT re-binding. For clients behind NATs, they may look to the server that they are "migrating" between ports, which is quite likely with UDP to happen quickly. By default, we should make sure connections are resilient here. The connection ID does give us the necessary support to allow the server to detect the case, and validate the path back to the client.

**Comment by nibanks** [comment]
One problem that this is trying to address is a load balancer that does 4-tuple load balancing. In that case, even a NAT rebind might end up sending the client's new traffic to a new server. So in that case, if the client really need to keep the connection bound properly, keep alives must be used.

I agree that this option shouldn't be a copout for servers to just not support migration. Though it will be in their best interest to support it (if their infrastructure does) to provide the best experience to their clients.

**Comment by pravb** [comment]
>>My main concern is that implementations, especially server implementations, MUST implement migration support, even if they allow it to be configured "off".
There is unfortunately no way to enforce this. Regardless of server support or infra issue the server must be able to veto this. I also think since QUIC has very poor signaling for DDoS prevention, server infra may dynamically start rejection migrations when under attack.

NAT re-binding can be solved by keep-alives and existing load balancers allow 2-tuple load balancing for UDP which means a NAT-rebinding where the port changes will not suffer the same issue.

**Comment by MikeBishop** [comment]
@tfpauly also hit on my biggest concern here:  What exactly gets turned off?  The point of the connection ID is the ability to survive NAT rebinds; ideally, the load balancer will be looking at the CID and not the 4-tuple at all.  After all, NAT rebinds can cross IP addresses (particularly in the Enterprise or mobile space), so 2-tuple binding isn't going to be sufficient.  But perhaps it's an acceptable Band-Aid for initial deployments.

So what are the protocol mechanics that get turned off?  The server is still going to need the ability to do path validation during the handshake (three-packet limit?), so that machinery still needs to be there.  If you're saying that you'll disable support for NAT rebinding, you're potentially going to be in a painful situation.

Regardless, the text added in #1254 states the principle that clients are the controlling party for all migrations; this remains true even if we merge #1251, because the server requests the client to perform a migration.  I think the most this restriction could get us is that clients should never intentionally change their local IP address -- though I suspect many clients will just be connecting without specifying a local IP address, so even that might have some interesting quirks.

**Comment by pravb** [comment]
Yes, incremental deployment is important. Until load balancers add QUIC support, you have two options for deployment:
1. Use two-tuple (src IP, dst IP) load balancing to continue working when NAT rebinding happens (port number change).
2. Or client can do keep-alives to keep the NAT mapping open for long running persistent connections. We already have precedence for this with long poll TCP "push notification" connections. 

Connection migration != NAT rebinding. Connection migration is a new scenario that needs opt-in and is driven by app and OS policy. For connection migration the only option for deployment is to upgrade the load balancers. Hence servers must be able to veto it to minimize traffic that looks like DoS attack and also prevent client from falling back to TCP unnecessarily when it could have simply opened a new QUIC connection and carried on. 

@nibanks good point about p2p where the negotiation must be vetoable by both sides. Let's also not discount scenarios like anycast and DoS prevention where knowing that the connection can migrate can help the server side. The traditional negotiation mechanism where initiator requests and acceptor agrees/vetoes is the most generic mechanism and will satisfy all requirements.

**Comment by ianswett** [comment]
Praveen's point is spot on.  Today's load balancers don't know about QUIC.  The initial gQUIC deployment got by without connection ID routing for a while, and as long as the idle timeout is short, it largely works and still delivered large enough gains to be worthwhile.

I'm fine with QUIC default enabling migration and then having a mechanism for disabling it, though.  I just want to make sure we do have a way to disable it in the handshake(or version if the WG goes in that direction).

**Comment by RyanAtGoogle** [comment]
To make sure I'm following correctly, I assume you're talking about
disabling explicit peer-initiated migration. We obviously can't prevent
NAT-rebinding based migration, right?

**Comment by ekr** [comment]
On Fri, Apr 6, 2018 at 4:30 PM, Ryan Hamilton <notifications@github.com>
wrote:

> To make sure I'm following correctly, I assume you're talking about
> disabling explicit peer-initiated migration. We obviously can't prevent
> NAT-rebinding based migration, right?


Well, we could cause it to fail, one assumes.

**Comment by pravb** [comment]
@RyanAtGoogle, yes this is strictly about explicit peer-initiated migration. As I mentioned before we have two possible options for dealing with NAT-rebinding and we cannot negotiate that anyways since it happens outside the control of the peers. The two options are: use 2-tuple load balancing OR do keep-alives and use 4-tuple load balancing. Please see my response before Ian's above. We cannot incrementally deploy peer-initiated migration with existing infra as Ian also pointed out.

**Comment by martinthomson** [comment]
If the concern is that the server can't manage migrations, the server can simply not send NEW_CONNECTION_ID.

I tend to think that' would be a real shame though, because the cases that need migration are pretty significant as @tfpauly says.

If we are going to build a system that relies on client opt-in, and servers that potentially don't support the feature, then perhaps we should entertain a system whereby clients request new connection IDs rather than have them provided spontaneously.

Again, that would be unfortunate because now we have created a means by which clients are segregated based on capabilities.  Worse, that segregation might be based on their ability to pay for access, if a "metered" flag could disable migration.

**Comment by kazuho** [comment]
I agree with what @martinthomson says.

A server can always decide to not send a `NEW_CONNECTION_ID` frame (it's not even a "SHOULD" even though some if not many of us anticipate that the server's sending it), and then the client would notice that there is no point in doing a gratuitous migration.

I also think that for the data-center use-case, nobody would object for QUIC connections not doing gratuitous migrations.

For the connections originating from the browser, I believe that a server that does not send a `NEW_CONNECTION_ID` frame should declare an idle timeout of somewhere below 30 seconds, so that the client would try to either keep the connection alive with no rebinding (by sending pings) or to reconnect in 0-RTT after quiescence that could have caused a rebinding.

**Comment by ianswett** [comment]
I'm ok with the "if you don't support migrations, don't send a NEW_CONNECTION_ID" recommendation.  I think it's worth adding one sentence about that to the transport draft, if that's our preferred way of indicating connection migration isn't supported.

**Comment by pravb** [comment]
"if you don't support migrations, don't send a NEW_CONNECTION_ID" mechanism can work as long as it stated that using a new connection ID for gratuitous migration is a MUST. I would add this requirement in addition to the sentence that @ianswett requested. 

The only downside I can think for this mechanism is that it will preclude use of multiple connection IDs on the same path without migration. Do we foresee use of multiple connection IDs for the same connection for unreliable semantics? Is there any other use case for NEW_CONNECTION_ID outside of gratuitous migration that will get affected?

>we should entertain a system whereby clients request new connection IDs rather than have them provided spontaneously
One problem with requesting connection IDs is that this will anyways have to be really early in the connection because if client loses cellular connectivity it will not have any means to contact the server over wifi. So for the parking lot problem, up front supply of at least one connection ID seems to be necessary?

**Comment by nibanks** [comment]
One down side of implicitly stating (explicit) migration is not supported, just by the server not providing NEW_CONNECTION_IDs, is that the connection can't use different connection IDs for the same path, even if the server and load balancer support that scenario. Recently, the spec was updated to allow for changing the CID after some period of quiescence, with the expectation that NAT rebinding will likely happen. That wouldn't work with this model.

My personal preference here is still an explicit indication (most likely via TP) that the server cannot support explicit migration / client IP address changes.

**Comment by erickinnear** [comment]
There's still the issue that many expected migrations aren't explicitly initiated by the client but rather by the network (NAT rebinding, etc). If we want clients to be able to switch connection IDs on the same path, and we also want to be resilient to the path changing out from underneath the client, then we need to be very careful how we specify such a transport parameter.

**Comment by tfpauly** [comment]
If the option is explicitly to disable migration, and migration is assumed to be supported by default, I think the text can be written sufficiently carefully. We want to allow the default case for clients to work.

The peer-to-peer case of one peer being stuck behind a NAT, signaling that the other peer shouldn't migrate is an interesting point, and one of the points I find more compelling for not migrating automatically to the same address. It is a bit comparable to the NAT detection mechanisms used by IKE, which determine some later protocol behavior. Let's make sure to call out this scenario in the text, as well as others, perhaps specifying that deployments that don't fall into these scenarios in which migration is not useful SHOULD NOT disable migration, so as to encourage mobility of clients.

Doing the negotiation in the handshake as a TP is preferable to version indication in this case, I'd argue.

**Comment by pravb** [comment]
@erickinnear supporting connection migration on server side requires updating of load balancers to be QUIC aware which will not be possible in many deployments for a while especially when the web server and the load balancer are not under the same administrative domain. In these cases even NAT rebinding will not work correctly and the solution is to use keep-alives if connections become inactive and want to be long-lived.  So if the server doesn't negotiate the TP then the client can automatically turn on keep-alives.

@tfpauly I am fine making the default as enabled and the TP flips it to disabled. The goal is to allow incremental deployment until load balancers can be upgraded.

**Comment by erickinnear** [comment]
Yes, I think we're in agreement that it will be useful to have a transport parameter, I just want to make sure that we're careful not to back clients into a corner where they cannot behave correctly due to influences outside of their control. A client that is behind a NAT might be surprised that the server thinks it's behaving incorrectly if it wasn't aware that some portion of the routing/NAT binding changed significantly. 

That's mostly a wording issue, I think, not a problem with the concept itself. 

It almost seems like it could be as simple as using the same terminology that we used previously ("local address" vs. "from an IP address"): 
```
The server does not support connection migration (link to the other section). 
Clients MUST NOT send any packets, including probing packets (probably 
use the real name from later), from a local address other than that 
used to perform the handshake.
```
It might be interesting to add, either in the definition or later where the second reference is made, a note that clients may wish to be more aggressive about using keepalives if connection migration is disabled.

**Comment by MikeBishop** [comment]
@erickinnear, what do you mean by "use the real name from later"?  "Probing packets" is a defined term later in the document.

However, I like the remainder of these updates and have made them, plus a forward reference to the definition of probing packets.

**Comment by janaiyengar** [comment]
@martinthomson : There's another use case, which I had to think about when getting connection migration out for GQUIC. This is where if you have a CDN server inside of an ISP, you want to explicitly disable migrating connections to other client ISPs, since that would constitute "leakage" at the server. You may still want to hand out new CIDs to allow a client to use it after a long quiescent period, in anticipation of NAT rebinding. An explicit signal from the server is a clear policy indication to the client not to migrate connections across networks.

This is admittedly difficult to enforce at the server without being too restrictive (by not handing out new CIDs). As I see it, a TP tells the client to not migrate connections across network changes. I would even suggest that a server MAY detect migrations across networks and close the connection with PROTOCOL_VIOLATION if it finds that a client violated this policy.

**Comment by erickinnear** [comment]
@MikeBishop by "use the real name from later", I was just thinking that we should use a defined term that we can link to -- if "probing packets" fits the bill, then that's great!

**Comment by erickinnear** [comment]
Another thought, spurred by Rui's comment on the PR: 

Sending this TP means that the other end doesn't get to *knowingly* initiate migration. However, both sides (or the client since we're currently not direction-agnostic) still need to handle path challenge frames and generate path response frames. 

If this is just for use in datacenter environments, then there isn't really anything gained by having a TP, just don't do migration. 
However, I do still see the value for cases, especially until load balancers can cope with connection IDs, where you'd want to indicate that a client on the public internet shouldn't perform migration. 

Of course, even in that case, you still have to implement all the code on the server itself to deal with the observed client endpoint changing.
