### ISSUE TITLE
We have two things called "frame"

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#128]
The transport protocol has frames, and STREAM frames can contain frames for the HTTP mapping.  It's confusing.  We should work out how to deal with that.

**Comment by MikeBishop** [comment]
I've been trying to consistently say "a QUIC <frametype>" in the HTTP draft if I refer to a non-HTTP frame.  Is that editorial convention sufficient, or were you actually looking to change terms here?

**Comment by martinthomson** [comment]
Picking another name "segment", "chunk", "lump", "whatsit", would be superior, but that's a good working solution.

**Comment by mnot** [comment]
H2 already has frames; maybe the new thing should have the new name. E.g., 'QUIC segments".

YMMV.

**Comment by mcmanus** [comment]
I don't like quic-segments because
1] it implies an ordering (and seqno) and the quic-frames aren't really
ordered unless they are streams
2] the term doesn't line up well with tcp segments (which are 1:1 with
unfragmented IP).. and quic and tcp are at the same 'layer' - so confusion.

The best (but still imperfect) solution I have is to change http frame to
http record. It overlaps with TLS of course (which isn't all that
desirable), but it uses the term pretty much the same way - to provide
delimiters within a QUIC stream.

The other idea I had was "http-control-segments".. I think segment is a
better fit here as compared against renaming all quic frames to quic
segments (again ordering and offset are present) and it emphasizes the
native integration between hq and quic for data but not control.

I'm not especially concerned that we would be changing the h2-frame
language.. HQ doesn't need framing in many of the same places that H2 did
so a change in nomenclature is ok to avoid confusion with the transport.

**Comment by ekr** [comment]
Other colors for this bikeshed:

Records
Blocks
Chunks
Packets
Datagrams

**Comment by LPardue** [comment]
A colleague of mine suggested [vesicle](https://en.wikipedia.org/wiki/Vesicle_(biology_and_chemistry))...

**Comment by ekr** [comment]
Also:

Cell
Fragment

**Comment by janaiyengar** [comment]
Why does the HTTP document need to talk about QUIC frames? Those are
QUIC-internal, and HTTP only needs to refer to QUIC streams, right? QUIC
itself doesn't encounter HTTP frames, so QUIC never refers to other
protocol frames.

I think it's fine to reuse frames and streams for the key reason that no
matter what you choose (unless you choose "vesicle"), you're likely to
conflict with some app. "Stream" is even harder, since video/audio might
use it in completely different ways than QUIC, but it's important to note
that the scoping is different. ("A video frame can be mapped to a QUIC
stream, and a video stream is made up of video frames.")

I've always found qualifiers ("QUIC", "HTTP", "video") to be adequate.

**Comment by MikeBishop** [comment]
We might be able to get out of HTTP referencing QUIC frames, but that’s just wording.  The frames represent events which occur.  We currently reference:

  *   On the wire, data is framed into QUIC STREAM frames, but this framing is invisible to the HTTP framing layer. A QUIC receiver buffers and orders received STREAM frames, exposing the data contained within as a reliable byte stream to the application.
  *   (Discussing CONNECT)  All QUIC STREAM frames on the message data stream correspond to data sent on the TCP connection. Any QUIC STREAM frame sent by the client is transmitted by the proxy to the TCP server; data received from the TCP server is written to the data stream by the proxy. Note that the size and number of TCP segments is not guaranteed to map predictably to the size and number of QUIC STREAM frames.
  *   The following error codes are defined by HTTP for use in QUIC RST_STREAM, GOAWAY, and CONNECTION_CLOSE frames.

This doesn’t actually bother me much, because I already have to compare/contrast with HTTP/2 frames.  If they’re HTTP/QUIC frames, I just call them <X> frame.  If they’re something else, I call them <protocol> <X> frames.

**Comment by MikeBishop** [comment]
The above solution has proven to be sufficient for now.  Though if anyone wants to make a case for QUIC vesicles, feel free to reopen.

**Comment by LPardue** [comment]
As someone that has written an I-D that needs to reference both QUIC Transport and HTTP documents, I have struggled with ensuring the correct frame-type is being used.

I have so far used the convention <x> <[ QUIC | HTTP/2 ]> frame. Changing the order is not problematic. I think there would be benefit in defining a consistent style, this can help both readers and writers of specifications.

 Furthermore, I recently took the position that HTTP/2 is the wrong term when talking about HTTP/QUIC frames. I will address this, should I call them HTTP/QUIC or would the abbreviation HQ frame also be ok?

**Comment by MikeBishop** [comment]
I agree with you on that position, and one of my first editorial changes to the draft was to excise all occurrences of the term "HTTP/2 over QUIC."  HTTP/2 and HTTP/QUIC are not the same protocol.  Just as h2 is the ALPN token and a convenient shorthand for HTTP/2, hq (or HQ) is a perfectly reasonable shorthand for HTTP/QUIC.  I tend to write it out in anything official, mostly to avoid anyone thinking I'm talking about headquarters.

I'm fine adding protocol frame naming to our notational conventions.  Reopening to track that suggestion.

**Comment by LPardue** [comment]
SGTM, thanks Mike.
