### ISSUE TITLE
Can Retry or VNego be compound with other packets?

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#1292]
The spec now says that "A sender can coalesce multiple QUIC packets (typically a Cryptographic Handshake packet and a Protected packet) into one UDP datagram." Should that be qualified?

For example, does it make sense to compound a Version Negotiation packet with any other packet? Of course, there is no length field in VNego, but one might imagine combining a handshake packet and a VNego packet, maybe as away to send an ACK for the client init. My feeling is "don't do that". Should it be said?

The same goes for the stateless retry packet. Does it make sense to combine it with a handshake packet?

**Comment by MikeBishop** [comment]
Perhaps worth noting.  However, if you send a packet with the version the client proposed, you've accepted the version, so the Version Negotiation packet would then be ignored (existing text).  Retry might get a little hairier.

**Comment by kazuho** [comment]
While I agree that coalescing some types of packets does not make sense on the sender side, I think that the receiver needs to handle each QUIC packet coalesced into a UDP datagram individually, regardless of their types.

Otherwise, coalescing could become an attack vector.

When coalescing is not used, an on-path attacker needs to do AES calculation to inject a packet that will be processed (instead of being dropped) by an endpoint. Coalescing should not change that.
