### ISSUE TITLE
Move ALPN information to HTTP mapping

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#13]
The TLS document doesn't really need to include this.

**Comment by MikeBishop** [comment]
Touches on #44 and #45.  Does the HTTP mapping need to require that the crypto protocol be TLS?  If not, how does it know that ALPN in particular will be used?  It would just specify that the negotiated protocol should be "http/q" or whatever we wind up calling it.

I think where this leads me is that one of the requirements of the crypto handshake protocol is application-layer protocol negotiation, which the TLS mapping will satisfy by using the ALPN extension.

**Comment by MikeBishop** [comment]
Working on #87 and looking more closely at this, I'm not finding content I think I should adopt.  A fair bit of your text about how TLS and QUIC interface belongs in the core spec, because it's true of how *any* crypto protocol is expected to interface with QUIC.  But I'm not seeing HTTP-specific information in the TLS document -- did you already fix this, or do we actually disagree here?

**Comment by MikeBishop** [comment]
@martinthomson, I'm closing this with no action per previous comment.  If there's something specific you intended here, please reactivate with specifics.
