### ISSUE TITLE
Swap largest reference and base indices

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1362]
The value of the base index can be set at the start of an encoding pass.  Swapping the two values means only one change for the encoder when it comes back to update the header.

It also means less likelihood of a change in size.  If largest reference moves near (for example) 127, then its encoded size needs to change.  But it would be rare to find that the largest reference would differ from the base by more than 127 octets, and it's even something an implementation could block to avoid size changes.

The corner case here is where there are NO dynamic table references at all.  I found this to happen in tests occasionally.  This alternative design is no better in that regard because both values need to be set to 0 in that case.  Using a negative zero offset as a special case is a great idea, but the value exists.

**Comment by MikeBishop** [comment]
To save a day/night cycle, I read that as:

- The proposal is to encode LR relative to Base rather than the other way around, because LR will usually be +/-127 from Base all the time.
- When LR turns out to be zero and Base is >127, the suggestion is a sentinel value (negative zero) mean "actually zero" instead of "difference of zero."

**Comment by afrind** [comment]
Logically I prefer LR first - it's the first thing needed and the decoder only needs to read one variable length integer out of the transport instead of two.  It's the only value that needs to be updated after encoding (unsure why you said "Swapping the two values means only one change...").

With -0 you can get away without resizing the encoding of LR and shifting the buffer *most* of the time, but you'll still need code to handle the case where it does resize, and this code path will be rarely exercised, or worse -- omitted.  If we were going to special case -0 => LR=0, we should do this universally rather than only when Base > 127.

**Comment by afrind** [comment]
Ah gotcha (I know Martin couldn't be wrong, what was I thinking?).  I guess my argument is that since you can't know the length of the prefix before you encode, it's not worth trying.  Can you help me understand the advantage of doing so?  Or the complications caused by writing the whole prefix at the end?

**Comment by martinthomson** [comment]
I'm going to abandon this one.  We discussed it and decided that LR is better as the first.  It reduces the complexity of the blocking code by a smidge.  I'll change my code.
