### ISSUE TITLE
Tracking of header blocks for reset streams

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1371]
There isn't much advice in hq or qpack about tracking of header blocks, and it's one of the hardest parts to implement.  The nastiest bit is dealing with reset streams.  If a stream is reset, then all the header blocks are no longer blocked, and none of the table entries they reference need to be tracked.

However..., tracking can only stop once the peer has received the reset, otherwise the peer might read the pre-reset data and block, increasing the number of blocked streams.  So we need to know when the peer stops caring, either because they sent STOP_SENDING or received RST_STREAM.  But we don't have a signal for this.  The header block acknowledgment only applies to a single header block, not the entire stream.

It's also a timely reminder that APIs need to surface when an inbound stream is stopped (STOP_SENDING) or reset (RST_STREAM).  In either case, an HTTP receiver would need to send whatever signal we're missing here.

**Comment by afrind** [comment]
Yes I raised this earlier (which @MikeBishop filed as #1176).  That got closed by making the consequence of the race condition a stream error rather than a connection error, since the race is likely to be quite rare.  eg: the encoder can reset all its state when it sends the RST_STREAM, rather than when it is acknowledged.  I think when we added the setting for number of blocked streams we re-introduced the connection level error.  I wasn't really thrilled with that solution but I'm not thrilled by adding an application level stream-reset-ack either. 

Assuming we have to do this, do you think this should be an HTTP frame sent on the control stream or a QPACK instruction sent on the decoder stream?

**Comment by MikeBishop** [comment]
When I'd sketched it out before, I was envisioning a flag on the decoder's ACK that effectively says "one header block / all header blocks".  When a stream was reset, it would ack all header blocks on that stream to indicate it was no longer tracking them.

However, that gets a little less obvious with #1370, since this is no longer really an acknowledgement, it's a "don't care about."  In that case, I might cast it as a separate instruction.

**Comment by martinthomson** [comment]
A separate instruction seems best given the differences.  The encoding is better that way too.  Then you can use a one-bit instruction for the common "ack a single header" instruction and two each for the "ack insertions" and "stream destroyed" instructions.

**Comment by MikeBishop** [comment]
@ianswett pointed out that this could also be solved by taking the blocking setting back to a Boolean, and @afrind said he doesn't feel as strongly about the integer limit now that he's implemented it.

**Comment by ianswett** [comment]
As Mike said, I prefer getting rid of the limit on blocking refs unless there is a very compelling reason to keep it.

**Comment by afrind** [comment]
Discussed in Kista.  Because the problem exists for eviction races as well, and those stream level errors MAY be promoted to a connection level error at the decoder's discretion, we need to have application level acks for reset streams, which will solve both problems.  If there is strong sentiment to replace MAX_BLOCKED_STREAMS with a boolean, please open a separate issue.
