### ISSUE TITLE
Stateless Reset Eternal Ping Pong

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#1443]
Two p2p server systems with compatible CID formats might accidently have a stateless reset routed back and forth between two are more servers that do not understand the packet context and consequently respond with a new reset. This can leave zombie resets spinning forever.

An advanced attacker might be able to take advantage of the above.

What is the motivation for making the reset undetectable in the first place?

**Comment by MikeBishop** [comment]
I think the "compatible CID formats" piece of this doesn't matter.  The recipient of a short header packet won't be able to identify the CID because the length is unknown.  It will guess the length it probably used (assuming the remainder is payload) and generate a Stateless Reset with a random CID/body.

But yes, in the absence of loss, this will continue forever.  An attacker could start the process with a spoofed source address.  Perhaps a suggestion that endpoints SHOULD limit the number of Stateless Resets they will send to a given address?  If each side sends back even one fewer SR than it received incoming packets, the attacker doesn't get much return from its spoofed traffic.

**Comment by mikkelfj** [comment]
I think it would be easier to detect resets, but that is apparently not an option.

Rembering source address in a stateless context is not ideal. But exponential decay can be used:

Whenever an endpoint feels the urge to send a reset, it should ignore that urge it with a probability x, 0 < x <= 1 such that reflected resets will eventually die out.

**Comment by kazuho** [comment]
One way of fixing this is to forbid sending a stateless reset unless the size of the stateless reset will be smaller than the packet that has triggered the stateless reset.

Note that endpoints are already required to send a large packet after quiescence, if they want to see stateless reset in case the server has lost state. See the following statement in [section 6.10.4](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.6.10.4):
> An endpoint SHOULD NOT send a stateless reset that is significantly larger than the packet it receives.

**Comment by mikkelfj** [comment]
> One way of fixing this is to forbid sending a stateless reset unless the size of the stateless reset will be smaller than the packet that has triggered the stateless reset.

This would require a significant size reduction which could be observable (I still don't understand why the reset must be hidden). It would also not address transmissions of many very small messages in separate packets.

I think the statistically dropping every N'th packet, say 4'th, would work well because in most cases the reset happen as expected, and when not, it happens on retransmission just as if a packet were lost.

**Comment by kazuho** [comment]
> I think that statistically dropping every N'th retry packet, say every 4'th, would work well because in most cases the reset happen as expected, and when not, it happens on retransmission just as if a packet were lost.

I might argue that statistically ignoring a packet goes against the goal of stateless reset; i.e. provide a signal that the connection has been reset *as early as possible, before timeout happens*.

IMO, the method to fix the issue should be either remember the peer address (as has been suggested by @MikeBishop in https://github.com/quicwg/base-drafts/issues/1443#issuecomment-398842429) or to limit the size (as I have suggested in https://github.com/quicwg/base-drafts/issues/1443#issuecomment-398915066).

**Comment by martinthomson** [comment]
I think that I'm with @MikeBishop here.  37 octets is quite a bit bigger than the smallest packet that might be sent, and if there is at least a chance of getting a reset back, then connections will die more quickly, though it might only be in the aggregate.  Advising reduced probability when the reset is not smaller than the packet it responds to seems right.

If you consider that we want to have resets of varying size, that's probably good, because you don't end up clamping resets to the size of the incoming packet.  I'm sure that you can devise a simple scheme that randomizes probability as a function of the increase in packet length over the incoming packet.

**Comment by mikkelfj** [comment]
I'm all for reducing reset size, but it can't stand alone as @martinthomson also summarized. Probability is needed for small packets.

**Comment by igorlord** [comment]
If a typical sender of a SR is the server, and a typical thing that a client sends is just a ACK, would size-based squelching of SR prevent most SRs from being sent?

**Comment by mikkelfj** [comment]
@igorlord not if the additional statistical rule is appied for small packets. But it would results in some some ACK's not triggering a reset. Since ACK's won't be retransmitted it could lead to a mexican standoff until timeout. The ACK's would be a response to data still in the pipeline. A server going down is probably not online again or failed-over before that pipeline has drained. So I doubt it will make much difference.

However, there are also cases where many small packets are sent such as play position updates. But then chances are higher that one of the packets trigger a reset.

**Comment by mikkelfj** [comment]
Can you explain how this would work for very small packet sizes? I'm not sure what TTL means here - how long state is remembered about an unknown endpoint?

**Comment by martinthomson** [comment]
TTL means the TTL field in the IP header.  It is a number that routers decrement until it reaches 0, at which point the packet is dropped rather than forwarded.

**Comment by igorlord** [comment]
Could someone explain the mechanics of the TTL proposal?

When a packet arrives, it has a residual TTL (originalTTL - #hops). So the proposal is to send a SR packet with the residual TTL and not reset the TTL to the server's default value?

This is somewhat brittle, since it depends on both peers to implement TTL logic correctly. If someone does not, pointing a broken endpoint at a victim would cause a forever-loop.  Even if everything is implemented properly, this could cause over 100 bounces per reset -- a powerful amplification attack.

**Comment by ianswett** [comment]
Yes, it relies on both sides doing this.  If you're mostly worried about your own infrastructure ping-ponging with itself, this does solve the issue, though as you said, it could take a while.

Separating out client ports from servers ports is also a potential mitigation, as long as the client doesn't send these in a given use case.

**Comment by dtikhonov** [comment]
> not unless you specifically construct the IP header that way, and that isn't very practical for a general purpose implementation.

This is a good point.

**Comment by martinthomson** [comment]
> When a packet arrives, it has a residual TTL (originalTTL - #hops). So the proposal is to send a SR packet with the residual TTL and not reset the TTL to the server's default value?

Yes, though I would act as a router and decrement.

> that isn't very practical for a general purpose implementation.

If you can't set TTL, or reduce its size, the recommendation would be to not send the packet.

**Comment by marten-seemann** [comment]
> > that isn't very practical for a general purpose implementation.
>
> If you can't set TTL, or reduce its size, the recommendation would be to not send the packet.

I don't think this is a good solution. I don't have access to the TTL field in Go, but I wouldn't deploy QUIC with disabled Stateless Resets. I'd rather do something non-deterministic, or keep a bit of short-lived state around to prevent looping.

**Comment by ianswett** [comment]
A short lived time wait list with exponential backoff is what I plan to deploy.  Of course, I already have that, so conveniently it fixes this case.

I do think setting TTL can avoid loops in some useful cases, but I agree that if everyone can't set it, it's potentially not a practical solution.

**Comment by martinthomson** [comment]
Maintaining state for 5-tuples on which a stateless reset was sent is probably the best solution, yes.  That would be a valid alternative to this.  Documenting that in the form of (maintain state || (reduce size || reduce TTL)) seems reasonable.

**Comment by ianswett** [comment]
A simpler idea I just thought of was making the stateless reset < SOME_SIZE and not responding with a stateless reset unless the payload was > SOME_SIZE.  

Given ACK-only packets are relatively common, particularly in response to a large packet, possibly we could advise generating an ACK-only sized packet and sending that in response, with a constraint it must be less than whatever the magic size is.

I think this completely fixes the issue, assuming it's workable in practice.

**Comment by martinthomson** [comment]
Also, ACK-only packets are generally too small.  In the extreme case, an ACK frame is only 4 octets, leading to a minimum-sized ACK-only packet that is a mere 22 octets.  Coincidentally, that's the minimum size of just the connection ID part of a stateless reset.

**Comment by ianswett** [comment]
ACK-only packets are very common, typically the second most common packets after full-sized packets.

If we think 0 length server to client CIDs are the most common, maybe we should use those for stateless resets from server to client.  If we think 8 bytes are common from client to server, then 8 + typical ACK length?

This also has the perk that the stateless reset is smaller.  That being said, I'm happy with not fully stateless resets with exponential backoff, but I think this is also plausible.

**Comment by mikkelfj** [comment]
I was thinking through the ACK scenario earlier - there are two points:

1. ACKS eventually die because they are generated in response to traffic that does not arrive (unless routing is seriously messed up)
2. There can a backlog ACK's before they die out, and perhaps RESET need to act on these timely.

But there are also ping frames and small message updates like player status in games or IoT temperature measurements.

**Comment by martinthomson** [comment]
An ACK- only packets seem like they are less critical to reset. The sender of an ACK- only packet is unlikely to send again shortly. That cuts two ways though. Either it would be a huge optimization to get the reset, because it would otherwise be a fair while until the next packet would be sent; or it would be wasteful, because the endpoint isn't planning to use the connection any time soon.

To me that suggests that ACK-only packets aren't worth paying special attention to in the design, even if they are super common. 

Either way, guessing the size of the peer's connection ID doesn't seem right to me.

**Comment by ianswett** [comment]
To clarify, I'm suggesting the reset packet attempt to look like an ACK-only packet instead of attempting to look like a full-sized data packet.

I'm not trying to ensure a reset is sent in response to an ACK-only packet.

**Comment by mikkelfj** [comment]
OK, I missed that. Back the < > SOME_SIZE, why would it be worse to statistically reset packets below SOME_SIZE than to ignore them entirely? That is what I would suggest. Above SOME_SIZE it is fine to gradually reduce size or to choose a camouflaged ACK rendition.

Some argue that gradual size reduction is not a problem but I think that unless he reduction is aggressive, it can lead to heavy amplification attack, similar to slow TTL reduction. In that light, simply sending an ACK-like reset would be safer because it aggressively drops the size down.

**Comment by ianswett** [comment]
I didn't miss that point about ANY connection, I'm just not sure that is the goal we want given the design we have.

We have two goals:
1) Look like a plausible non-reset packet to a passive observer. ie: "to the extent possible - indistinguishable from a regular packet"
2) Allow the peer to be reset via processing the agreed upon token.

I think number 2 only requires the packet arrive at the right IP/port, since we've already established that if the peer is relying on it's CID coming back, this design is impractical.

This makes 1 the more interesting one.  The server receives a packet it can't associate with a connection.  At that point, it may have knowledge of what typical client CIDs are for the given application(ie: 0, 8, etc) and what traffic it commonly sends, so it may be able to craft a more plausible reset than the min 37 octet suggestion.  That makes me think the current min should be relaxed, to the min non-empty packet size, though I admit by itself that makes this problem slightly worse, not better.

If we think requiring sending larger packets is extra burden on observers that want to reset connections, then a larger packet is certainly better, but I don't think we think that's a real form of protection?

**Comment by martinthomson** [comment]
What is typical doesn't matter.  What matters is what was used on that flow.  And we have to expect that (in the spirit of greasing at a minimum) some clients will use long connection IDs.

Unless you believe that we are OK in sending a signal to on-path entities, that is.  But we had that debate already.

**Comment by ianswett** [comment]
For a given flow, one of two things is true:
1) The CID towards the client is 0-length:  In this case, almost any random-looking packet is plausible.
2) The CID towards the client is >0-length: In this case, any return packet will have a different CID from the correct/previous CID, so an observer would have to assume the server decided to change CIDs.  In which case, it's difficult to know what to assume, though changing CIDs by the server may be considered an "unlikely" event by observers and thus may be an indication of reset, since typically we expect the client to initiate CID changes.  I think this is a natural fallout of the asymmetric CID design that I didn't fully appreciate until recently.

**Comment by martinthomson** [comment]
I see, so if the client requested 18 octet connection IDs, then a change to 8 is perhaps acceptable because it just looks like it changed to a shorter value, which is possible?

What if no other connection from that client has ever used a shorter connection ID?

**Comment by ianswett** [comment]
That's a good question.  At the moment for HTTP, I think it's reasonable to expect <=8 byte CIDs towards the client, with 0 being very common.   For WebRTC, I expect 0 bytes to also be very common, but there may be use cases when non-zero is necessary.  It's difficult for me to speculate about other applications.

**Comment by martinthomson** [comment]
It's possible that we could allow the 20 octets of randomness to be shortened, though observe the risks inherent in doing that.  Would that be acceptable?

**Comment by ianswett** [comment]
That seems reasonable to me.  

I'm trying to understand what the constraints on the design space are, and I'd love to see a ping-pong solution that ended with a single reset sent, but I understand that may not always be practical.
