### ISSUE TITLE
Negative Connection ID Sequence Number

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#1484]
Follow-on issue from #1465.  The existing text (restored but not changed by the PR) defines the CID selected during the handshake to be Sequence -1, and the CIDs issued via NCID frame to begin at zero.

@nibanks objects to having negative sequence numbers.  We could, of course, make the handshake-negotiated CID be number zero, but then NCID with a sequence of zero would either be invalid or pointless.

Arguments for/against, or alternative solutions?

**Comment by nibanks** [comment]
It's going to be painful to have a variable in memory that can represent both a variable length integer (UINT64) and a negative number. There is no precedent for it already. I'd **really** like to only use positive numbers.

**Comment by martinthomson** [comment]
Conveniently, varints can use int64_t because they only use the lower 62 bits.  Also, uint64_t(0)-1 underflows reliably to UINT64_MAX if you want to keep your variables unsigned.

However, I think that the -1 recommendation is wrong, particularly in light of the changes to Retry and the server's preferred address transport parameter.  We should rephrase and avoid making any recommendation about how to handle these.

Those same things makes me very reluctant to recommend starting at 1 or 2, but if we don't require a contiguous sequence of connection IDs, then maybe some implementations can skip a few without consequence.  We probably shouldn't require contiguous sequence numbers anyway because of the potential for some endpoints to consume values that aren't seen and then they might decide not to provision their peer with matching connection IDs.  The frame isn't that small, after all.

**Comment by MikeBishop** [comment]
The text currently says they SHOULD be contiguous.  The advantage to contiguity is that you can speculatively issue batches and assume with some accuracy that the sequence numbers you pick will match the sequence numbers your peer picks.

Loosening that to simply ordered seems touchy, since one since effectively becomes dominant in picking which sequence numbers will actually become useful. (Only the intersection of the sequence numbers chosen by each peer can be stably used.)

**Comment by martinthomson** [comment]
Yeah, I think that we'd want to retain the "SHOULD", but we might expand this to mention that gaps are generally only OK in the case where the corresponding sequence number was used on a dead path (or because you don't want to count backwards from zero to account for the handshake and server preferred address).

**Comment by martinthomson** [comment]
After realizing that you need to consume a sequence number if you intend to implement the preferred address, I think that this is the best approach.

At that point, we might as well concede that there will be a gap at the start in a lot of cases.  What @kazuho proposes here seems OK.  I don't think that the Initial packet needs a slot reserved, but the difference between one unused value and two isn't worth worrying about.

This does nothing for connection IDs provided with Retry, but the handling of Retry is reactive and can probably overwrite the zero index as it goes.

**Comment by mikkelfj** [comment]
Just a comment from the sideline - I'm not really keep track of NEW CID atm, but I'm worried that a peer can force feed new CID's so the state for an idle connection grows large. Any protection / guidance on this? Ideally a passive QUIC connection should only need to store a few ID's and counters.

**Comment by MikeBishop** [comment]
I had been playing with adding a RETIRE_CONNECTION_ID frame for that purpose.  As I start digging into when you can forget an old CID, you run into situations where the peers don't agree, such as #1495.
