### ISSUE TITLE
Varints for numeric transport parameters

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#1608]
Using varints instead of fixed size fields would allow us to save bytes in the common case, while allowing for a wider range of values if needed. Most importantly, we'd be more consistent in how we encode values across the protocol.
I'm not sure how to correctly write that in the TLS presentation language though.

**Comment by ekr** [comment]
The TLS presentation language doesn't currently support varints. I suppose one could add it as a feature.

**Comment by ianswett** [comment]
SGTM.

**Comment by kazuho** [comment]
I think that it makes sense to use varints for representing the **values** of the TransportParameters (i.e. the values defined in [section 6.6.1 Transport Parameter Definitions](
https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.6.6.1)).

I do not oppose to using varint for TransportParameterId.

OTOH, (I do not necessarily assume that you meant this, but) I would oppose to using varints for QuicVersion, or using varint for representing the size of the blocks (i.e. the length of the block represented using `<x..y>` notation). This is because QuicVersion is a fixed length integer in QUIC as well, and because we do not have a way to express an optional block in QUIC.

**Comment by mnot** [comment]
Discussed in NYC; @marten-seemann to drive to a conclusion by 15/10.

**Comment by ianswett** [comment]
It's 10/16, any updates @marten-seemann

**Comment by marten-seemann** [comment]
@ianswett: Sorry for the delay. Just sent out a mail to the list.

**Comment by martinthomson** [comment]
Fixed by #1947.
