### ISSUE TITLE
are flow control frames really idempotent?

### ISSUE THREAD

**Issue by siyengar** [quicwg/base-drafts#1612]
we say that in the draft

"All QUIC frames are idempotent.  That is, a valid frame does not cause undesirable side effects or errors when received more than once"

However max stream data has one peculiar property, i.e. lets say a sender sends 4 packets:

packet 1:
max_data ->  value = 1000

packet 2:
max_data ->  value = 2000

packet 3:
max_data ->  value = 1000

packet 4:
max_data -> value = 200

Here the sender, either due to malice or a bug decides to send the same max data in 2 different packets.

Let's say no loss occurs and the receiver gets all the packets. Obviously the receiver could ignore the max data in packets 3 and 4, however a receiver who wants to help peers prevent flow control bugs from happening can know that the peer had sent packet 3 after packet 2 and had thus attempted to accidentally reduce the value. We currently do this in our implementation to help avoid nasty issues like this and has helped us detect bugs. However, after some offline discussions with @marten-seemann and @kazuho it seemed like people had mixed opinions about this one. One could say that the sentence about idempotence could warrant a receiver allowing this behavior, however what about packet 4 if the sender had clearly never sent the value 200 before?

**Comment by siyengar** [comment]
Ya I think a MAY should suffice on the receiver side and I would be very happy with a MUST on the sender, however the general sentence about all QUIC frames are idempotent might mislead people into thinking that they can send any frame at any time. Do you think that "a valid frame" covers this case?  That is after sending a higher max data frame lower max data frames become invalid.

**Comment by marten-seemann** [comment]
I think the sequence of values sent in packets 1-4 should be valid, and that an implementation MUST NOT error when receiving these.

When retransmitting a packet, you can do two different optimisations:

1. you can update the offset in the MAX_DATA frame, and thereby save a few bytes that you'd otherwise spend on sending a new MAX_DATA frame.
2. you can retransmit the MAX_DATA frame as is, and instead keep track that packet X is a retransmission of packet Y. When receiving an ACK for X, you then know that Y doesn't need to be retransmitted (and vice versa).

According to my measurements, 2. is a much better optimisation than 1. However, it can lead to exactly the sequence that you described. 
It might be possible to combine 1. and 2., but this will create **a lot** of complexity: If the retransmission of a packet contains an updated MAX_DATA frame, you can't just cancel the retransmission for that packet if the original packet is acknowledged, since you need to make sure that the MAX_DATA containing the updated offset is delivered reliably.

I see little value in enforcing that peers implement optimisation 1., since the expected performance gains are minimal, while 2. offers a real benefit on lossy connections.

**Comment by siyengar** [comment]
When you're doing 2 why would you not send the latest update?

We also do 2, but we send the latest update. We additionally keep track of the packet number of the last sent max data per stream and per conn, that way we know when we get an ack for X we know that we still have a max data pending. It's not super complex :)

**Comment by martinthomson** [comment]
So this was opened and closed already in #447, though there wasn't a whole lot of discussion and the issue was closed with no action.

The action that @marten-seemann suggests is slightly bad - retransmitting packets is rarely the best choice from a correctness perspective - but the conclusion from the other issue was that there was little point in allowing endpoints to police continuous increases to limits.

Note that this advice would also need to apply to stream limits.

(To answer the question in the issue: Yes, these packets are still idempotent - the definition of idempotency has to allow for the state of the world to change in a way that changes the result the action when attempted again.  For example. `GET /foo` is idempotent, but if there is a `DELETE /foo` that happens, the result of another `GET /foo` will be different.)

**Comment by marten-seemann** [comment]
I didn't say it's impossible, but it would add a lot of code for saving a tiny number of bytes, occasionally.
I don't think we should force implementations to perform an optimisation when the performance benefits are probably barely measurable at all.

**Comment by siyengar** [comment]
@marten the issue isn’t about saving bytes or an optimization. The issue is a peer being able to distinguish a correct  implementation from an incorrect one. Correct implementations might be very cognizant of this behavior and do it explicitly, however allowing this makes it much harder for a peer to give early feedback to peers that did this accidentally due to another bug

**Comment by siyengar** [comment]
Thanks for the pointer @martinthompson and the clarification about idempotence.

this would definitely apply to any limit frame

**Comment by kazuho** [comment]
@marten-seemann 
> I didn't say it's impossible, but it would add a lot of code for saving a tiny number of bytes, occasionally.

FWIW, my understanding is it's actually simple to implement the optimal way. What you would do is:
* transmit the maximum when `max(acked_max, inflight_max)` is below the threshold
* when receiving an ack for the max frame, update the `acked_max` and `inflight_max`
* when deeming a packet that contained the max frame as lost, reset `inflight_max` to `acked_max` if the number of max frames in flight is zero, otherwise you leave `inflight_max` as-is. Then, you check if transmission of the maximum is necessary by referring to the rule above

This strategy works well in QUIC v1, because packets are deemed lost in the order they are sent, and there is a guarantee in the logic that packets that are sent later contain a equal-to or greater maximum. The logic is not "perfect" when multipath is involved, though I would assume that it would work well enough in practice.

Regarding the issue, I am fine with allowing receivers to raise protocol error when they see the issue. I would oppose to making that a MUST though.

**Comment by kazuho** [comment]
> Regarding the issue, I am fine with allowing receivers to raise protocol error when they see the issue. I would oppose to making that a MUST though.

Let me retract my this comment. My understanding is that some existing QUIC implementations simply retransmit a packet (by re-encrypting it using a new PN) when it is deemed lost. I think that such implementations should be allowed to exist.

Considering that, I would oppose to even allowing implementations to raise a protocol error when they observe a smaller maximum value in a packet that has a greater PN.

**Comment by mikkelfj** [comment]
A protocol error would also go against the idempotency principle and unnecessarily tie frames to packet numbers. If there is implied ordering, the ordering should not originate from PN (possibly outside of handshake?).

**Comment by dtikhonov** [comment]
@siyengar writes:
> a receiver who wants to help peers prevent flow control bugs from happening

One could detect _potential_ bugs in the peer in many other cases.  I vote against mandating such error detection at the protocol level.

@kazuho writes:
> some existing QUIC implementations simply retransmit a packet (by re-encrypting it using a new PN) when it is deemed lost. I think that such implementations should be allowed to exist.

This is true. This is what the LiteSpeed implementation does with GQUIC's _WINDOW_UPDATE_ frames. The smaller values are [ignored](https://github.com/litespeedtech/lsquic-client/blob/04468d215dc184ae64e7aa1d0e940da50c724e2f/src/liblsquic/lsquic_stream.c#L1855). It is more expedient (and is cheaper) to discard lower values on receipt rather than update or remove the old values on retransmit.

Yes, let us exist!

**Comment by siyengar** [comment]
@kazuho I don't think we should make it a MUST on the receiver, just a MAY and maybe a MUST on the sender. 

@dtikhonov of course other bugs are possible, however this is a pretty major one if the sender actually tried to reduce the flow control. Without enforcement the MUST of "sender MUST not reduce the window" is almost impossible to enforce. Ignoring it will just kick the can down the road with such issues only getting discovered way after deployment vs at dev time. 

While I think it's fine to allow senders to copy over the packets that they have sent before, I don't think that should be a goal of QUIC. That is senders that are doing this should be aware of what they are signing for and take appropriate precautions. There are efficient ways to implement copying packets but updating max data. Preventing the efficient enforcement of a clear MUST would be very sad.

**Comment by dtikhonov** [comment]
@siyengar, where do you see "sender MUST not reduce the window?"  I cannot find it in the drafts.

**Comment by siyengar** [comment]
@dtikhonov sorry it's not those exact words, here's the exact wording: https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#flow-control

> A receiver MUST NOT renege on an advertisement; that is, once a receiver advertises an offset, it MUST NOT subsequently advertise a smaller offset. A sender could receive MAX_DATA or MAX_STREAM_DATA frames out of order; a sender MUST therefore ignore any flow control offset that does not move the window forward.

the operative words being "MUST NOT subsequently advertise a smaller offset"

**Comment by dtikhonov** [comment]
I see what you mean, @siyengar.  (Near-identical wording is used to describe _MAX_STREAM_ID_ behavior.)  If we keep the _MUST NOT renege_, then the receiver SHOULD check for this error.  As you pointed out above, it is easily done.

From the implementation perspective, it is quite doable as well.  These frame types are to be added to the list of frames to be deleted from a packet upon retransmission (e.g. _ACK_ frame).  Erasure of these frames would trigger generation of new _MAX_DATA_ (and friends) frames.

On the other hand, I like the simplicity of ignoring lower values -- but that's just my pragmatic side...

**Comment by dtikhonov** [comment]
@huitema, the reordering can be handled by keeping the packet number along with the maximum received value, as @siyengar [described above](https://github.com/quicwg/base-drafts/issues/1612#issuecomment-409084763).

**Comment by huitema** [comment]
Sure. But that's just additional complexity, and I don't think it is justified.

**Comment by mikkelfj** [comment]
@siyengar 

> @mikkelfj what do you mean by the ordering not coming from packet number?

I mean that the general principle of QUIC is for packets to vessels of frames that do not carry any semantic such as ordering, except for the connection context itself. I am not saying there is other ordering for MAX_DATA, only that when there is ordering, it should not, and generally does not, derive from packet numbers. For example, streams are ordered by stream offsets, and streams are ordered by stream ID's. Implying a problem because of ordering related to packet numbers is fundamentally against this design.

**Comment by mikkelfj** [comment]
If frames are seen as a stream, reordering can legally happen before packetization, for example when concurrent packet transmitters draws from a single frame stream. In this context, packet numbers cannot conlude anything.

On reneg of limits: there is a difference between a lower limit as lower bound, and in fact advertising a lower limit. The former ought to be valid, the latter would lead to all sorts of problems.

**Comment by siyengar** [comment]
@huitema Not sure I understand, do you mean verifying a MUST behavior is not justfied? In my reading of the clause, an implementation that checks for whether the peer is sending lower values is totally allowed in the current draft if it knows that the peer has sent this subsequently. This is because my reading of the MUST check. 

I think a receiver should be allowed to verify that this happens, it is just not required to do so, and we should also allow for implementations that don't verify this check. So if an implementation does send a frame pattern like this, it should be aware that it will not interoperate against some implementations. 

If we want to change this, then you might want propose a change, otherwise I think the current draft allows receivers to verify the MUST.

@mikkelfj was there any discussion about this? My understanding is that we have always implied that packet number == ordering. All the loss recovery mechanisms assume this. If this is not true we need to have a deeper conversation :) Also I don't agree with the analogy of frames as streams.

**Comment by marten-seemann** [comment]
> A receiver MUST NOT renege on an advertisement; that is, once a receiver advertises an offset, it MUST NOT subsequently advertise a smaller offset. A sender could receive MAX_DATA or MAX_STREAM_DATA frames out of order; a sender MUST therefore ignore any flow control offset that does not move the window forward.

This sentence is maximally confusing. You're not allowed to advertise a smaller offset, but then the peer is not allowed to check for this violation either. If I interpret this correctly,  Chrome, Litespeed and quic-go are violation the spec by implementing a slightly less than optimal retransmission strategy, and mvfst is violating the spec by performing a check of the flow control offset.
We should definitely make this wording clear, one way or the other.

I understand that optimisations are fun to implement, and once you've done it they seem trivial and obvious, but we shouldn't require an implementation to optimise anything. Retransmitting every packet as it is (just repacking it with a different packet number) is the most basic retransmission strategy that allows for a functional implementation of the protocol, and I think an implementation should be allowed to do this.

**Comment by MartinThompson** [comment]
I think you guys have tagged the wrong Martin Thompson. You should double check and re-tag the correct one.

Regards!
-martin

**Comment by dtikhonov** [comment]
@siyengar writes:
> I think a receiver should be allowed to verify that this happens, it is just not required to do so, and we should also allow for implementations that don't verify this check. So if an implementation does send a frame pattern like this, it should be aware that it will not interoperate against some implementations.

In practice, it will mean that all sender implementations will make sure not to send such frame pattern.  When I see that something _MAY result in an error_ (we have some other instances in the other QUIC drafts), it always strikes me as odd:  Surely, if something MAY result in an error, it forces the peer's hand; it is effectively a MUST.

**Comment by martinthomson** [comment]
Yes, we generally couple a *MAY result in an error* text with a MUST for the peer (because a MAY is always a MUST in the sense that it mandates tolerance).  In this case, we're saying MUST NOT go backwards, coupled with a MUST NOT generate an error if the peer doesn't comply.  That was explicitly to enable the sort of thing that @marten-seemann and @dtikhonov do, even if that is maybe slightly objectionable to the purists.

I think that the fix is as follows:

> A receiver cannot renege on an advertisement; that is, once a receiver advertises an offset, advertising a smaller offset has no effect. A sender MUST ignore any flow control offset that does not increase maximum (stream) data.

Would that work for people?

**Comment by huitema** [comment]
Works for me.

**Comment by siyengar** [comment]
While I'm not a huge fan of this change, it looks like I'm in the minority here, so it's fine with me.

**Comment by ekr** [comment]
I'm not sure @siyengar is in the minority here. This seems like a pretty
easy implementation error to make, and the check he proposes would allow
you to detect it in practice. It's not really clear to me what the
significant optimization is that relaxing this enables.

**Comment by ianswett** [comment]
I'm torn because I don't think retransmitting frames is right in this case, but on the other hand, I'm not sure increasing packet numbers always indicate one cannot send old frames.  With multipath, this problem may become intractable in practice, so I think the PR is an improvement.
