### ISSUE TITLE
Restrict delayed ACKs

### ISSUE THREAD

**Issue by mirjak** [quicwg/base-drafts#1662]
Currently the transport drafts says:
"Packets containing non-ACK frames MUST be acknowledged immediately or when a delayed ack timer expires."

However, I think the transport draft should set actually boundaries here and not rely on the delayed ack timer defined in another doc. RFC1122 for TCP e.g. says
"A TCP SHOULD implement a delayed ACK, but an ACK should not
be excessively delayed; in particular, the delay MUST be
less than 0.5 seconds, and in a stream of full-sized
segments there SHOULD be an ACK for at least every second
segment."

I guess we can now a days adapt the values a bit but should probably define similar boundaries in the transport draft.

**Comment by ianswett** [comment]
There's more text on this in the recovery draft, as well as related issue #1428 

Since there is a lot of interaction with recovery here, I'd rather keep as much text as possible in that draft.  I want to keep specific numbers like 0.5 seconds or 2 packets out of this draft, but if we need more text referencing recovery or some other descriptive text, feel free to suggest it.

**Comment by martinthomson** [comment]
This appears to be part of the cluster of issues related to ACK delays.  If someone has a concrete proposal for that, I would like to see that before the interim, so that we can resolve it there.

**Comment by mirjak** [comment]
@ianswett I would like to see that the transport draft sets the normative boundaries while the recovery draft specifies the specifics. This way both drafts are less dependent and could be easier revised in future separately.

@martinthomson I would put recommended numbers in the recovery draft but we can try to put lower and upper boundaries in the transport draft. I actually think something like "SHOULD at least send one ACK per RTT" would be good but that might be hard to implement. I think we can easily agree on an upper bound for the delay timer. I guess we can either go with 0.5 seconds as well or even something lower.

**Comment by ianswett** [comment]
I'm fine with one ack per RTT, since that seems like a sensible minimum.  If we say that, I don't see a need to say 0.5 seconds in transport.

**Comment by mirjak** [comment]
But that would mean you dynamically would need to set the time-out based on your RTT, e.g. kDelayedAckTimeout=min(smoothed_rtt,25)

Is that really what you want? It would make the ack delay at least less predictable for small RTTs...

**Comment by ianswett** [comment]
I think the goal for the transport doc is to define boundaries of reasonable behavior, correct?  If so, I no more than 1 ACK sent in response to a packet and at least 1 ACK per RTT are good boundaries.

I'd like the more detailed text to be in recovery, as I said above.  There are some open issues to improve that text, including the one I reference above.

**Comment by mirjak** [comment]
Yes, boundaries in transport, detailed text in recover. I just meant to say if the boundary is one ack per RTT, the detailed text in recover should say something like kDelayedAckTimeout=min(smoothed_rtt,25)

And I wanted to make sure that that is really what you want...?

**Comment by ianswett** [comment]
Thanks for clarifying.  I think there are potentially two numbers.  One is what the sender is assuming the receiver is using and the other is the value the receiver is using.  I think the receiver should use the value you suggest above with a min(), but I don't think the sender should assume that, since one may have a substantially different value for SRTT than the other.

I'm due to write a fair bit of text in the recovery doc about ACK behavior, so I'm happy to keep this issue open until that text includes mention of this "at least one ack per RTT behavior" and what the sender should and should not assume?

**Comment by mirjak** [comment]
right, I think you only need to say that the sender should assume that to be a max. I guess there is anyway no problem is the ACK is sent faster...

**Comment by ianswett** [comment]
If that's what you wanted, you would need that, but if the connection isn't receiving any packets, not sending acks is the right thing, so I think the new clause in the PR: "if new packets needing acknowledgement were received." covers that?

**Comment by mirjak** [comment]
Yes, if you don't receive anything that is fine. However, just using the delayed ack timer would not fulfill the requirement of one ACK per RTT. Assume a scenario where you send packets and you ack the last packet and then send nothing for about one RTT and then send one more packet. In that scenario you should ack immediately because you didn't send an ACK in the last RTT and should not wait for the delayed ack timer to expire.
