### ISSUE TITLE
Target of HTTP version fallback

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#1677]
We added the version fallback error code to HTTP/2 because there were certain HTTP/1.1 scenarios which were difficult or impossible to support over the multiplexed transport for various reasons.  (Resources which returned raw formatted headers, WebSockets, chunk extensions, client certificates, etc.)

Are there things which aren't supported in HTTP/QUIC which *are* supported in HTTP/2, such that the fallback should be to HTTP/2?  Or should our fallback go straight to HTTP/1.1, since the things you can't do in HTTP/QUIC you probably also can't do in HTTP/2?

**Comment by mikkelfj** [comment]
At least the number of applications that are so tightly coupled with HTTP/2 today as to be a concern is probably very limited. The fact that there are (are could be) things that you could theoretically do in HTTP/2 but not in QUIC does not necessarily mean that you should. That is, unless there is a smoking gun in form of an important real world use case.

Otherwise, I'd say that having to support both HTTP/2 and HTTP/QUIC is just more complexity than it is worthwhile.

If it were like HTTP/2 had replaced the world, it would be different, but HTTP/1.1 is likely to outlive both HTTP/2 and QUIC v1.

**Comment by RyanAtGoogle** [comment]
What fallback are we referring to here? With HTTP over QUIC it is Alt-Svc which is used to discover QUIC servers. If QUIC is not working for that server, I would expect a User-Agent to mark that alternative as broken and fall back to using the origin directly. I would expect the User-Agent to use the "normal" logic for connecting to that origin. In that case of HTTPS, that would involve ALPN negotiation of HTTP/2 or HTTP/1.1. 

Do we need any more logic beyond this?

**Comment by MikeBishop** [comment]
For HTTP/2, we used it when the resource did something that couldn’t be expressed in HTTP/2, either because of the protocol or because of our implementation:

  *   Client certificates couldn’t be used because HTTP/2 prohibits renegotiation (Secondary Certificates will fix that, eventually)
  *   Multi-leg auth protocols can’t be used because HTTP/2 doesn’t maintain links between multiple attempts on a request (there was a draft on how to fix that, but it was never adopted)
  *   Our implementation permitted resources to return raw-formatted headers, which obviously doesn’t play nicely with HPACK.  Thankfully, that was rarely exercised.

It’s not a failure to connect, but an indication that the request you made can’t be answered over HTTP/2 for some reason.  Most of those reasons apply equally to HTTP/QUIC.

**Comment by RyanAtGoogle** [comment]
Oh! You're talking about HTTP_1_1_REQUIRED? I see. Makes sense, I think...
