### ISSUE TITLE
DATA frame encoding is inefficient for long dynamically generated bodies

### ISSUE THREAD

**Issue by RyanAtGoogle** [quicwg/base-drafts#1885]
In the common case of a long response body that is dynamically generated, it is not possible to know the full length up front. Instead, the body is often read in chucks from some backend/data source and written to the wire as it's available. Since response bodies need to be encoded in DATA frames with an explicit length this typically means splitting the body into numerous chunks. Instead if would be more efficient if we could set a length of "until end of stream" (encoded as 0 or some such) which would allow the sender to write a single DATA frame header and the simply send the entire body without additional framing.

HTTP/2 explicitly tries to avoid overly long frames. This is a feature for HTTP/2 in which the frames for multiple streams are sent on the same in-order sequence of bytes, so a long frame potentially introduces head of line blocking for other higher priority data. But for QUIC there is no such concern since these DATA frames are all within the same stream.

**Comment by LPardue** [comment]
I'm sympathetic to the issue but not sure it needs fixing in v1. What is worse case overhead?

The proposal seems similar to some aspect of Roberto and Jeff's ideas. A slightly different type of stream could carry just a response, and permit simple random access of bytes across the entire stream.

**Comment by dtikhonov** [comment]
> Instead if would be more efficient if we could set a length of "until end of stream" (encoded as 0 or some such) which would allow the sender to write a single DATA frame header and the simply send the entire body without additional framing.

Yes, this would be nice.

**Comment by ianswett** [comment]
I previously missed this potential issue, but I think it's worth fixing, because for cases like large content delivery(ie: video streaming, etc), this minimizes overhead, complexity, and makes it easy to provide a zero-copy API on both the send and receive sides.

Also, 0 length is currently disallowed in DATA, so we have a value available in the existing frame we can define as something useful if we'd like.

I expect if this was supported, >90% of HTTP DATA frames would use it, which speaks to the prevalence of this use cause.  Having to specify a length is in many ways a special case, and the typical case is "the rest of the QUIC stream is DATA".  The only two cases I can think of where that wouldn't be true are server push, which is rarely used, and trailers, which are rarely supported and even more rarely used.

**Comment by martinthomson** [comment]
New feature!  Be prepared to take this to Bangkok and have it resolved there.  I think that we're close to saying "no" to these automatically.

**Comment by ianswett** [comment]
To clarify, this is a minor change to an existing frame.

Also, not many people have implementation experience with the HTTP mapping, so we're going to hit some small issues like this as implementers catch up.

**Comment by martinthomson** [comment]
I disagree.  It's a new capability.  I'm not saying that asking for a new capability is out of bounds, just warning you that the door is about to close.

**Comment by kazuho** [comment]
@RyanAtGoogle 
> Instead if would be more efficient if we could set a length of "until end of stream" (encoded as 0 or some such) which would allow the sender to write a single DATA frame header and the simply send the entire body without additional framing.

Doesn't having a "end of stream" signal as part of the frame payload mean that we would need to escape the contents of HTTP if it contains the octets that can be interpreted as the "end of stream" signal?

Assuming that my understanding is correct, this sounds like MIME multipart. I prefer current chunked encoding style above that, because you do not need to scan through the content that you'd be forwarding.

Or am I missing something?

**Comment by RyanAtGoogle** [comment]
@kazuho the end of stream signal is the QUIC transport-level FIN. Thankfully, it does not need to be encoded at the HTTP layer. I think it's more like HTTP/1.1 "Connection: close" than MIME multipart.

**Comment by kazuho** [comment]
@RyanAtGoogle I see. Thank you for the clarification.

So the premise for using the proposed method is that trailers are not going to be sent.

**Comment by LPardue** [comment]
To generalise Ian's observation. This greedy DATA frame would prevent onward use of frame types on a stream. Not only the core frames like HEADERS and PUSH_PROMISE but also extension frames such as ALTSVC. 

I think server push is actually ok here because a server would probably want to send promises before the response body (to a avoid a race condition).

**Comment by dtikhonov** [comment]
@LPardue writes:

> I'm sympathetic to the issue but not sure it needs fixing in v1. What is worse case overhead?

When one transfers large files, the overhead incurred by the DATA frames will be on the order of 3 bytes for every `[ ~1 MSS, 2^14 - 1 ]` bytes of content, or between about 0.2% and 0.02%.

@ianswett writes:

> The only two cases I can think of where that wouldn't be true are server push, which is rarely used, and trailers, which are rarely supported and even more rarely used.

The server push will continue to be rarely used if the API makes its use inconvenient.  For example, one can imagine that a server may want to push after sending a few KB of data (a finite DATA frame) -- to parse the HTML for CSS links or what-not.  An implementation that only allows pushes before the first (and only) DATA frame will make using server push in such manner more difficult.  Because it is easier to support only a single DATA frame of indeterminate size, it is likely that many implementations will do just that.

The complexity associated with framing data into DATA frames is real (if you want to do it efficiently), but not insurmountable.

**Comment by LPardue** [comment]
Thanks for saving me the effort of calculating that Dmitri. Given that this bit of HQ mirrors H2 the overhead is neutral in that perspective. I'm of the same opinion as Martin that this is a "new feature" that offers up to 0.2% bandwidth saving. What is the bar for new features.

(New because this it changes the semantics in comparison to H2).

**Comment by MikeBishop** [comment]
I'm sympathetic to the desire to reduce framing overhead, and having previously described the frames as "regions," I'm not philosophically opposed to having a region run to the end of the stream.  However, we've built / inherited from H2 a model in which frames have a known length from the start (though some might be so large that you have to process them in a streaming fashion).  I'm cautious about up-ending that model and saying that some frames have indeterminate length, and you'll know the end when you get there.

Depending on your implementation model, that might be fine.  If you have a processor that gets fed the bytes until the end of the frame, then it already handles a stream and being told that the payload has ended after/as the last byte is written to it.  This is a scoped change to the layer that reads the bytes from the stream and stuffs them into the processor.  If you have a processor that gets told the length and consumes that many bytes from the stream, this might be more of an architectural change.

I'm curious to hear from implementers how much of a challenge they foresee this being in their architectures.

**Comment by MikeBishop** [comment]
Also, rather than making DATA "special," I'd probably just add text to the framing layer section that a length of zero means the frame extends to the end of the QUIC stream.

**Comment by mikkelfj** [comment]
Initially did not see much point in this, but if you are parsing text and generating output, it it is hard to decide on any reasonable chunk size as you discover the output as you go. You'd have to buffer data until you hae enough to create a frame. Being able to avoid that has value beyond saving 0.2%.

**Comment by dtikhonov** [comment]
> You'd have to buffer data until you have enough to create a frame. Being able to avoid that has value beyond saving 0.2%.

Yes, there is certainly complexity associated with writing out streaming data. Nevertheless, one should not *have to* buffer.

**Comment by LPardue** [comment]
gQUIC also has a different way of achieving HTTP header transfer, which means it had HoL blocking :)

Things are just different in HQ, it's a chance do you wind some of the compromises that QUIC made. As an implementor I'd like to have an environment that creates new opportunity, just as much as performance.

The direction of conversation is positive, and I agree performance isn't just shaving bandwidth. Mike's idea creates a general approach that I like.

**Comment by dtikhonov** [comment]
One concern I have about adding the greedy DATA frame is that it may very well mean that no implementation will actually generate sized DATA frames:

> Because it is easier to support only a single DATA frame of indeterminate size, it is likely that many implementations will do just that.

Which, in turn, will mean that a large chunk of everyone's HQ code that reads DATA frames with sizes will go  unutilized.  The atrophy and death of a sized DATA frame -- perhaps in the next version of QUIC -- is the next logical step.

**Comment by kazuho** [comment]
@dtikhonov As a developer of a HQ proxy capable of forwarding trailers, I can say that H2O/quicly will generate sized DATA frames.

**Comment by RyanAtGoogle** [comment]
@MikeBishop Oh! I love the idea of generalizing this to all frames, not just data. This would be quite convenient for body-less requests/responses.

**Comment by kazuho** [comment]
@MikeBishop 
> I'm curious to hear from implementers how much of a challenge they foresee this being in their architectures.

In case of H2O/quicly, it is almost nothing to support DATA frames expanding to EOS.

However, it is harder to do the same for other types of frames. The code is based on the assumption that we can cap the maximum size of the frames, and buffer them until they are fully received.

**Comment by LPardue** [comment]
@RyanAtGoogle I had a similar thought but initially worried that EOS would kill the bidirectional stream too early. However I think I was wrong, because stream is closed from either direction.

**Comment by RyanAtGoogle** [comment]
@kazuho how would this proposal prevent an implementation from capping the maximum size of a frame?

**Comment by MikeBishop** [comment]
@kazuho, for most of them, that's still true.  About half of frames have well-defined maximum sizes -- if you haven't hit EOS before that point, the frame is improperly formatted.  The frames whose payload is bounded only by the frame length field are DATA, HEADERS, PUSH_PROMISE, and (technically) SETTINGS.

**Comment by LPardue** [comment]
Consider also extension frames like ORIGIN or CACHE_DIGEST (yes they don't exist, yes) that might be sent in the HQ control stream, those can't be EOS'd.

**Comment by kazuho** [comment]
@RyanAtGoogle
> how would this proposal prevent an implementation from capping the maximum size of a frame?

It doesn't. However, introducing the concept of non-DATA frames terminated by EOS has a impact on complexity. We handle HQ frames in the following way:
* We keep the frame header in the receive buffer until all the header is delivered. Then,
* if it is a DATA frame, we pop the frame header from the receive buffer, and continue reading the data out from the receive buffer until we read the exact amount of data specified by the frame header
* if it is not a DATA frame, we check that the size of the frame is below 16KB. If it is above that, we issue a connection close. If it is below that, we keep the octets in the receive buffer until the entire frame arrives. Once the frame arrives, we process it in-place, then remove it from the receive buffer.

Having non-DATA frames terminated by EOS means that we need add a different path for the last bullet. I'm sure I can implement that, but my preference goes to avoiding it.

I can understand the motivation to use EOS as a terminator for DATA frames. It makes sense because you might emit a large number of DATA frames for each HTTP response, and because DATA is typically the last frame type to be sent using a stream. Neither of the two points apply to other frame types, which means that the optimization is far less useful for them, even though I understand the elegance of permitting that for all frame types.

**Comment by dtikhonov** [comment]
In our QPACK implementation, [ls-qpack](https://github.com/litespeedtech/ls-qpack), the decoder consumes header block as a stream.  Hence, having a header block of an unspecified size is no problem -- there is no buffering either way.

For QPACK encoder, it is a profitable optimization to be able to write some header blocks directly to the stream.  I share @RyanAtGoogle's emotions in this regard.

@kazuho writes:
> Having non-DATA frames terminated by EOS means that we need add a different path for the last bullet. I'm sure I can implement that, but my preference goes to avoiding it.

Isn't this as simple as foregoing the initial size check and closing the connection if you do hit the internal limit?  Certainly, if you're willing to buffer 16KB - 1 bytes to process a frame, you should be willing to buffer 16KB -1 bytes and then throw them out and close the connection.

**Comment by dtikhonov** [comment]
@kazuho writes:
> As a developer of a HQ proxy capable of forwarding trailers, I can say that H2O/quicly will generate sized DATA frames.

What about larger players such as Google?  For example, because not many server implementations support server push and not many websites use it (and even fewer do it well), Google [floated the idea](https://github.com/httpwg/wg-materials/blob/gh-pages/ietf102/chrome_push.pdf) to "destroy" it.

**Comment by kazuho** [comment]
@dtikhonov 
> Isn't this as simple as foregoing the initial size check and closing the connection if you do hit the internal limit?

You also need to handle EOS differently. In the bounded frame case, seeing EOS before consuming the entire frame is a protocol error. In the non-bounded case, seeing it is a non-error.

To generalize, allowing the use of EOS as a terminator for non-DATA frames introduces new complexity to *some* decoders. OTOH, allowing that does not simplify on the encoder side, because you need the code to emit such frames in the middle of the stream.

This is very different from DATA frames:
* For many HQ stacks, DATA would be the last frame to be emitted on a stream. Therefore, you can get rid of the code that emits bounded DATA frames if we introduce the use of EOS as a terminator.
* It does not make the decoder complex, because in practice no decoder will block until it receives an entire DATA frame.
* DATA will be the most frequently used frame (compared to nothing else). Therefore, it is beneficial to reduce the number of the frames (by allowing use of EOS as the terminator).

**Comment by kazuho** [comment]
@dtikhonov 
>> As a developer of a HQ proxy capable of forwarding trailers, I can say that H2O/quicly will generate sized DATA frames.
> 
> What about larger players such as Google?

I hope that the developers will notice interoperability with the websites hosted by Fastly before shipping stacks with broken trailer handling :-)

**Comment by ianswett** [comment]
Curious: What do you use trailers for?

Clearly our code will end up having to support specified lengths due to interop and the small number of cases(push and trailers included) that we support.

**Comment by kazuho** [comment]
@ianswett H2O is capable of sending server-timing headers as trailers.

However, regardless of the use case, any proxy (including edge servers) that can forward trailers need to use length-delimited DATA frames when forwarding a chunked response, because it cannot tell whether trailers exist until receiving all the response body.

> Clearly our code will end up having to support specified lengths due to interop and the small number of cases(push and trailers included) that we support.

Agreed. This discussion is not about simplifying the decoder. It's about simplifying the encoder used by certain endpoints (as well as reducing the network overhead in a small degree).

**Comment by LPardue** [comment]
This is a good observation. There is some industry attention being paid to chunking end-to-end through the delivery chain.

Perhaps there's scope for an extension to HQ and/or H2 that can explicitly declare no trailers on a stream, wresting performance on the endcode or pass through cases.

**Comment by kazuho** [comment]
@LPardue 
> There is some industry attention being paid to chunking end-to-end through the delivery chain.

I understand the same way.

> Perhaps there's scope for an extension to HQ and/or H2 that can explicitly declare no trailers on a stream, wresting performance on the endcode or pass through cases.

I am not sure if I like the complexity, partly because of the small performance gain we will see (see @dtikhonov' comment at https://github.com/quicwg/base-drafts/issues/1885#issuecomment-431348155), and also because it could be hard to use; it is often the case that a proxy cannot guess at the time of connection establishment to which origin server it would be connecting (consider the use of secondary server certificates).

Actually, my preference might go to addressing the issue in QUIC v2 (or as an extension to v1). For example, we could move the chunking layer into the transport by adding a END_OF_BLOCK flag to a STREAM frame for indicating the end of each block within a STREAM. Assuming that many of the application protocols will transfer size-delimited blocks (e.g. HQ frames), it makes sense to support the concept in transport.

Having it expressed as a flag of a STREAM frame (by burning the frame type octet) will give us simplicity _and_ efficiency in terms of bandwidth, because we can totally eliminate the Length field of the HQ frames.

**Comment by MikeBishop** [comment]
Technically, don't you have to declare in your header whether there will be trailers and what they will be?  So that is actually known if you're parsing the HTTP semantic layer.  However, this layer of the mapping doesn't attempt to encode it.

@martinthomson, that's another way to do it, but it makes me very nervous to say that we can't tell the difference between intent and a bug.  Seems like a door to a security risk or at least potential consistency concerns.  Consider a proxy whose back-end connection is interrupted and closes the stream before the entire payload has been transferred -- that error gets propagated and looks like a normal, intended response under those rules.

(Of course, if the proxy wrote a zero length and then had that happen, the same issue would exist.)

**Comment by mikkelfj** [comment]
Certainly taking the minimum of stream and frame seems like an invitation to problems.
Predeclaring trailers is inconvenient if you don't know that ahead of time. Separate stream, v2?

I (kind of) like what @kazuho wrote about blocks/boundaries within a stream in v2, but this is a large topic that digs into partial reliability. I'm not sure boundaries on their own are that useful because a flag in a stream header still require a stream frame while an application embedding its own framing can be more dense, depending on the frame size vs. packet size. I did make such a proposal a boundary proposal a long time ago (out of scope for v1).

**Comment by MikeBishop** [comment]
@mikkelfj, yes.  That was the design adopted first by GQUIC then (in a different incarnation) in early versions of the HQ draft.  There needs to be a guaranteed ordering between parts of the response and PUSH_PROMISE frames, and QUIC only provides guaranteed ordering on the same stream.

**Comment by kazuho** [comment]
@MikeBishop 
> Technically, don't you have to declare in your header whether there will be trailers and what they will be? So that is actually known if you're parsing the HTTP semantic layer. However, this layer of the mapping doesn't attempt to encode it.

The use of `Trailers` header field is merely a recommendation (i.e. `SHOULD`). And as you point out, there is no signal at the encoding layer. So from an intermediary's perspective, IMO it's just more natural to forward the trailers as they are, regardless of what the value of (or the existence of) the Trailers header is. Though I agree that dropping trailers in case of the absence of the `Trailers` header field will not cause interoperability in practice.

**Comment by kazuho** [comment]
@mikkelfj 
> I (kind of) like what @kazuho wrote about blocks/boundaries within a stream in v2, but this is a large topic that digs into partial reliability. I'm not sure boundaries on their own are that useful because a flag in a stream header still require a stream frame while an application embedding its own framing can be more dense, depending on the frame size vs. packet size.

Well, it's a matter of how you encode it. We can for example define the encoding of STREAM frame as a series of blocks. That way, we can eliminate having needless metadata (i.e. stream ID, offset) for each block.

> I did make such a proposal a boundary proposal a long time ago (out of scope for v1).

Yeah. While I think that is the ideal thing to do, I do not want to revisit the discussion now. My intention is to use it as a counter-approach to express my impression that occasionally using EOS as a terminator of DATA frame is kind of a band-aid solution. Admittedly, this is a nice-looking band aid. But it is not ideal, and I'd prefer either applying it minimally or deferring it to v2 to fix the issue in the ideal way.

**Comment by MikeBishop** [comment]
PR reverted; reopened for discussion in Tokyo.

**Comment by ianswett** [comment]
Reopening because this was merged and then reverted without a proper resolution.

**Comment by MikeBishop** [comment]
Discussed in Tokyo; this is viewed as an important optimization.  There are ways to solve this by modifying the HTTP/3 framing layer, but it has challenges, notably for proxies.  This can be solved by extensions (EXTERNAL_DATA, END_OF_FRAMES).  We should do so to learn more.

However, the "optimal" solution might be a QUIC stream-of-messages feature in the future, which is already being discussed.

**Comment by MikeBishop** [comment]
Yes, ignored; they were valid in HTTP/2 as well.  They append zero bytes to the output, which means no net effect.
