### ISSUE TITLE
Loss events for reordered 0- and 0.5-RTT data

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1967]
In the event that 0-or 0.5-RTT data arrives before the cryptographic handshake packets that would normally precede it.  That is, the Initial containing ClientHello might arrive after a few 0-RTT packets, or the 0.5-RTT packets might arrive before the server flight is completely received.

In that case, those packets will be declared lost.  That's fine from a loss-recovery perspective.  However, the congestion controller will treat this as a loss event.  We want to ensure that loss events are driven only by congestion.

Perhaps the congestion controller shouldn't trigger a loss event on packets that might be dropped in this way.  If we do this, we need to be careful about definition.

**Comment by siyengar** [comment]
This also applies to one rtt data as well sent in the client first flight. If one rtt arrives before cfin, then the read key cannot be used by the server yet, and it might drop or buffer a few of these packets. This could appear as a loss to the client. We got bit by this a few months ago.

**Comment by ianswett** [comment]
We need to clarify this, but it's going to be a challenge to write clear text about these issues.  I'll send out a PR that tries to do so anyway.

**Comment by janaiyengar** [comment]
This is a slightly involved fix.  We basically need to distinguish packets whose drops do not necessarily indicate congestion vs those that do.  As I see it, the packets whose drop does not necessarily indicate congestion are:
1. any handshake packet
2. any 0-RTT data (sent by client)
3. any 0.5-RTT data (sent by server)
4. data received before CFIN, which from the client's point of view is all data sent until ack for CFIN is received (thanks @siyengar for noting this).

1, 2, 3 are ok, but 4 is tricky, since congestive losses in the first RTT are indicators of a large initial window. I'm inclined to leave 4 out conservatively, since it delays the engagement of the CC machinery by a fair bit.

**Comment by marten-seemann** [comment]
Handshake packets would never be undecryptable for the server, only for the client.
