### ISSUE TITLE
Exempt all ACK frames from congestion control

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#1977]
I realize there are quite a few retired PRs in this space.

However, the current system sets up perverse incentives. If I want to maximize my throughput given a certain congestion window, the optimal behavior is to always send ACK frames in their own packets.

IMO, simply not counting ACK frames in flightsize (and the header of ack-only packets) is conceptually cleaner and a pretty simple change to the implementation.

If there are no objections I can file a PR.

**Comment by marten-seemann** [comment]
If you want to send more data than your congestion window allows, nobody can stop you from doing so.

**Comment by siyengar** [comment]
I agree with @marten-seemann here, we're solving for a sender that wants to do the right thing and be nice to the network. If I understand this proposal, you're suggesting not counting ack frames towards size even in the packets that contain them?

**Comment by ianswett** [comment]
Agreed, I'm happy with the status quo.  If you want to game congestion control, there are plenty of ways to be unilaterally more aggressive.

The reason ACK-only packets are the only ones that aren't congestion controlled is to allow sending ACKs even if there's no available congestion control or you'd otherwise be pacing limited.  And the main reason they don't count towards bytes in flight is because they don't elicit an ACK to allow them to be removed from bytes in flight.

**Comment by marten-seemann** [comment]
If I remember correctly, we had a lengthy discussion of @martinduke's proposal at one of the early interims. The conclusion was to count ACKs for congestion control, because QUIC ACK frames can become quite large, and therefore should be considered as load on the network. The exception for ACK-only packets is unfortunate, but the only way to not end up in an acknowledgement loop.

**Comment by janaiyengar** [comment]
Fair enough. I chatted with @martinduke and thought it was a fine proposal (I think it still is). But I agree with @marten-seemann that it leaves large ACKs out, which is unfortunate.

**Comment by martinduke** [comment]
To answer @marten-seemann 's first point, I do think that the congestion control rules in the spec matter, even though they're unenforceable. Implementers will sometimes do whatever the spec lets them get away with. The reason I brought it up was the fairly stupid "never send an ACK with data" loophole.

Regardless, this is clearly DOA and I'm closing it.
