### ISSUE TITLE
Reserve Long Header Packet Type for QUIC-LB

### ISSUE THREAD

**Issue by nibanks** [quicwg/base-drafts#1980]
This issue is directly related to @martinthomson forthcoming changes to the first octet.

The [QUIC-LB](https://github.com/martinduke/draft-duke-quic-load-balancers/blob/master/draft-duke-quic-load-balancers.md) doc uses the QUIC packet framing to communicate between the load balancer and backend servers, because it is the easiest way for the backend server to have built in support. It already has to handle QUIC packets obviously. In order to differentiate QUIC-LB traffic from normal connection flows, QUIC-LB [defines a new QUIC packet type](https://github.com/martinduke/draft-duke-quic-load-balancers/blob/master/draft-duke-quic-load-balancers.md).

If the first octet is changed to only allow for the currently defined packet types in the transport spec, this will cause problems for QUIC-LB. So, we'd like to reserve 1 packet type in the transport spec.

**Comment by kazuho** [comment]
Can’t you use a different version number instead?

**Comment by nibanks** [comment]
The goal was to match the QUIC-LB version with the transport version.

**Comment by kazuho** [comment]
Yeah. While that sounds like a logical point of view from QUIC-LB's perspective, I wonder if it is possible to have such a property guaranteed, because IMO it sounds like requesting an invariant for (at this moment) an individual draft.

**Comment by nibanks** [comment]
We're not asking for an invariant. The reserved packet type in each version of QUIC-LB could be different.

**Comment by siyengar** [comment]
I've spoken about this offline with @martinduke. I think that using a QUIC packet for this is not necessary at all and might be detrimental in some cases. For example, there is a circular dependency to talk to a particular server to assign it a connid when it doesn't currently have a connid assigned to it. 

I think this will open up a can of worms though. When we add a packet type for a lb packet, we might want to add a packet type for a health check packet, etc. and other use cases which adds up to several bits.

**Comment by kazuho** [comment]
@nibanks 
> We're not asking for an invariant. The reserved packet type in each version of QUIC-LB could be different.

Yeah. My point is that requiring each QUIC version to follow a particular design constraint (in this case reserve a code point) is what Invariants is.

As pointed out in 
https://github.com/quicwg/base-drafts/issues/1980#issuecomment-436731614, the Invariants draft provides you a way to coalesce other types packets; that is to use a private version number. Would you mind elaborating why you think it's illogical for QUIC-LB to use that mechanism?

**Comment by nibanks** [comment]
@kazuho the QUIC-LB packet would be no more invariant than the Initial long header packet. I don't see how you could call it invariant. Perhaps in V2, we do something different, maybe just a different value, maybe removed all together, maybe request more packet types. But bottom line, we are requesting 1 QUIC v1 packet type right now. Nothing invariant.

**Comment by marten-seemann** [comment]
I don't like the idea of using an additional packet type, especially since the current mapping has the nice property that we're actually using all 4 encodable packet types.
Using a new packet type, which is not an invariant, has the additional unpleasant property that you'll potentially have update QUIC-LB every time we're releasing a new QUIC version.

**Comment by nibanks** [comment]
Having the QUIC-LB be a versioned interface is a pro in my mind, not a con. We would only updated version numbers if necessary, but having the ability to do so is a good thing.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by martinduke** [comment]
While I agree with @nibanks that an additional codepoint would be desirable, if the WG likes it better QUIC-LB might simply use the RETRY codepoint. It will likely be straightforward to disambiguate this, if we take a little care.

**Comment by martinthomson** [comment]
I think that we probably want to have a deeper conversation about this draft.  I look at it and ask why you need to create a bespoke protocol here at all.  If it is going to look like QUIC proper, why not make it be QUIC proper?

But even assuming that you do need that, why are you concerned about making this look like QUIC proper?  I can't see why you would need that for routing purposes, because it seems like you should be back to 5-tuples for routing on this bit.  I can't see why you would concern yourself with ossification on a link that you presumably have considerable influence over.  I can see why you might want to disambiguate this connection from "real" connections, but you could use a separate port, ALPN, or even a new QUIC version if it came to that (though I would advise against a version).

On response to @marten-seemann's comment, which I agree with, you might also like to consider the effect of having 5 types in the long header and what that does for protocol ossification.

**Comment by janaiyengar** [comment]
Reserving a codepoint would be putting the horse before the cart. Let's
first get the QUIC-LB draft to a point where it is a wg activity, then
discuss the designs in there, and agree on a need for a packet-type in the
wg. I don't think it makes sense to reserve a codepoint before we've agreed
on the mechanisms in the draft first.

**Comment by kazuho** [comment]
As previously stated, QUIC already has an extension point, which is the version number field of a long header packet.

Any protocol including QUIC-LB can define it's own 4 octets to distinguish itself from other traffic.

For example, QUIC-LB can declare it self to use 0x1b000000 to identify itself. Then, if you need to have a version number field within QUIC-LB, you can create your own LB version field in the payload area.

I do not think we need any other extension mechanism, for QUIC LB or whatever.

**Comment by nibanks** [comment]
@kazuho I agree that is another solution. I would prefer that over repurposing the RETRY packet type. It would possibly add some complexity on how VN should work. Should servers advertise support of that version? If so, should QUIC-LB 'sanitize' it when sent out over the open internet?

**Comment by kazuho** [comment]
@nibanks 
> It would possibly add some complexity on how VN should work. Should servers advertise support of that version? If so, should QUIC-LB 'sanitize' it when sent out over the open internet?

IIUC the QUIC-LB protocol (or whatever we call it) is not a variant of QUIC. It's a completely different protocol that happen to have the need to be demuxed from ordinary QUIC protocol.

Assuming that is true, I think you do not need to include it in VN. All you need is to use it for demuxing.

**Comment by ianswett** [comment]
I'd prefer to reserve a version for QUIC-LB instead of changing the core QUIC transport or abusing RETRY.

**Comment by martinduke** [comment]
The objective we are trying to meet here is to support cases where the load balancer to server path is not trusted. To do this, we believe we need to pass through middleboxes that are dropping things that don't like QUIC.

At the same time, we are reluctant to make load balancers support a full implementation of QUIC.

I am fairly agnostic as to the solution as long as it looks "enough" like QUIC without requiring a full implementation. When there were more available codepoints, it was simple enough to just take 0xfb. I see the ossification problems with going to 8 codepoints instead of 4.

Whatever the design team comes up with will have to get ratified by the WG anyway. If the least objectionable choice is a different version, we can proceed with that.

**Comment by mikkelfj** [comment]
A subset of QUIC sounds like a new version with implicit ties to an existing version. LB could take advantage of version negotiation and get encryption, handshake, and version stability without going full QUIC and without inventing its own protocol.

**Comment by janaiyengar** [comment]
@nibanks -- it's still cart before the horse. You want people to discuss the mechanisms in QUIC LB first (which is now happening a bit on this thread) before reserving a codepoint for one particular design.

FWIW, I am with @kazuho and @ianswett -- let's use the Version field for demuxing.

**Comment by mikkelfj** [comment]
With VN an LB should detect a requested LB version and only offer LB versions in response. It should not offer LB versions normally. It would probably also filter on IP range and use a different port when possible.

**Comment by nibanks** [comment]
Thanks folks for all the input. I think we can work reasonably well with a different version number.

**Comment by mikkelfj** [comment]
Note that LB to backend encryption is of interest to this protocol: Some cloud providers offer a fast internal network but the network is not invisible to other customers and at the very least injection attacks are a concern. For this reason a basic QUIC handshake does make sense. If cloud providers can agree on a standard protocol it would be simpler to deploy cloud services in a generic fashion.

I kind of hope something similar could be made for updating name servers.
