### ISSUE TITLE
Include the QUIC version in the transport key labels

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1997]
@adl suggests in #1991: "it could make sense to also include the QUIC version in the transport key labels"

A simple hack would be to (ab)use the unused `context` field, and include the 4 octet version.

**Comment by kazuho** [comment]
+1 to adding QUIC version.

(Ab)using the `context` field sounds attractive, though I would prefer having text in the label specify the version, partly because it is what TLS 1.3 does (i.e. `tls13 ` prefix), and partly because we might want to use the `context` in a version-specific way in the future.

**Comment by martinthomson** [comment]
Addressed by the extra text added to #1991.
