### ISSUE TITLE
Do streams 0 and 1 count towards MSPC?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#201]
And if so in which directions?

**Comment by marten-seemann** [comment]
I don't think there's a stream 0 (however, I find the wording in the [Stream Identifiers section](https://github.com/quicwg/base-drafts/blob/master/draft-ietf-quic-transport.md#stream-identifiers-stream-identifiers) a bit confusing, since the 0 that is used as a stream ID in a WINDOW_UPDATE frame for connection-level flow control is just a placeholder).

Since stream 1 is always initiated by the client (it's an odd stream ID), there's no ambiguity towards which MSPC it counts.

**Comment by ekr** [comment]
It's ambiguous whether stream 1 counts against the client's allocation

**Comment by martinthomson** [comment]
There isn't a concrete stream 0, but clearly stream 1 is an issue.

I agree that this is not clear, we probably need to pick an answer.  Note that the HTTP mapping requires a minimum of 3 streams in addition to the crypto stream.  This plays into #186.

**Comment by martinthomson** [comment]
Discussed in Tokyo, editors will decide this, but write it down.
