### ISSUE TITLE
OnPacketsLost for Nonretransmittable Packets

### ISSUE THREAD

**Issue by nibanks** [quicwg/base-drafts#2015]
Why isn't `OnPacketsLost` called for nonretransmittable packets? Just because you don't retransmit the information contained in the packet, doesn't mean it's loss wasn't an indication of a congestion event, right? If you send an ACK only packet, then three data packets after it, and you then get an ACK for just the data packets, shouldn't you consider there have been a congestion event?

**Comment by nibanks** [comment]
But I'm arguing that determining if there was a congestion event should be independent of how many retransmittable bytes the packet contains. It would be trivial enough to update the pseudo code.

**Comment by mikkelfj** [comment]
At least you'd have to update OnPacketSent as well. But if you count nonretransmittable packets and there is no retransmittable packet in front, you might miscalculate the available bandwidth because you do not get timely feedback.

**Comment by nibanks** [comment]
Yes, a few places would have to be updated, but it's really just moving the `if (unacked.retransmittable):` line into the `OnPacketsLost` function, only subtracting the bytes in flight if retransmittable.

**Comment by ianswett** [comment]
This was chosen as an effort to be similar to TCP, which does not consider loss of ACK-only packets as a congestion event.  

As @mikkelfj pointed out, ACK-only packets don't count towards bytes in flight, so it seems odd to me to consider the loss of them a congestion event.

I can imagine changing this, but if in doubt, I think adhering closely to what TCP does makes sense.

**Comment by janaiyengar** [comment]
Yup, this is a pragmatic decision.  Note that the chances that there's congestion and that the only packets that get dropped are non-retransmittable ones is very low.

**Comment by mikkelfj** [comment]
Are you sure? With, say, SFTP download, what data should the client piggyback ACK onto?

**Comment by kazuho** [comment]
@pravb 
> I assume even with QUIC, unless the implementation goes out of its way, ACKs should get piggybacked with data? If ACKs are always sent separately then I would question this decision since unlike TCP they are occupying network bandwidth. At the least we should document that ACKs must be piggybacked whenever possible.

This seems to be related to #1977.

IMHO, it might be better to state that an endpoint SHOULD NOT send pure ACKs more than one per two packets being received. I say this because some QUIC stacks might use a split design, where ACKs are generated in the kernel (for more timely response) while generating retransmittable packets in the userland.

**Comment by marten-seemann** [comment]
I agree with @pravb here, we should recommend that ACKs should always be piggybacked, unless there is no data sent. For me, this seemed to be the fix for #1977, otherwise you're just cheating your own congestion controller and sending more data into the network than your cwnd allows.

**Comment by ianswett** [comment]
In the "Sending ACKs" section of the transport draft, it currently says:

"A sender SHOULD bundle ACK frames with other frames when possible."

There are cases when sending an ACK for every packet is the right thing to do, such as in response to a PING on an otherwise idle connection, so I don't think it's practical to say that you should not send one ACK per retransmittable packet received in some cases.

**Comment by janaiyengar** [comment]
I'm closing this. Please reopen if anyone thinks further discussion is warranted.
