### ISSUE TITLE
Why are stateless reset tokens 16 bytes long?

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#2018]
We chose the stateless reset token to be 16 bytes long, but I don't remember the reason. It matches the tag size of the AEADs we use, although, as @kazuho points out in https://github.com/quicwg/base-drafts/pull/2006#discussion_r234105228, this might not be true for all TLS cipher suites.

In general, the probability for an attacker to correctly guess a stateless reset token is 2^(-token length). It seems like a 64 bit token would be sufficient to provide protection against an attack like that. Using a shorter token would make rotating connection IDs significantly cheaper.

**Comment by kazuho** [comment]
If the concern is about the overhead of the Stateless Reset Token field of the NEW_CONNECTION_ID frame, the other option might be to make the field optional. I am not sure why the field is mandatory, even though not all endpoints are required to send Stateless Resets.

Conveniently, once #2006 gets merged, the Length field of the Stateless Reset Token field would be the only field we use a 8-bit encoding for Connection ID Length. We can change it to a 4-bit encoding for consistency, and will have 4 bits to encode flags...

**Comment by mikkelfj** [comment]
Due to birthday problem a reset could affect the wrong connection with a real world probability if it is too short. Especially when servers do not coordinate and when state is lost between reboots.

**Comment by marten-seemann** [comment]
@mikkelfj: I don't see how the birthday problem comes into play here.
Let's run some numbers. Assume a cluster that is serving 1 million (≈ 2^20) connections at the same time, each of them using 16 (2^4) connection IDs at the same time. To have a chance of 1 millionth (≈ 2^-20) to disrupt a random connection of those, an attacker would have inject 1 million packets.

**Comment by kazuho** [comment]
Generally speaking, I prefer having the same level of protection for resets as we have for other types of injection; i.e. use a token that is as large as the AEAD tag.

I am not sure if there is a reason strong enough to shorten the token; after all, QUIC v1’s model is to use a stable CID rather than rotating very frequently.

**Comment by martinthomson** [comment]
@kazuho's reasoning is what drove the decision here.  It might be the case that 16 octets is overkill, but there isn't a huge advantage in shaving this down.  The cost isn't significant.

**Comment by ekr** [comment]
I think the real question is whether they are too small. If you build them with self-encryption, you might want more room.

**Comment by martinthomson** [comment]
Self-encryption isn't useful here.  Self-encryption of a connection ID, sure, but the producer and consumer of a stateless reset token is different.

**Comment by kazuho** [comment]
Kind-of related, but by rereading #1041 I notice that a Stateless Reset is considered valid even for packets that arrive from a non-validated path (see [section 10.4.1](
https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.10.4.1)).

Is that intentional? Or should we limit the detection of Stateless Resets to packets that arrive from a pre-validated path?

I ask this because the current design of CID allows 2<sup>18\*8</sup> of space to identify a connection (because CID is generated by the endpoint that uses it to identify the connection), whereas a stateless reset token only provides 2<sup>8\*8</sup> space (because token is generated by peer and therefore be suspected to birthday attacks.

**Comment by martinthomson** [comment]
It is intentional.  Even if 2<sup>64</sup> was insufficient, I don't think that it's that bad.  Birthday bounds only come into play when you want to kill one connection from many.  That is, you are willing to send 2<sup>64</sup> packets and there are 2<sup>64</sup> connection IDs live.  Standard DoS mitigation techniques probably start to apply before the birthday bound is threatened.

**Comment by ekr** [comment]
Oh, yes, sorry. Long day and I was thinking retry token.

**Comment by dtikhonov** [comment]
Time to close this bug? The question has been answered.

**Comment by martinthomson** [comment]
Yep.
