### ISSUE TITLE
minimum payload size requirement creates awkward special case

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#2049]
In #2030 we set the minimum payload size to `4-packet number length`.
This creates a really awkward special case in my code. When packing STREAM frames, I make sure that the last STREAM frame doesn't have the length flag set, so I can save the bytes for encoding the payload length.

In the corner case where I only have a single stream for new a stream with stream ID < 64 that is closing that stream at offset 0, the length of this STREAM frame is just 2 bytes: 1 (type byte) + 1 (stream ID).
If I now add a PADDING frame in order to fulfill the minimum size requirement, this will be interpreted as part of the payload of the STREAM frame, so I will need special logic to detect the special case described above, and set the length flag on the STREAM frame in that case.

The motivation for #2030 was to avoid a special case that would rarely be executed (and which would lead to an undecryptable packet in the worst case). It seems that we achieved that by introducing an even rarer special case, which leads to incorrect delivery of stream data if not properly taken care of.

**Comment by kazuho** [comment]
This is an interesting pitfall!

Maybe you can prepend the PADDING frames instead?

**Comment by marten-seemann** [comment]
I could, if I knew that there I’ll run into this corner case beforehand. But in my implementation, I’ll only know that after packing the STREAM frames. I could also write a check for exactly this special case, and then modify the STREAM frame to include the length field. 

I’m not saying that this problem is not solvable - I just doubt that it’s easier than adjusting the sample offset, plus the consequences for getting it wrong a more severe.

**Comment by kazuho** [comment]
> I could, if I knew that there I’ll run into this corner case beforehand. But in my implementation, I’ll only know that after packing the STREAM frames.

What I mean is that when you notice that the length of the streams is below 4 bytes, you can move them backwards and insert PADDING before them. That logic would replace the logic you have, that appends PADDING frames.

The performance impact of prepending afterwards (i.e. moving and inserting) is negligible compared to the overhead of AEAD.

**Comment by marten-seemann** [comment]
> What I mean is that when you notice that the length of the streams is below 4 bytes, you can move them backwards and insert PADDING before them. That logic would replace the logic you have, that appends PADDING frames.

Sure, I can think of multiple ways to fix this, and I'm not concerned about performance at all. I'm concerned about correctness and implementation complexity.

My point is: I think the way of packing frames and then adding padding is a common way to pack packets, and many implementations will choose to implement it that way. The corner case I described is **very subtle**, and I expect this to be the source of nasty bugs in the future. I think we could save ourselves a lot of trouble by reverting #2030.

**Comment by nibanks** [comment]
I think this can be trivially solved by updating your logic that decides if the length should be included in the STREAM frame. When writing the frame to the packet buffer, if the length of the stream data is less than 4 bytes just always include the length.

**Comment by mikkelfj** [comment]
I think this header protection is starting to bleed into the core packet processing and I don't think that is a particular good idea.

If you revert to the old method header protection method, @kazuho argues that both sender and receiver must perform a check for adjustment. However, you must still check that the received packet is long enough to sample since the packet might be evil or faulty. If the length check is for the common case where no offset adjustment is needed, there is no extra overhead. If the check fails you need to perform a new length check that can handle short packet numbers with short content.

Special casing short packets is a bit unfortunate if you have a lot of short packets to process, but the the overhead is still limited and more importantly isolated to one place in the logic framework. Also, if there are many short packets, branch prediction will likely figure it out.

With the current padding solution you get the special case @marten-seemann mentions, but you might also still have to check if the sampling does not overlap with payload when the packet number is short and the payload is short. If you don't check this you could be triggered to xor the mask into the payload. Likely AEAD will catch this but it is an unsafe praxis, so you still have extra checks for short packets.

**Comment by martinthomson** [comment]
Maybe don't pad, but change the packet number encoding instead.

**Comment by janaiyengar** [comment]
I'm with Nick on this one. I've dealt with this exact problem in a
different context. You need to have logic to decide whether the stream
frame is going to have a length field or not. A simple rule that says
include the length field if the stream frame data size is < 2 makes it a
simple fix.

**Comment by mikkelfj** [comment]
The problem with the simple stream frame check is that it buries logic far away from header protection where it is rather counter intuitive.

**Comment by kazuho** [comment]
@mikkelfj As I stated in 
https://github.com/quicwg/base-drafts/issues/2049#issuecomment-441427122, there are other approaches that you can consider.

**Comment by janaiyengar** [comment]
@mikkelfj : I don't think that's a problem. Like I said, encoding stream frame size is related to packet size  anyway, so it is logic that is going to be a bit non-local as it is.

**Comment by martinthomson** [comment]
Tokyo conclusion: @marten-seemann might send an editorial PR that describes the trap here. Or might close it instead.

**Comment by marten-seemann** [comment]
Describing the special case turns out to be kind of awkward, because you'd have to make a lot of assumptions about an implementation's packet packing logic.
