### ISSUE TITLE
Public routing info

### ISSUE THREAD

**Issue by igorlord** [quicwg/base-drafts#205]
This issue directly applies to the use of Server Proposed Connection ID (issue #119) / Stateless Rejects (issue #60).

"Origin servers" are often complex multi-server data centers with load balancers. Some "origin servers" are actually globally distributed load balancing and routing systems, possibly with multiple levels of load balancing (for example global and local).  Since packets may show up at any load balancer node (both for global and local load balancers), it is very difficult (if not prohibitive) for these load balancers to keep track of the load balancing decision for each active connection and share that state among all nodes.

To enable stateless load balancing, load balancers need every packet to include routing information for its connection. Server Proposed Connection ID (#119) with Stateless Rejects (#60) are the methods of choice, as they allow the "origin server system" to encode some information into the ConnectionID -- a part of the public header present in every packet.  However, depending on the complexity of the encoded routing information, 64 bits may not be enough to ensure a sufficient amount of entropy in the ConnectionID.

The proposal is to allow Server Proposed Connection ID to include additional information to be present in every packet. That additional information can take a form of an optional longer Connection ID (and therefore be immutable) or be a new mutable part of the public header.

**Comment by martinthomson** [comment]
If the server were to provide the connection ID as part of a TLS HelloRetryRequest, then the cookie extension could carry this information adequately.

Generally, I think that this duplicates the stateless reject issue perfectly.

**Comment by igorlord** [comment]
Is that cookie available in every packet belonging to the connection?  Can it be read without access to the crypto secrets?  That's what would be needed for doing routing based on the information in the packets.

**Comment by kazuho** [comment]
I agree with @igorlord.

IIUC STK is something that can be used for correlating QUIC connections. What @igorlord and I are looking for (per https://github.com/quicwg/base-drafts/issues/119#issuecomment-274680186) is a way to correlate packets belonging to a single QUIC connection to a specific POP or a server.

**Comment by ianswett** [comment]
I agree that the ability to have a longer than 64 bit connection ID is potentially useful.  @martinthomson Are you saying that the HRR should inform the client of the new, longer connection ID?  If so, that seems reasonable, but it leaves us with a few more questions:

1) Does there need to be a public flag bit indicating a 128 bit connection ID?   (I suspect yes)
2) Is there a realistic need for anything longer than 128 bits?   (I suspect/hope no)
3) Is there a requirement it only be used once version negotiation is complete?   (I suspect no, since we may want to use it when resuming)

Thoughts?

**Comment by martinthomson** [comment]
HelloRetryRequest could provide a new connection ID.  We'd need a tweak to the transport parameters to permit it, but that's easy.

If we have a longer connection ID, I would suggest that we make all of them longer and we would only use a flag bit to "compress".  I don't think that we need more than 128.  However, 128 isn't enough to do something like encrypt a value and add an authentication tag, so maybe 128 isn't enough.

Yes, I think that connection IDs are hugely useful - if not necessary - during resumption.  To that end, I think that we might also want to put a connection ID in a session ticket so that a resumed connection can use the right routing information (without also creating a correlator).

**Comment by igorlord** [comment]
While a longer ConnectionID would serve my needs nicely, certainly can be cases when this information is not needed. I would rather see "additional public header data" separate from the 64-bit ConnectionID.  That ExtraData could be set in session ticket. Then, the ExtraData would show up in the public header when the client is doing resumption.

This is just a thought; not a requirement...

**Comment by igorlord** [comment]
It looks like we have 24 bits (bytes 1-3) in each packet header available right now.  We could use them for the purposes of this issue as well as #279.

For example, we can specify byte 2 that is an "Echo Request" and byte 3 as an "Echo Response".  When an endpoint generates a packet, it places "Echo Request" byte from the latest packet received from the peer into its "Echo Response" byte.  This will allow endpoints to characterize peer behavior, detect upstream packet reordering, etc.  If we do not cover these packets by crypto, middleboxes can add them.  If not these bytes, we could have a mechanism to attach such cleartext request/response to packets (though that's the road to header extensions).

**Comment by igorlord** [comment]
Looks like there is a discussion of a more specific alternative for middle box timing in #269 (#391).

**Comment by MikeBishop** [comment]
The issues discussed here seem to be more granularly addressed in #631 and #1052.  I think we can close this instance as stale.
