### ISSUE TITLE
SetLossDetectionTime negative timeout

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#2052]
In `OnPacketSent()`, `time_of_last_sent_retransmittable_packet` is set to `now`, and then `SetLossDetectionTimer()` is called.

In `SetLossDetectionTimer()`, the early RTX timer is computed as `timeout = loss_time - time_of_last_sent_retransmittable_packet`, and `loss_time` can be smaller than `now`, which causes `timeout` to go negative.

**Comment by janaiyengar** [comment]
This could use some clarifying, but that shouldn't happen. loss_time is set to 0 if loss_time is smaller than now, see DetectLostPackets() which sets loss_time. Specifically,
```
    if (time_since_sent > delay_until_lost ||
        delta > reordering_threshold):
      sent_packets.remove(unacked.packet_number)
      if (unacked.retransmittable):
        lost_packets.insert(unacked)
    else if (loss_time == 0 && delay_until_lost != infinite):
      loss_time = now() + delay_until_lost - time_since_sent
```
Since loss_time is *not set* when time_since_sent > delay_until_lost, it remains set to 0. This means an ER timer does not need to be set (and is not set in SetLossDetectionTimer(), which is exactly what you want, since setting a timer only makes sense if the event is in the future. In this case, loss_time was before now(), and so, the loss event happens now, causing OnPacketsLost() to be called at the end of DetectLostPackets().

**Comment by larseggert** [comment]
Consider the case that `loss_time` is set in `DetectLostPackets()`, but by the time `SetLossDetectionTimer()` is called, `now` is larger than `loss_time`.

**Comment by ianswett** [comment]
To clarify, this is a case when alarms wake up late, since ideally if this was negative, the alarm should have executed, correct?

I think the easiest fix that fits with how most alarms work is to allow negative values and say they mean execute ASAP.

**Comment by kazuho** [comment]
For somebody unfamiliar with congestion control, it helps if the pseudo-code in the specification was designed to always return a non-negative timeout, because then, you could check the value to see if you have implemented it correctly.

**Comment by martinthomson** [comment]
I think that Kazuho is right.  `timeout = max(timeout, 0)` isn't that hard to add to the algorithm.  An unchecked underflow on an unsigned integer would be an unfortunate outcome.

**Comment by ianswett** [comment]
@martinthomson if the timeout is unsigned, then max(0, timeout) doesn't help because timeout has already wrapped :(

@kazuho Interesting example I've never considered.  However, that doesn't cause an int underflow, just for the timer to be set in the past.

I sent out a PR to avoid the int underflow, because it's easy to fix and I agree it's best to avoid negative values when possible.

I'd rather not do anything to prevent timers being set in the past, because it can happen almost anywhere under some circumstances(ie: late alarms).
