### ISSUE TITLE
Fast Retransmit triggered by single ACK 

### ISSUE THREAD

**Issue by goelvidhi** [quicwg/base-drafts#2059]
From Recovery draft,
"An unacknowledged packet is marked as lost when an acknowledgment is received for a packet that was sent a threshold number of packets (kReorderingThreshold) and/or a threshold amount of time after the unacknowledged packet."

Lets say sender sends packet# 1, 2, 3, 4 and 5 and kReorderingThreshold  = 3. The sender receives ACK for packet# 5. Will that trigger FR? Does this mean that FR will be triggered by a "single ACK"?

TCP causes FR only after receiving 3-Dup ACKs or corresponding SACK. The mechanism described in QUIC recovery draft is a major deviation from TCP.

**Comment by ianswett** [comment]
This behavior is documented in: https://tools.ietf.org/html/rfc7414#section-8 and I believe is widely implemented.

**Comment by siyengar** [comment]
I don't think it is a major deviation from TCP. The spirit of the FR mechanism in TCP is to FR when it sees 3 packets out of order which a receiver can only do via SACKs or duplicate cumulative acks. Since QUIC does not have cumulative ACKs, the notion of DUP acks would not make sense, so an ACK for a packet which is 3 packets out of order would imply that 2 packets before it were lost. It's cleaner and easier to implement.

**Comment by martinthomson** [comment]
Is there any change required to the specification here?

**Comment by goelvidhi** [comment]
Thanks Ian.
@martinthomson,
I think a reference to FACK paper (Forward Acknowledgement: Refining TCP Congestion Control) in the Fast Recovery section of the draft would be helpful.
