### ISSUE TITLE
Document what needs to be checked for address validation

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2125]
```
There is no need for a single well-defined format for the token because the
server that generates the token also consumes it.  A token could include
information about the claimed client address (IP and port), a timestamp, and any
other supplementary information the server will need to validate the token in
the future.
```

Unless I'm missing something, we don't actually document or recommend how to validate that a token matches an Initial. I think we should.

**Comment by mikkelfj** [comment]
I'm wondering about the case where a token is received and has expired and is otherwise valid.

There are several cases:

1. injection attack - replay etc.
2. valid token
3. valid token, but expired, based on servers internal algorithm
4. invalid token, fails servers integrity check

Sometimes it makes sense to close a connection, other times it might be more reasonable to ignore the token and force validation within the connection?

**Comment by ekr** [comment]
@mikkelfj: can you make a separate issue for these points?

**Comment by mikkelfj** [comment]
@ekr #2132

**Comment by martinthomson** [comment]
Discussed with editors; design please.

**Comment by martinthomson** [comment]
Chairs,

This is an odd one.  Late comments mean that I think we need to re-do the process on this.  Do you want `proposal-ready` again, or what?

**Comment by LPardue** [comment]
Assuming comments been made on the PR since the discussion here seems dormant. Has that discussion settled or is it still in process? We can return to proposal-ready if you believe there is emerging consensus on the new remedy to this design issue.

**Comment by martinthomson** [comment]
Yes, I would like to return to `proposal-ready`.  I just wasn't sure that this was permissible.

**Comment by LPardue** [comment]
Moving back to proposal-ready, and it can make it into the next tranche of consensus call when that is made.
