### ISSUE TITLE
How long idle is idle?

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2138]
[Section 7.8 of -recovery](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#restart-after-idle) specifies rules for what a sender does when it starts sending after an idle period.  But surely this doesn't apply when the idle period is short.  Reading that text, an idle period of any duration would trigger this requirement, but I don't think that is the intent.  The period should be defined.

**Comment by mikkelfj** [comment]
I did propose an exponential decay in some other issue and added a link to some TCP RFC 2861 and research that touches upon this.
https://github.com/quicwg/base-drafts/pull/2023#discussion_r235152230

**Comment by ianswett** [comment]
The intent is this is triggered after an idle period of any length.  As it says in the draft, the reason is to limit bursts into the network.

It turns out bursting 100 packets at once into the network almost always causes losses, and two solutions are pacing and resetting the CWND to a lower value out of idle and allowing ack-clocking to smooth the flow.

**Comment by ianswett** [comment]
I think that's what the text does say.  If you think it's unclear, tell me and I can fix it or feel free to send a PR.
