### ISSUE TITLE
Checking frame type encoding?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2155]
```
encoded as a single byte with the value 0x07.  An endpoint MUST treat the
receipt of a frame type that uses a longer encoding than necessary as a
connection error of type PROTOCOL_VIOLATION.
```

Why does this requirement exist? It seems like an odd place to be
picky when we're generally allowing implementations to do unusual
things without requiring checking. To be clear, I'm fine with the
shortest encoding rule, but the must check seems unnecessary
and inconvenient.

**Comment by mikkelfj** [comment]
I believe this is because it allows for fast switch statements in frame processing. It is what makes it affordable to use varints in extension frames. For two byte+ this could be relaxed, but even here, it allows for faster lookups. The situation is different where varints represent countable entities.

**Comment by ekr** [comment]
No. That's a reason to require that you encode deterministically, not that you check

**Comment by martinthomson** [comment]
A MAY would have the intended effect.

**Comment by ekr** [comment]
Yep. I would be fine with a MAY, i just understood that filing issues rather than PRs was right.

**Comment by martinthomson** [comment]
Issues are probably best if there is a design change involved (as there is here - sort of).  PRs are always good.
