### ISSUE TITLE
ACK of ACK advice too strong

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2199]
From @ekr:

>> Once an ACK frame has been acknowledged, the packets it acknowledges SHOULD NOT be acknowledged again.
>
> Suppose that I receive 1 3 5, and I ack these, and that ACK is acked. I then receive 2, 4, 6. This advice would have me send an ACK frame with three ranges, whereas I could send one range.

I think that the advice here is that ranges are dropped when all ACKs for all packets in that range have been acknowledged.  Or something along those lines.

Maybe:

> An endpoint SHOULD omit an ACK Range if it has received an acknowledgment for its acknowledgments of all packets in that range.

Though that seems clumsy.  Better words would be appreciated.

**Comment by ekr** [comment]
Maybe "Endpoints SHOULD not acknowledge packets for which it has already
received acknowledgement of acknowledgements, except where this would
create unnecessary gaps in the encoded ACK frame." Not ideal, I know/

**Comment by gloinul** [comment]
I think this is connected to #2205 in an interesting way. The question that arises is if one MUST include all ACK state between highest received, and the lower PN that needs to be ACKed (as it is newly arrived due to reordering). 

An alternative would be to explicitly allow GAPs for packets that has been received and where the reception's ACKs has been ACKed. But, I guess that results in interesting bookkeeping chores in the implementations.

**Comment by ianswett** [comment]
Agreed the wording is too strong.

Take a look at PR #2245
