### ISSUE TITLE
When can you coalesce connections

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2223]
S 2.4.

```
An authoritative HTTP/3 endpoint is typically discovered because the client has
received an Alt-Svc record from the request's origin which nominates the
endpoint as a valid HTTP Alternative Service for that origin.  As required by
{{RFC7838}}, clients MUST check that the nominated server can present a valid
certificate for the origin before considering it authoritative. Clients MUST NOT
assume that an HTTP/3 endpoint is authoritative for other origins without an
explicit signal.
```

This text seems quite a bit more restrictive than S 9.1.1. of RFC 7540,
which just allows reuse as long as the SAN is present in the cert. Is
that intentional?

**Comment by martinthomson** [comment]
I think that the intent was to present equivalent text.  Though the thinking about coalescing has evolved some in the meantime.  We should discuss where we think the state of this discussion is at and see if we can capture something sensible.

**Comment by ianswett** [comment]
Yes, it'd be good to capture something more up-to-date if we can come to consensus on that.

Is explicit signal meant to indicate DNS and/or ORIGIN frame?  If so, maybe call those two out as examples?

**Comment by LPardue** [comment]
@ianswett I think the dilemma is that some of those things don't exist yet for H3. For example, Mike did some earlier work to redefine ALTSVC frame for H3 but there is yet to be equivalent for ORIGIN or secondary certs.

**Comment by MikeBishop** [comment]
Yes, it's intentional.  RFC7540 allows coalescing based on the cert and DNS, because you're connected to the authoritative origin.  However, HTTP/3 is never connected on the authoritative endpoint for an http(s?):// URL, so you need something else to tell you that's okay.  This could be an Alt-Svc record for that origin delegating to the same UDP port.  This could be an ORIGIN-for-H3 frame telling you to throw caution to the wind and trust the cert, if the client thinks that's sensible.

**Comment by MikeBishop** [comment]
Discussed in London; also blocked on https://github.com/httpwg/http-core/issues/194 defining how a client decides which connection / server to ask for a given resource.

**Comment by larseggert** [comment]
Discussed in ZRH. Waiting for HTTP changes to materialize.
