### ISSUE TITLE
Can I send non-data frames on CONNECT streams?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2229]
S 5.2.

Can you send anything other than DATA on a CONNECT stream?

```
All DATA frames on the stream correspond to data sent or received on the TCP
connection. Any DATA frame sent by the client is transmitted by the proxy to the
TCP server; data received from the TCP server is packaged into DATA frames by
the proxy. Note that the size and number of TCP segments is not guaranteed to
map predictably to the size and number of HTTP DATA or QUIC STREAM frames.
```

You don't say that I can't send anything else, but you don't say
I can't either.

**Comment by kazuho** [comment]
Wouldn’t it be better to just prohibit the HEADERS stream?

We might want to introduce a frame that changes the priority of a stream (e.g., max bitrate). I do not think there’s a strong reason to forbid such kind of extensions only on CONNECT stream.

**Comment by martinthomson** [comment]
I don't want to prohibit extension frames, but the frames defined in the current spec don't serve any purpose.  That is why I said "of those defined in this document".

**Comment by MikeBishop** [comment]
Well, there's technically nothing preventing the use of push....  ;-)

More seriously, I don't feel like the prohibition adds much.  This maps the definition of the CONNECT method into H3 framing -- DATA frames == TCP payload.  In any other respect, it's an HTTP request and frames mean what they otherwise mean.

Is there a particular frame that *needs* to be prohibited?  HEADERS would indicate a trailer block; it might be worth upstreaming to the updated semantic draft that a CONNECT tunnel can't have trailers.

**Comment by MikeBishop** [comment]
Discussed in Tokyo; after the CONNECT takes effect, all frames other than DATA are prohibited unless an extension specifically provides otherwise.
