### ISSUE TITLE
Consider making h3 frame types varint

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2253]
Reusing the language from the transport frame might make this easier, though we might decide not to worry about enforcing the minimum-sized encoding for HTTP.

I'm not advocating for this in particular, but we seem to have a bunch of issues on our plate around the basic frame formats.  See also #2233, which proposes this for settings types.  And #2235, which proposes reordering of the frame.  Considering these issues together might be a good idea.

**Comment by kazuho** [comment]
As stated in 
https://github.com/quicwg/base-drafts/pull/2235#issuecomment-449610469, I do not think that we should make this change.

Our experience from HTTP/2 tells us that it's unlikely that we would run out of the 8-bit number space, and therefore requiring every stack to decode type using varint seems like an unnecessary complexity.

Note that the endpoints would be required to decode the varint even if we decide to enforce minimum-sized encoding. This is because H3 allows use of frame IDs without negotiation.

**Comment by DavidSchinazi** [comment]
I'm in favor of varint with the min-size requirement. The added ability to perform experiments without coordination is worth the addition of a 5-line inline function.

**Comment by ekr** [comment]
> @DavidSchinazi, what do you mean by _without coordination_?

The idea is that there is a lot of space in the 8-byte version, and so if you just pick a random code point in that space, the chance of collision is vanishingly small. This means people can do experiments without having some registry or other mechanism to prevent people choosing the same code point.

**Comment by dtikhonov** [comment]
> if you just pick a random code point in that space, the chance of collision is vanishingly small.

That's what I figured; but it's not zero. (Note that you only get 62, not 64, bits.)

**Comment by ekr** [comment]
No random selection mechanism ever has a 0 chance of collision, but we routinely build systems that rely on not having collisions in these circumstances.

**Comment by LPardue** [comment]
How do we decide how the varint 62-bits are used? I recall this being a discussion topic that led to the invariants saying the space is used however the endpoints decide. Would H3 frames need to coordinate with SETTINGS or just assume varint encodes 1-byte updwards?

**Comment by dtikhonov** [comment]
That's a good point. It would be bad to have to support small values encoded using the full eight bytes.

**Comment by martinthomson** [comment]
One thing that SETTINGS doesn't support is the use of new frame types prior to receiving SETTINGS.  For instance, if I wanted to push out an origin policy in 0.5RTT on a regular connection (using the context-free push that @ekr and @LPardue talked about), I could maybe do that with a new frame type.  Both h2 and h3 allow unannounced use of new frame types, so this would work fine.

If the space is 8-bit, then I can't experiment with that spontaneously and without coordination.

I'm leaning toward the varint on that basis.  The larger encodings will push things off the fast path, but I think that's OK.

**Comment by kazuho** [comment]
@martinthomson While I agree to the fact that it is impossible with the 8-bit design to send new frame types in 0-RTT, I am not sure if I am convinced with the argument that it represents the necessity to use varint frame types.

Consider the 0-RTT context-free push case. We not only need to have new frame types but change the semantics of push. The request headers of a context-push cannot be sent in a way that a client that do not understand the extension can ignore.

Therefore, to me it seems that anything to be sent from the server in 0-RTT needs to have a different unidirectional stream type. Therefore I think #2275 is the way to go, but that having varint frames types is not.

**Comment by martinthomson** [comment]
> The request headers of a context-push cannot be sent in a way that a client (that does not understand the extension) can ignore.

I don't think that is true.  If you assume that this is a QPACK-encoded header block, that would be true (because it would create an expectation of acknowledgment), but you don't need to use QPACK.

That example, is - as you say - better on a unidirectional stream.  And - with a small cost in head-of-line - can be done based on SETTINGS.  But I can't say confidently that there is no use of 0.5-RTT that would benefit from having relative ordering with other activity on the control stream.

**Comment by kazuho** [comment]
>> The request headers of a context-push cannot be sent in a way that a client (that does not understand the extension) can ignore.
> 
> I don't think that is true. If you assume that this is a QPACK-encoded header block, that would be true (because it would create an expectation of acknowledgment), but you don't need to use QPACK.

Maybe I should have pointed out that push streams start with a Push ID, however if a server has a usable Push ID is not determined until it receives a MAX_PUSH_ID frame from the client. Doesn't sending a push stream in 0.5 RTT violate that requirement?

**Comment by martinthomson** [comment]
That's not really relevant.  If the intent is to enable pushing of stuff in 0.5RTT, then the design wouldn't necessarily use push IDs.  It doesn't need to associate the push with a request, so it doesn't need them, it could just use a new stream type.  But I think we're well into the weeds here.  Point is that there *might* be valid uses for sending extension frames before receiving SETTINGS.

**Comment by kazuho** [comment]
> That's not really relevant. If the intent is to enable pushing of stuff in 0.5RTT, then the design wouldn't necessarily use push IDs. It doesn't need to associate the push with a request, so it doesn't need them, it could just use a new stream type.

The point is that how such a context-free push in 0.5 RTT would look like to a client that only implements H3. H3 requires every push stream to carry a Push ID (immediately following the stream type). Every non-negotiated extension including context-free push need to obey the requirements.

> Point is that there *might* be valid uses for sending extension frames before receiving SETTINGS.

Yeah. My point is that there would be not a single case for that, because my understanding is that a server cannot start sending frames on an unidirectional stream due to the restriction I point out.

**Comment by martinthomson** [comment]
Sorry, I'm being dense, obviously.  Which restriction?

**Comment by kazuho** [comment]
No, I was imprecise in my last sentence.

What I was trying to clarify is that it is a requirement of H3 that a server cannot start sending frames on a *push stream* before it receives a MAX_PUSH_ID frame from the client, which arrives after SETTINGS. Therefore, any use of an extended frame on the *push stream* can be negotiated.

*Unidirectional streams* other than the push stream are not restricted to the frame definition of H3, so we have the room to do whatever we want, regardless of if we have varint frame types in H3.

The only case a server might want to send extended frames before seeing SETTINGS is when the client's request arrives before the SETTINGS frame due to packet loss or out-of-order delivery (I haven't considered this case before; please forgive me if you assumed this case).

But if we do care about such case (i.e. using 0.5 RTT or SETTINGS being delivered later), I think we should revisit the discussion of if we should use Transport Parameters for sending H3 settings. We would have the following benefit by exchanging H3 settings using Transport Parameters, :
* QPACK dynamic table can always be used; there is no need to operate in restricted mode until receiving SETTINGS from the peer
* Use of 0.5-RTT push (or any other extension) can be negotiated. That avoids wasting the bandwidth by sending extensions that the client does not understand.

**Comment by DavidSchinazi** [comment]
I agree with @kazuho that exchanging H3 settings in transport parameters has appealing benefits, there is however the downside that client transport parameters are not encrypted, and this could therefore be used for fingerprinting.

That said we may be somewhat off topic, as this issue is about 8-bit vs varint for h3 frame types. Without going into the details discussed in this thread, there seems to be interest in allowing uncoordinated extensions, and varints allow those at a very small implementation cost.

**Comment by kazuho** [comment]
> I agree with @kazuho that exchanging H3 settings in transport parameters has appealing benefits, there is however the downside that client transport parameters are not encrypted, and this could therefore be used for fingerprinting.

I am not sure if we need to care about the downside, considering the fact that we are sending other parameters (including the transport-level transport parameters) in clear. If we do care, we should try protecting all of them.

> That said we may be somewhat off topic, as this issue is about 8-bit vs varint for h3 frame types. Without going into the details discussed in this thread, there seems to be interest in allowing uncoordinated extensions, and varints allow those at a very small implementation cost.

Yeah my point was that people interested in doing private experiments can always negotiate the use of the extensions for all the cases the WG decided to care about, and therefore that there is not a benefit in having varint frame types, especially assuming that sending private experimental extensions to the wild without coordination is likely to be just waste of bandwidth.

**Comment by MikeBishop** [comment]
I don't feel strongly either way.  You can always request a code point assignment from IANA without publishing an RFC, and experience suggests we're unlikely to run out of code points.  (If we do, we revive the EXTENDED frame that contains a sub-type field and a payload defined by the sub-type.)  However, there is value in being able to do some initial tests without registering a codepoint.

This can be done, as Kazuho suggests, either by advertising a setting or by allowing super-high codepoints for private use.

I suspect the technical merits of either will ultimately prove irrelevant and this will wash whichever direction "varint all the things" goes.

**Comment by kazuho** [comment]
I think it's worth noting that the side effect of varint h3 frame types means that we would need to redesign (or abandon) the HTTP_MALFORMED_FRAME error code. It relies on the frame type being 8-bit.

**Comment by MikeBishop** [comment]
Discussed in Tokyo; moderate support and minimal opposition.  We will do this.  HTTP_MALFORMED_FRAME will need to change.  Two proposals:
- reflect the frame type if <255, and 255 indicates "other."
- reflect the low byte of the frame type; collisions should be relatively rare.

**Comment by LPardue** [comment]
If we varint all the things, how likely is it that malformed frames occur? 

Many frames carry just a varint payload, so malformed seems mostly to be that frame length (i.e. payload length) mismatches the sum of received payload parts.

**Comment by ianswett** [comment]
That was one of the core points of #2396, FYI.
