### ISSUE TITLE
loss of only two packets can lead to an unrecoverable situation

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#2267]
Assume that client and server handshake successfully, all packets containing handshake data are received, but the ACK for the CFIN message is lost. Furthermore, assume that the RTT is `x` and there is negligible RTT variance (just to simplify my example).
At this point, the server considers the handshake as completed, and starts its timer to drop the Handshake keys after 3 times the PTO timeout. 3 PTOs equals a duration of `3x`. The client doesn't consider the handshake as completed, since it didn't receive the ACK for the last Handshake packet it sent. On sending that packet, it already set a the crypto timeout timer to a duration of twice the RTT, i.e. `2x`.
When the crypto timer fires, the client retransmits the CFIN. Now assume that this packet is lost (or, leading to the same outcome, the packet is received, but the ACK for it is lost again). The client resets the timer (now with backoff) to `4x` after sending the retransmission. By the time this timer fires, the server will already have dropped the Handshake key. We're now in the situation where the client will never receive an acknowledgement for the CFIN.

Note that a similar situation (with the roles reversed) can occur when an ACK for the certificate sent by the server is lost.

This scenario gets interesting when the client begins sending 1-RTT data after sending the CFIN. The server will be able to read the 1-RTT data, and send acknowledgements for it. There's nothing stopping client and server from running the application protocol, as they normally would, with one interesting caveat: The client will continue to retransmit the CFIN indefinitely and always declare it lost (and decrease its congestion window). Furthermore, the client will only be able to use ACK-based loss recovery, since it is not allowed to use probe timeouts as long as crypto data is still outstanding.

**Comment by ekr** [comment]
It seems like this is an argument that the time to drop the keys is way too low. FWIW, DTLS uses 2MSL for its counterpart timer.

**Comment by martinthomson** [comment]
4 minutes is a bit long in my opinion.  (And longer than the time used in DTLS in practice.)

This demonstrates that we need to capture retransmissions with these timers.  We don't set a limit on the PTO timer, do we?  I couldn't see one.  If there was a limit, then it would be that `PTO*2^(limit+1)`.  Which is probably how the TCP MSL should have been calculated.

**Comment by huitema** [comment]
I think this issue is an indirect justification for implicit ACK. The server may have dropped the handshake key, but it can send and receive 1-RTT packets. So can the client. If the client sends an 1-RTT packet after sending the CFIN, it should receive an ACK from the server. At that point, it knows there is no point in retransmitting the CFIN. If neither the 1-RTT not the CFIN handshake are acked, both can be repeated. If the handshake CFIN was received but the ACK lost, as @marten-seemann envisages, the server may not be able to process handshake packets anymore, but it can receive and ACK the 1-RTT packet.

Of course, that falls apart if the handshake and 1-RTT packets are coalesced. Maybe we need a warning there...

**Comment by kazuho** [comment]
Then, I'd assume that there is nothing we need to address?

**Comment by marten-seemann** [comment]
> I think this issue is an indirect justification for implicit ACK. The server may have dropped the handshake key, but it can send and receive 1-RTT packets. So can the client. If the client sends an 1-RTT packet after sending the CFIN, it should receive an ACK from the server. At that point, it knows there is no point in retransmitting the CFIN.

I agree, but it's better if the server send an ack-eliciting 1-RTT packet right after the handshake completes, since there's no uncertainty on the server's side if the client already has 1-RTT keys. In the stream-0 design team we once had a proposal fo a HANDSHAKE_DONE frame (a 1-byte ack-eliciting frame that is delivered reliably). I consider this a much cleaner solution than relying on timers which might or might not be chosen appropriately to work with a particular loss pattern.

Dropping handshake keys, and moving forward from the crypto mode in the loss recovery (so we can use the PTO timer instead of the crypto timer), is then really straightforward.

**Comment by ianswett** [comment]
@kazuho I think we should do something, because in this case the CFIN would be in-flight, and that would cause only the handshake timer to be active in the recovery draft, even if the CFIN is no longer ACK-able.

Even without HANDSHAKE_DONE, anytime you receive a 1-RTT ACK, you can assume all Handshake data has been received and no longer needs retransmission, so you can drop the Handshake send keys.  That's a unilateral action that the peer doesn't need to be aware of I believe, as long as it's only the send keys being dropped and not receive.

We could advise coalescing a 1-RTT PING with a Handshake timeout retransmission if 1-RTT send keys are available and also advise to consider all Handshake data delivered once a 1-RTT ACK is received and processed?

**Comment by huitema** [comment]
@ianswett I don't think that you can drop the Handshake send keys unilaterally just because you received a 1RTT ACK. You can safely mark all the locally sent handshake packets as acknowledged, and you know that they will never need to be retransmitted. But if you receive a repeated handshake packet from the peer, it means that the peer is not implementing implicit ACK, and also is expecting an ACK on the repeated handshake packet. If you don't send the ACK, the peer could repeat the handshake packet N times and drop the connection.

**Comment by huitema** [comment]
If we want to drop handshake keys, it has to be coordinated with the peer in a standard way. For example, we could update the spec and say that handshake keys are expected to be dropped after the first 1RTT ack has been received (client side) or the first 1RTT-protected packet has been received (server side). That will work because it compels both peers to do implicit acks. But without stating that in the standard, no, you cannot do it.

**Comment by ianswett** [comment]
@huitema Thanks for the correction, I keep forgetting about sending ACKs.

**Comment by kazuho** [comment]
FWIW, current TLS draft states: _After all CRYPTO frames for a given encryption level have been sent and all expected CRYPTO frames received, and all the corresponding acknowledgments have been received or sent, an endpoint starts a timer._

To me this sounds safe and that there is nothing we need to fix.

**Comment by ianswett** [comment]
@kazuho I believe in the case Marten is concerned about "After all CRYPTO frames for a given encryption level have been sent " is not true, because the acknowledgements are not received?

**Comment by kazuho** [comment]
@ianswett Seems to me that that is the case.

**Comment by DavidSchinazi** [comment]
Having thought about this some more, I think that the HANDSHAKE_DONE proposal might be our best way forward.

Knowing when to stop sending ClientFinished/Ack is a variant of the two generals problem, meaning it's actually impossible to know when to stop sending over a lossy network without out-of-band information.

There are two ways to solve this. One is timeouts, similar to what TCP does on graceful connection close. However timeouts aren't great, because they're by definition always too short or too long. In this case, we can do better by using an explicit event that would trigger key discarding. We even have a suitable stream of out-of-band information: our 1-RTT protected packets.

One could consider having the client treat the receipt of any valid 1-RTT packet as confirmation that the ClientFinished was received, but that doesn't work because the server is allowed to send non-sensitive application data before validating the ClientFinished.

Having the server send a retransmittable HANDSHAKE_DONE frame as soon as it receives ClientFinished solves this issue. The server discards its handshake keys when it sends HANDSHAKE_DONE and the client discards them when it receives it.

I personally find this preferable to a short timeout (which can cause an infinite send) and a long timeout (which costs resources).

**Comment by martinthomson** [comment]
Having thought about this some more myself, I'm pretty happy with what we have.  We don't throw away keys until they aren't needed (as @kazuho points out), plus a little extra.  So I think that this is a case of "phew, false alarm".

If anything, we should be discussing whether the timer is needed at all.

**Comment by marten-seemann** [comment]
I don’t think this is the case. In the scenario I described, the server sent and received all CRYPTO frames, and it sent acknowledgments for all the packets. This satisfies the condition for dropping the keys (since it says *all the corresponding acknowledgments have been received OR sent*).

**Comment by huitema** [comment]
I just completed a PR in Picoquic to fix this issue. What it does:

1) Client side, implicit ACK of the first Initial Packet if the handshake key is received. After that, apply a special parser for Initial frames (see point 4 below)
2) Server side, move to a "ready" state when the 1st 1-RTT packet from client is received; as part of that move, implicit ACK of Initial and Handshake packets sent by the server.
3) Client side, move to the "ready" state when first ACK of 1-RTT packet is received from server. This triggers implicit ACK of Initial and Handshake packets sent by the client.
4) In Ready state, use a specific parser for Initial and Handshake message. Effectively ignore all frames in these packets, but if there is an ACK eliciting frame, schedule an ACK.

This removes a bunch of corner cases, such as spurious retransmit of Initial packets in the middle of a migration. It also closes an avenue for DOS against established connections, since Initial packets cannot anymore change the state of the connection once the handshake is complete.

Well, not quite all attacks: Initial packets can still trigger an ACK that might cause an allergic reaction at the peer. But then, the attacker could also send spoofed ACK in Initial packets directly to the peer, so this is not exactly a new attack. Plus, if the peer adopts the defenses outlined above, the spoofed ACK will have no side effect.

**Comment by marten-seemann** [comment]
> Server side, move to a "ready" state when the 1st 1-RTT packet from client is received; as part of that move, implicit ACK of Initial and Handshake packets sent by the server.

This will only work if the application protocol actually makes the client send any data after establishing a new connection.

**Comment by marten-seemann** [comment]
The issue is that the ACK for the CFIN is lost.

I think the cleanest solution here is making the server send a HANDSHAKE_DONE frame in 1-RTT once the handshake is complete. At this point, it can immediately drop the Handshake keys. The HANDSHAKE_DONE is retransmitted according to normal 1-RTT retransmission rules, and as soon as the client receives it, it also drops Handshake keys and switches loss recovery to 1-RTT mode.

**Comment by huitema** [comment]
Yes, adding an handshake done frame would be a very good idea

**Comment by kazuho** [comment]
@marten-seemann 
> I think the cleanest solution here is making the server send a HANDSHAKE_DONE frame in 1-RTT once the handshake is complete. At this point, it can immediately drop the Handshake keys.

That's much more aggressive than what is required now.

At the moment, we keep the handshake keys 3 PTO after the client learns that all the handshake data have been received by the server (see 
https://github.com/quicwg/base-drafts/issues/2267#issuecomment-455036849).

I think it makes sense to use a 3 PTO timer to avoid having negative side-effects to the congestion controller, and I do not understand why we need an explicit signal (Handshake_Done).

**Comment by nibanks** [comment]
My vote would be to have an explicit signal instead of a timer based solution. The loss recovery / congestion controller could use the exact same signal to fix any necessary state. I like the Handshake Done solution.

**Comment by marten-seemann** [comment]
@kazuho 

> At the moment, we keep the handshake keys 3 PTO after the client learns that all the handshake data have been received by the server (see #2267 (comment)).

See https://github.com/quicwg/base-drafts/issues/2267#issuecomment-455945590 why that doesn't work.

**Comment by kazuho** [comment]
@marten-seemann I disagree, as I have stated in 
https://github.com/quicwg/base-drafts/issues/2267#issuecomment-451844018.

Current design guarantees that both endpoints will have 1-RTT read and write keys 3-PTO before the handshake keys are dropped (I think we can agree on this).

It seems to me that you consider loss of an ACK for a Handshake packet should lead to the termination of the connection. Would you mind clarifying why? Because I do not think that's necessary.

**Comment by marten-seemann** [comment]
> Current design guarantees that both endpoints will have 1-RTT read and write keys 3-PTO before the handshake keys are dropped (I think we can agree on this).

Both endpoints have the 1-RTT keys, but the client doesn't know that the server has them, since the ACK for the CFIN was lost. For the client, this situation is indistinguishable from the CFIN itself being lost, so it has to keep retransmitting it.

**Comment by tatsuhiro-t** [comment]
I encountered this issue while testing quinn during interop.  client kept retransmitting Handshake but server had already dropped handshake key.  The problem is that server starts timer too soon; client has no way to know that handshake is received by server and it started timer.
My preference is to have a explicit signal from server.  It is much better to doing something complicated using ACKs.

**Comment by nibanks** [comment]
Perhaps another way to do this, similar to HANDSHAKE_DONE, would be to have a KEY_RETIRE frame that be used to throw the Initial and Handshake keys away individually. This might be slightly better than the proposed HANDSHAKE_DONE method proposed above because the Initial key could be thrown away earlier than the end of the handshake.
