### ISSUE TITLE
address-based access control

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#2279]
In HTTP, we often deploy access control based on client's IP address. What's new in H3 is that the client's IP address might change mid-connection.

The questions are:
* How does the server apply address-based ACL? Should it grant (or reject) access based on client's initial address? Or should it use the source address of the packet that contained the HTTP request?
* If we are to validate access credentials using the initial address, should we suggest H3 client seeing a 4xx response (e.g. 401, 403, 404) to reconnect and retry the request using the current IP address?

**Comment by martinthomson** [comment]
Marking editorial because I don't see a concrete change as a result of this, more likely just advice, but this could flip.

One of the greatest pieces of baggage in HTTP is source-address-based ACLs.  I understand their value in DoS mitigation, but this issue implies something greater than that.  I hope that you don't mean as a substitute for authentication, but more part of a more comprehensive "your IP address is bad and you should feel bad, so here's a 4xx/5xx".

If we are talking about reputation for DoS mitigation, and a connection on a "good" address moves to a "bad" address, I would probably recommend against a change in treatment in all but extreme cases.

If you are using IP address as a proxy for physical location - which is a bad idea in general, but might be justifiable in terms of defense-in-depth strategies for high-value resources under conditions you control.  If your client moved outside that area, then you will need to consult your local policy.  Some policies could say "don't accept the packets", which is the most robust response, but it makes the HTTP status code somewhat irrelevant.  Clients in those contexts will want to be locked to the one network interface somehow.

The question is whether we might want to help the client avoid accidental address changes with an explicit signal.  I'm going to suggest that the answer is "no".

**Comment by kazuho** [comment]
@martinthomson Thank you for elaborating.

> One of the greatest pieces of baggage in HTTP is source-address-based ACLs. I understand their value in DoS mitigation, but this issue implies something greater than that. I hope that you don't mean as a substitute for authentication, but more part of a more comprehensive "your IP address is bad and you should feel bad, so here's a 4xx/5xx".

Yes. I think I should have mentioned that the issue relates to logging and the Forward header field ([RFC 7239](https://tools.ietf.org/html/rfc7239)) as well. They also tie addresses to a request.

> The question is whether we might want to help the client avoid accidental address changes with an explicit signal. I'm going to suggest that the answer is "no".

That works for me.

Though I also think that we should encourage server implementations to tie "current client address" (instead of the initial address) for logging, Forward header field, address-based ACL, because that would be the least inconsistent behavior from what the user would expect.

**Comment by janaiyengar** [comment]
One advice here could be that if a server needs the client to not move to a different IP address, it can simply disable migration via the disable_migration TP. This is a policy decision of course. Does this belong in the applicability draft?

**Comment by ianswett** [comment]
Agreed, if you're doing IP based ACLing, disabling connection migration seems wise.

Otherwise, there's nothing the client can do and the server has to set it's own policy.  Applicability seems like a fine place for this.

**Comment by kazuho** [comment]
@janaiyengar 
> One advice here could be that if a server needs the client to not move to a different IP address, it can simply disable migration via the disable_migration TP. This is a policy decision of course.

I am not sure if I agree with the framing.

It is often the case that only _some_ of the URIs of an origin applies address-based authentication. I do not think that disallowing migration for the entire origin is the correct solution.

I think it is better to encourage (or requires) HTTP servers to consider "current IP address" as the client address of each HTTP request.
