### ISSUE TITLE
STOP_SENDING is not depicted in the send FSM

### ISSUE THREAD

**Issue by rpaulo** [quicwg/base-drafts#2283]
The text says:

>From any of the “Ready”, “Send”, or “Data Sent” states, an application can signal that it wishes to abandon transmission of stream data. Alternatively, an endpoint might receive a STOP_SENDING frame from its peer. In either case, the endpoint sends a RESET_STREAM frame, which causes the stream to enter the “Reset Sent” state.

But STOP_SENDING is not depicted in the send state diagram.  Shouldn't we add this to the diagram under "Send RESET_STREAM" ?

**Comment by martinthomson** [comment]
STOP_SENDING has no direct effect on the stream states.  Its omission was intentional.  That it triggers a the sending of RESET_STREAM is an indirect effect.  It's the RESET_STREAM that acts on the state.

**Comment by rpaulo** [comment]
To me, the sending of the RESET_STREAM is a *direct* effect of receiving the STOP_SENDING.  We put STOP_SENDING in the receiving stream states, so it's omission from the sending stream states was odd to me.

**Comment by MikeBishop** [comment]
@rpaulo, you're exactly correct, but making the wrong inference from it.  The direct effect of the STOP_SENDING is the generation of a RESET_STREAM.  That itself isn't a stream state transition -- it's the sending of RESET_STREAM that has an effect on the state machine, regardless of why it's sent.  Including it in the diagram risks implying that a state change takes place regardless of whether the RESET_STREAM gets sent, and it doesn't.

Otherwise stated, only the originator of a stream part can reset it.  STOP_SENDING is a request to do so, but doesn't perform the action itself.

**Comment by martinthomson** [comment]
Closing.  No intent to change.
