### ISSUE TITLE
Allow extra data after self-terminating h3 frames

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/base-drafts#2291]
The current spec is overly restrictive when it comes to self-terminating h3 frames. If implementations ignore extra data after the expected bytes, this will allow us to add fields down the road without the need to specify new frame types.

Created this issue to host discussion regarding PR #2289.

**Comment by LPardue** [comment]
Thanks!

Some further observations:

0) It reminds me a bit of ARINC 661 wire format :)
1) this seems like it could work with most frames that carry a fixed-size fields and/Or varint payload because the delta between H3 frame length and payload field sizes is the size of postfix fields. However, how is it expected to work with DATA frames? Does HEADERS have a similar problem?

2) why is experimentation with frame types difficult for this use case? 

3) I think I might have hit a similar problem when trying to design the HELIUM Http/2 frames: https://tools.ietf.org/html/draft-pardue-httpbis-http-network-tunnelling-01#section-6.3

**Comment by DavidSchinazi** [comment]
This only applies to self-terminating frames (ones that have a known length regardless of the h3 frame LTV length) so for example it applies to PRIORITY but not to DATA or HEADERS. The idea is to apply the Postel principle when inside the encryption boundary - we may want to add fields later so why prevent ourselves from doing it?

**Comment by mikkelfj** [comment]
Are self-terminating frames not limited to DATA frames to avoid the general complexity and because DATA is the only frame needing this?

If more complex engineering is needed, I think designing separate streams for DATA is better, and probably a v2 feature.

A TLV format can have frames with implicit lengths, iif all types with implicit lengths are known.

**Comment by kazuho** [comment]
Generally speaking, I think having the ability to express self-terminating frames is a good thing.

However, our charter requires us to create a mapping that is "a description of HTTP/2 semantics using QUIC," and my preference goes to adhering the charter rather than chasing the possible optimizations. I am not against changing things in H3 if it clearly helps us, but I am not sure if there is a provable benefit here.

**Comment by ianswett** [comment]
After thinking about this more, I'd prefer to change to TV for cases when forcing implementations to supply a length is adding complexity.  That fixes the same core issue: "What to do if the specified length doesn't match the actual length" in a different way.

**Comment by LPardue** [comment]
I don't understand how that works though, how does the receiver parse the frame if the length is unknown? 

For the DATA frame, in #2098 the exception was made for len=0 because we could use the EOS signal.

**Comment by ianswett** [comment]
Some frames need a length(ie: DATA), but some, such as GOAWAY, clearly do not.  In the case of GOAWAY, computing the length is trivial, so length is just a wasted byte and it doesn't really matter for an infrequently sent frame.  In other cases, it's more of a challenge to add a length after the fact.

**Comment by LPardue** [comment]
Ok but that seems tangential to this ticket's request AFAIK (which may be wrong). I thought the ask was to enable arbitrary fields after the core H3 frame fields. Done by using the delta between how large the frame says it is and the sum of all frame fields.

In the case of GOAWAY it's simple. But imagine I start sending extension frames on the control stream. If you know the type is not supported in your receiver, you can just ignore length bytes and carry on. 

I appreciate the want to reduce some complexity but it seems like we'll end up with an inconsistent set of frame types (TLV vs TV) without much spec text /guidance to support it.

**Comment by DavidSchinazi** [comment]
My thought when I opened this issue was that if we have self-terminating frames that include a redundant length, then we should use that length for extensibility. I'm also fine with @ianswett's proposal of removing the length from self-terminating frames, [even if some consider it over-engineering](https://github.com/quicwg/base-drafts/pull/2235#issuecomment-451296608).

**Comment by mikkelfj** [comment]
I'm not against TLV vs TV when omitting the length is given by a known type (I have argued that before). But reserving half the numeric space for TV values when you need to know the type anyway to decode the TV field, that is what I consider overengineering.

**Comment by MikeBishop** [comment]
(Editor hat off.)

If you know that the peer understands the extended fields, then you've created an extension that redefines a frame type by mutual agreement, which is already legal.  Just redefine the frame in your extension, possibly with optional fields.

If you don't negotiate, the risk is that there are conflicting interpretations of this after-the-fields data.  In order to avoid that, you should move your particular interpretation / the extra fields to a new frame type.

I don't see a path in which stuffing excess data into a frame without negotiation is a wise choice.

**Comment by MikeBishop** [comment]
Discussed in Tokyo; no.  Security concerns, and better ways to do extensions.
