### ISSUE TITLE
New connection ID message

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#232]
In order to break linkability across events that are known to an endpoint, we should explore the possibility of having each endpoint provide the other with a new connection identifier AND a number of packet numbers that should be skipped.  This allows an endpoint to continue using the same connection on a new path without linking use of that new path to use of the old path.

You need to change connection ID and packet numbers or they can be used for linking.  That doesn't preclude the use of other signals for linking, but it removes obvious ones.

This wouldn't address all of the potential linkability issues we identified, but would help in cases where an endpoint is aware of the need - or even potential need - for a gap in linkability.

**Comment by enygren** [comment]
As pointed out by Subodh Iyengar, the server-proposed connection ID needs to be switched to before any server state is needed in order to enable stateless load balancing.

**Comment by ianswett** [comment]
To summarize the only important missing point on #427, we currently have no way to specify a >4 byte packet number, and it seems reasonable we may want to skip to a packet number space quite a ways away to avoid linkability.

I suggest we specify the most significant 4(?) bytes of the packet number in this connection ID frame, because the alternative of using 8 byte packet numbers may increase linkability when migration occurs, since the obvious approach is to increase the packet number by a substantial amount.

Or we can add an 8 byte packet number if my concerns about linkability are unfounded, as it'd be a bit simpler.

**Comment by ianswett** [comment]
I believe this issue also requires #423

**Comment by martinthomson** [comment]
@ianswett, I always planned to add a packet number gap with each connection ID.  The client then skips that number of packet numbers when changing the connection ID.  The server can easily remember the delta that it bound to each connection ID.

**Comment by ianswett** [comment]
@martinthomson  In order to deal with packet loss, I believe it needs to specify where the connection ID's packet number space begins(ie: what it's 0 value is) in real packet number space, not just the size of the gap.

**Comment by RyanAtGoogle** [comment]
@martinthomson clever! I like that idea.

@ianswett I think it would be quite similar to how the server deals with packet loss today. On connection id X, when a packet is received, the server compares the (truncated) on the wire packet number to the largest received packet number and uses that to determine the full packet number. 

In the case where the connection id is now Y, it compares the (truncated) on the wire packet number to the packet_gap(Y) + largest received packet number and uses that to determine the full packet number.

Does that sound plausible?

**Comment by martinthomson** [comment]
@RyanAtGoogle has it precisely correct.  (In practice, this would in fact allow for a smaller gap than the agreed one to be used, but that's probably slightly nutty.)

**Comment by ianswett** [comment]
So to clarify the algorithm, the receiver would prime the "expected next packet number" to be the last received packet + the specified gap?

I believe the size of the gap is related to the size of the packet number.  ie:  If you're using 4 byte packet numbers, you need the gap to be as much as 4 billion?

If the new connection ID is used to transmit over multiple paths at once, this could get a a bit messy because there's a risk the packet number spaces get relatively close?  What if two migrations occur close together in time and/or the first migration fails?  If the first migration fails, I think the connection must immediately close with the gap based approach?

**Comment by martinthomson** [comment]
Actually, the size of the gap is determined by the amount of entropy you want to add.  Obviously, <4 billion will lead to having some bits remaining the same, so I would recommend a number that is close to or larger than that size.

If you have to migrate twice, then you could go back to the baseline.  You could even use largest_acked on the sender as well as the receiver for the baseline.

**Comment by ianswett** [comment]
Ok, now I understand exactly what you're saying, and it was originally what I had in mind, and I'm concerned about two potential issues:
1) You can't safely increase the packet number by more than ~2^31 today, because we only have 4 byte packet numbers on the wire.  Ideally you'd like the packet number gap introduced to be totally random within the full packet number range?  Or possibly we're ok with a single bit of correlation?
2) If you tried to migrate a second time before receiving an acknowledgement for the first time.  I guess that ends up being a sub-case of 1, where the amount you can further increase the packet number becomes limited because the peer hasn't acked the first migration.  Going back to the baseline is dangerous because you don't know if any packets on the intermediate path were received, and it would take some carefulness to avoid re-using packet numbers.

**Comment by martinthomson** [comment]
@ianswett,

On 1, a larger gap is possible if you are also changing the connection ID and you require that the connection ID change and gap be concurrent.

On 2, you are right, double migration is nasty.  You certainly can't send two packets with the same number.  Do you have any ideas on how we could avoid that?

BTW, ekr's design for connection ID obfuscation wouldn't suffer from this.

**Comment by ianswett** [comment]
My solution to both was to send a connection ID paired with the starting packet number that Connection ID indexes to, but there may be better solutions.

If the packet number is encrypted, there are still potential problems we need to properly specify, but they aren't privacy problems.

**Comment by martinthomson** [comment]
The problem with that is that you have to use the connection ID once you hit that packet number or burn that connection ID once you get too close (for some definition of close).

**Comment by martinthomson** [comment]
I have a solution for double-migration: require a strictly ordered sequence of new connection IDs.  Every associated packet number increment has to be added.  So if you move twice, you will have added a delta twice as well.  You can't skip a connection ID without also accounting for the packet number offset.  Then there is no ambiguity.

**Comment by hardie** [comment]
On Wed, Apr 26, 2017 at 9:31 PM, Martin Thomson <notifications@github.com>
wrote:

> I have a solution for double-migration: require a strictly ordered
> sequence of new connection IDs. Every associated packet number increment
> has to be added. So if you move twice, you will have added a delta twice as
> well. You can't skip a connection ID without also accounting for the packet
> number offset. Then there is no ambiguity.
>
> When you say "strictly ordered" here, you mean ordered according to the
list provided, right?  So you would still allow the connection ID to wrap
if that was the consequence of the new ID plus offset?

Ted

**Comment by martinthomson** [comment]
Ordered in terms of order of delivery, or probably with a number attached (so that packet reordering doesn't cause issues).

The connection ID can't really wrap, it's not a sequence number.  The packet number wouldn't be permitted to wrap either, because that leads to a two-time pad on the AEAD.  2^32 is all you need to ensure that the next number appears to entirely random, so 2^31 on average should be OK.  My hope is that the occasional small gap in packet number won't risk running out entirely (2^64).

**Comment by janaiyengar** [comment]
Yes, as I was catching back up on this thread, that is exactly what I was thinking. We need a message that (i) hands out index + connection ID (assuming we may want to send this message more than once, to hand out more connection IDs as needed), and (ii) a packet number delta. The indices of the connection IDs across the observed migration can be used to determine the expected packet number gap.

**Comment by martinthomson** [comment]
You know, I could write this up, but it would be incomplete.  The third item here is the public reset verifier, which needs to be updated for every new connection.

Of course, if we decide that the verifier has to be in the clear, then we have to create a completely new design.

**Comment by janaiyengar** [comment]
Hm, good point. If we're in agreement we have something for now, I suggest
then that we wait to see where the Public Reset conversation lands. Let's
not write this up only to go back and revert shortly after.

**Comment by janaiyengar** [comment]
I think we have a solution here, which suggests to me that we aren't
stalled on this issue. My hope is that we'll resolve Public Reset in Paris,
and we can discuss this point there as well. Once we have them both
resolved, we write them both up.

But I don't have a strong opinion here and I'm fine with either.

(FWIW, we have a bad PR design -- send it in plaintext with no crypto.)

**Comment by martinthomson** [comment]
That's a fair point.  I will write this up without a verifier update and patch that in when we resolve on a public reset design.
