### ISSUE TITLE
Spoofed connection migration as a DoS vector

### ISSUE THREAD

**Issue by igorlord** [quicwg/base-drafts#2342]
Section 9 "Connection Migration" has this text:

> An endpoint which has sent this [disable_migration] transport parameter, but detects that a peer has nonetheless migrated to a different network MAY treat this as a connection error of type INVALID_MIGRATION.

How can an endpoint distinguish "a peer has nonetheless migrated to a different network" vs "a man-on-a-side attacker has resent/raced a packet from a different IP"?  If this hinges on path validation, an insidious attacker can actually own the new IP and proxy packets with PATH_CHALLENGE back to the client and resend packets with PATH_CHALLENGE_RESPONSE from its IP.

**Comment by martinthomson** [comment]
Yeah, that seems like too simple a DoS.

It sort of highlights the need to implement much of the migration machinery if you consider the risk of NAT rebinding.  Unless you plan to only permit remote address changes based on a "same network" heuristic.

**Comment by martinthomson** [comment]
Tokyo conclusion: with our answer to #2143, the endpoint that disables migration will have to do the full migration machinery.  If it doesn't do that work, then the server needs to drop the packet (thereby ignoring it).

Note that it can't send a stateless reset here, because that would produce the attack in a different form - our existing text on defense against stateless reset oracles would prohibit that anyway.

We should perhaps rename the transport parameter to "disable_explicit_migration" or "disable_active_migration".

**Comment by larseggert** [comment]
Discussed in London: @erickinnear to incorporate a resolution in #2637 or a separate PR

**Comment by erickinnear** [comment]
London: 
- Also remove the error code, since it's no longer a protocol violation.
