### ISSUE TITLE
nothing can be sent when receiving a packet just after the idle close timer expires

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#2347]
IIUC, the primary reason of having STATELESS_RESET is to let the client notice that the connection is dead immediately, so that it can retransmit the request using a new connection. However, when a server receives a request immediately after it's idle close timer has expired, it cannot send any packet in response, because it is in the draining period. Is this the expected behavior?

IMO, we should always allow a server to respond whenever it receives a packet after the idle timeout has expired. One way of allowing that is to let an endpoint immediately discard the connection state when the idle close timer expires.

**Comment by martinthomson** [comment]
Tokyo conclusion:  Forbidding the server from responding in this window is not great.  We will drop the closing/draining period after an idle timeout and have the endpoint just drop state.

@ianswett suggested that you could send the CONNECTION_CLOSE that you might have otherwise sent, but it is easier to just shortcut the closing period.

**Comment by martinthomson** [comment]
Amendment based on discussion: suggest setting the idle timeout to `max(idle_timeout, 3*PTO)` to avoid pathological cases.
