### ISSUE TITLE
Spoofed retry token attack on IP authentication

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#2394]
If a Man on the Side attacker (A) is able to observe a Retry token from server (S) intended for a legitimate client (C), then (A) can either race (C) to use the token, or hope that the token can be reused within a limited time frame and use the token even if (C) has already done so.

(A) can now start a new apparently legitimate connection by spoofing the source address to that of (C) since it can observe packets sent to that address.

If (S) issued the Retry token in the hope of verifying that it speaks to a trusted machine on the network, then (A) might be able escalate privilege to that of (C).

The defence would be for (S) to not authenticate (C) based solely on its IP, but the Retry facility might lead some operators to believe that a Retry is a reasonably safe identity mechanism.

**Comment by mikkelfj** [comment]
@marten-seemann mentioned that a retry always lands on the same server so it is feasible to require a reset token to always be accepted at most once (assuming there is a reasonable timeout).

However, (A) can then still race (C) to gain privilege.

A less likely attack is that (A) downloads a large file to flood (C) since (C) gets mirrored traffic. But (A) must also be able accept the traffic to maintain ACK's.

**Comment by kazuho** [comment]
This is an interesting attack, and I have several points that I would like to argue.

First, this is not an MOTS attack that we need to consider. Because the attack can be mounted by a malicious client. A client first obtains one token, then uses that token to create multiple connections. That is an attack vector that we need to fix (assuming that we haven't already).

Note also that we are giving up to have protection against on-path attackers injecting Initial packets.

Therefore, the protection method that @marten-seemann is fine. It's true that an MOTS attacker can race a Retry to prevent a legitimate client from establishing a connection. However that's not something we need to fix, considering that an MOTS attacker can simply inject an Initial packet containing a CONNECTION_CLOSE frame to disrupt the handshake.

Lastly, I would like to point out that there is another (possibly simpler) way of addressing the issue. A server can embed the server CID issued in the Retry packet in the Retry Token that it issues, and use the token to confirm that the Initial packet sent in response to the Retry contains the correct DCID.

I think we should recommend servers to implement some kind of protection.

**Comment by mikkelfj** [comment]
> However that's not something we need to fix, considering that an MOTS attacker can simply inject an Initial packet containing a CONNECTION_CLOSE frame to disrupt the handshake.

This is not about a DoS attack. It is about about privilege escalation. The man on the side can observe another connection and pretend to have the IP of the original client. If the server grants access to the observer based on the original clients IP, trust has been broken.

Racing the packet is sufficient to achieve that.

Racing will also close the original clients connection iff the token can only be used once, but that is a minor concern, I agree.

**Comment by mikkelfj** [comment]
I believe the fix is to only allow tokens to be used once as Marten suggests, and to add to the vulnerably section that a server SHOULD/MUST not grant privileged access based on the clients IP address verified by a Retry token since on-path devices and also path observing devices can race a Retry packet with a spoofed IP address.

**Comment by kazuho** [comment]
> to add to the vulnerably section that a server SHOULD/MUST not grant privileged access based on the clients IP address verified by a Retry token since on-path devices and also path observing devices can race a Retry packet with a spoofed IP address.

I disagree, because a node that can receive packets going to address X and that can also send a packet that states to originate from X can initiate a new connection by itself.

For such a node, there is no need to piggyback on an Initial sent by the true owner of address X.

**Comment by mikkelfj** [comment]
I might be just the right to establish a connection, which is bad enough.

But a QUIC server implementation could also provide an API that indicates that 1) connections should be Retried to prove IP, and 2) provide the source IP of the application layer with a status of verified. From then on, things can go arbitrarily wrong.

**Comment by mikkelfj** [comment]
But even without Retry, I think things can go wrong if the server API indicates the IP is trusted. But without Retry the conclusion arrives later and requires an on-path attack.

So that begs the question: why would you Retry for other reasons than to redirect to a new host?

**Comment by mikkelfj** [comment]
Oh, but you can always create a new connection with a spoofed IP, you don't even need a Retry token.

But that makes me question the entire point of
https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.8.1.1

> As long as it is not possible for an attacker to generate a valid token for its own address (see Section 8.1.3) and the client is able to return that token, it proves to the server that it received the token.

But an attacker does not need to forge a token, it can just pretend to have another IP that it can listen in on. The server will then voluntarily provide the token.

I suppose this requires a v2 authenticated handshake.

**Comment by mikkelfj** [comment]
So the conclusion is that you cannot do anything about it in v1. There isn't even much reason to strongly prevent token reuse since only path observers can reuse it, and they have powers anyway.

But there is reason to advise in vulnerability that Retry only protects against off-path attackers, not on-the-side or on-path attackers.

**Comment by martinthomson** [comment]
This is a fairly non-interesting attack.  I read this as saying that if you can send and receive packets for a given IP address you can make connections from that address.  From the perspective of what we can reasonably test, there is no distinction between that and genuinely owning the address.

The point about the number of times that Retry tokens can be used is a fine one.  Adding a note about expected lifetime of these tokens to [Section 8.1.1](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#validate-retry) is a fine idea.

**Comment by ekr** [comment]
Discussion on London: I think this misunderstands the purpose of the retry token.

As a practical matter, we assume that servers under normal conditions respond to Initial with a full first flight. Otherwise, QUIC is a two-round trip protocol no better than TCP. So, there is a builtin 3x amplification attack on random victims.

The purpose of the retry token is when the *server* is under attack from spoofed packets, and wants to efficiently distinguish between true and false IPs so it can blacklist the attackers. A retry token collection attack is possible here too, but the anti-DoS system has to track IPs anyway, and so can just track any IP address which is associated with excessive traffic anyway.

Proposal: Close with no action.
