### ISSUE TITLE
Can VN and Retry packets be coalesced?

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#2407]
They don't have a length field, so the only place they could go is at the end of a packet.
As the spec currently stands, it's valid to send a packet like this.

There's little value in doing that. Do we want to continue to allow this?

**Comment by kazuho** [comment]
My understanding is that they are implicitly forbidden, because coalescing packets belonging to different connections are forbidden, and because there’s nothing to coalesce with when either of the two types of the packets is sent.

I am not sure if we need to be more clear on that, considering the fact we generally use MAY for the discarding rules for coalesced packets.

**Comment by ianswett** [comment]
VN certainly causes a new connection based on discussions in Tokyo.

Retry does not cause a new connection(ie: same ClientHello).

Clarifying this seems wise if it's not already clear.

**Comment by mnot** [comment]
So, is this editorial?

**Comment by janaiyengar** [comment]
I'm with @kazuho, but I'm still wondering: what is the clarification that we can provide?

**Comment by kazuho** [comment]
@janaiyengar Simply clarifying that "VN and Retry packets will never be coalesced" as part of the changes we would make in #2308 might be a good idea.

We do not need to use a RFC 2119 word here due to the editorial nature of the issue.
