### ISSUE TITLE
Reserved versions are not version-dependent

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#2434]
We only talk about reserved versions in the transport document. Since they're used to trigger VN, they need to be version independent. Should they be moved to the invariants?

**Comment by martinthomson** [comment]
I would say no.  We don't need to make any particular version invariant.

**Comment by marten-seemann** [comment]
If you include reserved versions for greasing purposes in the VN packet, and we later define a QUIC version with that version number, a client might pick this previously reserved version. So to me it looks like the reserved versions have to be stable between different versions.

**Comment by martinthomson** [comment]
The registry is stable.  There was talk about moving that, but it never happened.

**Comment by larseggert** [comment]
@martinthomson are you saying that because the version registry is stable across versions, its contents in effect become part of the invariants?

**Comment by mnot** [comment]
Would it make sense to refer to the version registry (or at least its definition) in invariants? If that's all this is about, we could just call this editorial< I think.

**Comment by MikeBishop** [comment]
There's a balancing act here.  From an architecture standpoint, the registry and reserved versions belong in the invariants, because they're inherently part of the cross-version properties of QUIC.

However, there's also the political answer, which is that Invariants describes what we want outside observers to focus on about the wire image.  The idea that certain versions aren't "real" is explicitly *not* something we want outside observers to pay attention to.  Thus, the current location is a(n exceptionally weak) form of security by obscurity.

**Comment by mnot** [comment]
That sounds like an argument to close this issue with no action. @marten-seemann do you feel strongly about this? Anyone else?

**Comment by marten-seemann** [comment]
@MikeBishop's argument sounds reasonable to me. I'm ok with closing this.
