### ISSUE TITLE
Connection ID Length changes

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#2473]
There's nothing in the spec that prohibits this, except from zero to not zero. But should there be?

1) For the receiver, it's a bit annoying to have to store the length of each additional connection ID
2) We could eliminate the length field from the frame
3) If we're concerned about changes from zero-length being detectable, we should also be concerned about length changes being detectable. Ultimately, the complexity of handling this is the problem of the endpoint generating the connection ID, so if you want to do this to yourself, go for it. The use case for going from zero to not-zero (unexpectedly needing migration) is as relevant as changing between non-zero lengths (migrating existing connections when the routing scheme totally changes)

I would recommend one of the following:
A) New CIDs must retain the same length
B) Remove all restrictions on CID length changes - I sorta lean towards this one,  but I think both are better than the status quo.

**Comment by nibanks** [comment]
I brought this up on the PR when we added the NEW_CONNECTION_ID frame and it was decided that some folks thought it was a feature that (nonzero length) CIDs could length if they wanted...

**Comment by ianswett** [comment]
I strongly oppose A).  There are definitely cases I may want to change CID length.

I have no idea why we say you can't change from zero to non-zero lengths.  That being said, I'm not sure what the incentive is for a peer to move from zero to non-zero, so maybe restricting it doesn't matter.

**Comment by mikkelfj** [comment]
There are routing implications going from 0 to non-zero. A 0 would be a 5-tuple hash, or so. Suddenly changing that could confuse middle boxes. It could also change some privacy assumptions made by the peer when accepting the connection.

**Comment by martinduke** [comment]
@mikkelfj This is entirely up to the endpoint generating the CIDs, yes? Endpoints already need to be aware of their routing architecture.

I don't understand the privacy implications you allude to.

**Comment by mikkelfj** [comment]
A CID is a cookie that can simplify tracking compared to a translated 5-tuple that depends on hidden routing table state. A CID could also suggest that migration is suddenly undertaken even if not permitted. These are both weak arguments, but it is easier to be fooled when the CID come and go if you do not check everything carefully.

**Comment by martinthomson** [comment]
@ianswett, consider how an endpoint might distinguish between a short header with a zero-length connection ID and a packet with a non-zero-length connection ID. If the need to do trial decryption doesn't bother you (it is after all self-inflicted) then we can maybe allow a transition between the two, but I think that was the primary reason.

**Comment by ianswett** [comment]
Thanks, given it seems to be a core goal of the QUIC design to avoid trial decryption, that makes sense.

**Comment by dtikhonov** [comment]
It is not clear to me what this bug is about.  @martinduke, do you propose that _NEW_CONNECTION_ID_ frames always carry CIDs of the same length for a given connection?

**Comment by MikeBishop** [comment]
If you have a "mixed" connection, you lose the ability to reject packets because the CID is unknown; it might be your zero-length CID, so you have to try to process packets with unknown CIDs.  But also, if you *do* recognize the CID and it fails to decrypt, you have to decrypt it again -- it might be a ZLCID packet where the packet number happens to encrypt into a valid CID!  So I agree, let's not do that.

I don't feel strongly about requiring all CIDs on the connection to be the same length, save to note that it's not implausible for a server to reach a case where it must either kill a connection or increase the CID size being used.  (Let's say that all/enough CIDs in the previous size have been allocated already.)

**Comment by martinduke** [comment]
I don't understand the trial decryption argument.

An inherent property of zero length is that I must trial decrypt any pkt with unknown connection id, so the existence of non-zero-length IDs is orthogonal to this point.

If I have a ZL and non ZL CID, on every packet I do a simple byte compare to check which it is, then decrypt. No trial decryption required.

**Comment by martinduke** [comment]
@dtikhonov that was one proposal, but at this point it's dead. Now the proposal is for hosts with ZLCIDS to offer non-perishable length in new_conn_id frames

**Comment by MikeBishop** [comment]
Zero-length is prohibited from migrating (modulo #2441), so the 4-tuple gives you quasi-similar protection against injected junk that a CID does -- to inject, you have to be able to see previous packets, hence on-path.  You're not (quite) signing up to decrypt any junk packet you get handed.

**Comment by martinduke** [comment]
@mikebishop I think you're describing migration with only ZLCID, which IMO would still be illegal.

If a short header comes in from a new address, simply match a known local CID, like for any other non-ZLCID connection. If no match, drop it.

**Comment by MikeBishop** [comment]
So you're suggesting that clients MUST use a CID until the path has been validated and then MAY switch back to the zero-length CID?  Hm.  That does still have the double-decrypt case for a valid CID on an established path, but that should be vanishingly rare outside of an attack.

I'm still not convinced it's necessary, but it's possible it could be done safely.

**Comment by mikkelfj** [comment]
Is it important/worthwhile?

**Comment by martinduke** [comment]
@mikebishop you are ahead if me and thinking about going from non ZLCID to ZLCID. That is not what I'm proposing, and would have to think about it.

For the moment, do you see a trial decryption issue if we allow ZL to nonZL transitions only?

**Comment by martinduke** [comment]
@mikkelfj why ban it we're not sure?

**Comment by mikkelfj** [comment]
... unnecessary complexity and risk. But granted, there ought to be justifications for the requirements set.

**Comment by kazuho** [comment]
@martinduke 
> There's nothing in the spec that prohibits this, except from zero to not zero.

Going from non-zero to zero is also prohibited. NCID cannot carry a zero-length CID. Prohibiting it makes sense, because a server can have at most one connection that uses a zero-length CID, assuming that the CID might be used for a new path (that's the intent of delivering a CID in a NCID frame).

While I think it's possible to design an endpoint that does zero-to-non-zero transition without trial decryption, I think forbidding both ways is cleaner. Is there a particular benefit in supporting zero-to-non-zero transition?

**Comment by kazuho** [comment]
@martinduke 
> If a short header comes in from a new address, simply match a known local CID, like for any other non-ZLCID connection. If no match, drop it.

The issue with the approach is that the server cannot distinguish between a connection that it has lost state and a broken packet with zero-length CID. The server loses the ability to send stateless resets for all of the connections it handles.

Note: IIUC, a server is expected to generate stateless reset tokens by using 5-tuple (if CIDL=0) or by using CID (if CIDL!=0).

**Comment by martinduke** [comment]
@kazuho

> a server can have no more than one connection that uses a zero-length CID, assuming that the CID might be used for a new path (that's the intent of delivering a CID in a NCID frame).

Why not? ZLCID connections are separated by 4-tuple. One of the clients proposes a new CID. Then something comes in a new address with the CID previously proposed. It seems fairly simple to distinguish the two.

**Comment by kazuho** [comment]
@martinduke Here's an example.

The server has two connections; A (using client address IPaddr<sub>A</sub>) and  B (using address IPaddr<sub>B</sub>). The server issues zero-length CIDs to both of the connections.

Then, when the server receives a short header packet from IPaddr<sub>C</sub> (due to either A or B migrating a new address), the server cannot tell if the packet belongs to connection A or connection B without trial decryption.

**Comment by Ralith** [comment]
A CID from NEW_CONNECTION_ID might also be used to reduce linkability following an idle period, and if non-ZLCID to ZLCID transition were permitted, it might also be used for a client to explicitly opt-out of support for migration in exchange for reduced overhead. Initiating a migration with a ZLCID doesn't make sense, but these other cases seems reasonable to me.

**Comment by martinduke** [comment]
Either I have been very unclear, or I am proposing something that makes a simple error so that it is confusing everybody. Here is what I am proposing to allow (CIDs are letters)

Client                                                                                                    Server
[ Connection already setup; client has no CID ]
IP: 1.1.1.1 to 2.2.2.2 (DCID A) ----->
           (contains NEW_CONN_ID B)
                                                                              <--- IP: 2.2.2.2 to 1.1.1.1 (no DCID)
                                                                                       (contains NEW_CONN_ID C)
(exchange continues with IP addresses above, with no CID to client and CID A to server)
(then there's an address change)
IP: 3.3.3.3 to 2.2.2.2 (DCID C) -------->
                                                                               <---- IP: 2.2.2.2 to 3.3.3.3 (DCID B)

This is the case I am concerned about. I do not see, at the moment, any reason why switching "client" and "server" above should make a difference.

What I am definitely NOT proposing is that an endpoint migrate while never accepting a non-ZL CID.

**Comment by martinduke** [comment]
Format fail, try again

Client                                                          Server
[ Connection already setup; client has no CID ]
IP: 1.1.1.1 to 2.2.2.2 (DCID A) ----->
(contains NEW_CONN_ID B)
                                                      <--- IP: 2.2.2.2 to 1.1.1.1 (no DCID)
                                                     (contains NEW_CONN_ID C)
(exchange continues with IP addresses above, with no CID to client and CID A to server)
(then there's an address change)
IP: 3.3.3.3 to 2.2.2.2 (DCID C) -------->
                                                      <---- IP: 2.2.2.2 to 3.3.3.3 (DCID B)

**Comment by martinduke** [comment]
Format fail, try again

Client                        Server
[ Connection already setup; client has no CID ]
IP: 1.1.1.1 to 2.2.2.2 (DCID A) ----->
(contains NEW_CONN_ID B)
                 <--- IP: 2.2.2.2 to 1.1.1.1 (no DCID)
                        (contains NEW_CONN_ID C)
(exchange continues with IP addresses above, with no CID to client and CID A to server)
(then there's an address change)
IP: 3.3.3.3 to 2.2.2.2 (DCID C) -------->
                   <---- IP: 2.2.2.2 to 3.3.3.3 (DCID B)

**Comment by ianswett** [comment]
@kazuho The server can also statelessly reset the connection if it has no state by 5-tuple, as you mention above.

I don't have a very strong feeling on this, but it seems like another thing we forbid that has some potentially valid uses with drawbacks we don't like.  Unless we think this is actively harmful, I'd prefer to allow this.

If a server never wants to transition to/from a 0-len CID, it's easy for it to do that.

**Comment by kazuho** [comment]
@martinduke 
> Either I have been very unclear, or I am proposing something that makes a simple error so that it is confusing everybody. Here is what I am proposing to allow (CIDs are letters)

I think it works, though I wonder why the client needs to switch to using a zero-length client CID when it migrates. Can't it just continue using a zero-length client CID?

@ianswett 
> The server can also statelessly reset the connection if it has no state by 5-tuple, as you mention above.

Please let me retract that, because it's wrong. The design of stateless reset requires the source of the reset token to not be reused. That's something the sender of stateless reset can enforce when using CIDs, but not when relying on the 5-tuple. Quoting from section 10.4.2 of the transport draft: _This design relies on the peer always sending a connection ID in its packets so that the endpoint can use the connection ID from a packet to reset the connection. An endpoint that uses this design MUST either use the same connection ID length for all connections or encode the length of the connection ID such that it can be recovered without state. In addition, it cannot provide a zero-length connection ID._

> I don't have a very strong feeling on this, but it seems like another thing we forbid that has some potentially valid uses with drawbacks we don't like. Unless we think this is actively harmful, I'd prefer to allow this.

I would not oppose to allowing it, though the premise would be that it does not introduce complexity to other implementations that would not be using the feature, because I do not understand the practical benefit.

**Comment by martinduke** [comment]
@kazuho To avoid trial decryption!

**Comment by kazuho** [comment]
@martinduke IIUC, generally speaking, trial decryption becomes inevitable for a client when it coalesces multiple connections that uses the same server 2-tuple onto a single socket.

In the approach you describe, the client is not coalescing multiple connections in such a way on a single socket when it initiates the connection, because it is initially using zero-length CID. But it sounds like that the client will be using the socket in such a way on a socket it decides to migrate.

What I do not see is the rationale behind such a design.

If the client's preference is to minimize the network bandwidth (by using zero-length CIDs), shouldn't it use zero-length CIDs for subsequent paths that it migrates the connection to? That's possible, as long as it does not coalesce multiple connections that share the same server 2-tuple onto a single socket. The simplest way of doing that is to use a dedicated socket for each connection.

Or if the client's preference is to minimize the number of sockets it maintains, shouldn't it be always using non-zero-length CIDs from when it initiates a new connection?

**Comment by DavidSchinazi** [comment]
I think banning switching from non-zero-length CID to zero-length CID might be too constraining. Imagine a server is initially reached via an IPv6 anycast address, and it tells the client its IPv6 preferred address. If that server owns a /64, it can give a different preferred address to each client which allows zero-length CIDs and migration without requiring trial decryption because the server can find the connection simply by looking at the packet destination IP address. (Note that kernels don't let you easily do that today but that can be fixed.) The only downside I'm seeing here is that migration can now be tracked across paths since the connection ID doesn't change and the server IP is enough to identify a connection. I suspect there are deployment scenarios where reducing CID overhead is more important that the privacy risk. But, given that the server preferred address is only advisory, a client that cares more about privacy than about the CID overhead can simply refuse to switch over. With all that said, I don't think the restriction against zero-length-CID helps us.

**Comment by martinthomson** [comment]
I'm willing to concede that a server preferred address is a special case here.  Destination IP address is accessible, if awkward to get at.

There is also a valid argument that says that you get what you ask for.

Either way, I don't see this being resolved here effectively.  You could raise this on the list or wait until Prague to discuss in person.

**Comment by martinduke** [comment]
@mt I agree we should probably discuss in person

**Comment by huitema** [comment]
I don't see why we need to change the spec. The node proposes N connection ID, the peer chooses one of them. If the node wants a fixed length, it restricts itself to use proposing a fixed length.

**Comment by mnot** [comment]
Discussed in Prague; hum strongly supported closing with no action, but some interest in a new issue constraining to server preferred address (but will require substantial information, e.g., solid use case).
