### ISSUE TITLE
CID's should be compared in constant time

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#2477]
[If a CID can be seen or guessed, an attacker can make you decrypt garbage packets.  On-path attackers can see; nothing to do about that.  If the time it takes you to reject an invalid CID can be observed, an attacker can guess and check possible CIDs.]

On that account, it should be a requirement that CID's are compared constant time, otherwise they are easy to guess anyway.

_Originally posted by @mikkelfj in https://github.com/quicwg/base-drafts/issues/2441#issuecomment-464173546_

**Comment by MikeBishop** [comment]
However, if you have to be on path to observe processing time, this is moot.

**Comment by mikkelfj** [comment]
> However, if you have to be on path to observe processing time, this is moot.

You don't, because the endpoint cannot know what the correct path is before knowing the CID, assuming there is more than one possible path, as is usually the case.

BTW: there could be attacks on middle boxes that learn what valid CID's are, but do not compare these constant time. I'm not sure how effective that would be though.

**Comment by kazuho** [comment]
I think @mikkelfj is technically correct. A simple attack would be like the following.

Assume there's a server using an ordered list to maintain CIDs. When it receives a packet, it scans the list in ascending order until it finds a matching CID (or if reaches the end of the list without finding one).

An attacker can bisect the server to see which CIDs is active, by observing the difference in the latency of receiving stateless resets. This is much convenient than a brute-force attack that tries every possible CID to see if one is active.

If we need to be clear about the constant time requirement is a different question.

**Comment by mikkelfj** [comment]
I’m not sure it is worth reqiiring. Then we should also say constant time hash tables should br salted.

Note that popular Splay trees are vulnerable to manipulation.

Disabling Reset could be a recommendation if under attack.

**Comment by dtikhonov** [comment]
This is rather far-fetched.  This requirement does not belong in the spec.

**Comment by martinthomson** [comment]
The "secret" here is a connection ID.  Something we put in packets without encryption.

If the cost is that you can force a server to attempt to decrypt packets, that's relatively easy to do by other means.  If the point is to attribute that pointless work to others, that's maybe a tiny bit interesting as a DoS vector, but it seems to me like this isn't that useful a thing to document.

The underlying assumption here has always been that decryption, successful or otherwise, is cheap enough that an attacker ends up spending more resources in sending the packet than the defender does in discarding them.  That's not completely true as decryption isn't free, but the cost/benefit to an attacker is very low and - relevant to our current effort - it is extremely difficult to defend if you assume differently. From that perspective, I don't think we should do anything about this.

**Comment by ianswett** [comment]
+1 to Martin's suggestion to not do anything about this.

**Comment by janaiyengar** [comment]
I agree with @martinthomson that we've assumed decryption to be relatively cheap, and that being able to guess a CID is therefore not a particularly interesting attack.  I don't think this issue warrants any language in the spec.

**Comment by martinthomson** [comment]
Packet numbers cross paths, CIDs don't.
