### ISSUE TITLE
Define idle period for congestion control

### ISSUE THREAD

**Issue by pravb** [quicwg/base-drafts#2555]
Currently the recovery draft 19 requires the sender to either reducing the cwnd to initial cwnd OR pace the send after idle. Idle is defined as "it ceases to send data and has no bytes in
   flight" . This will mean that just a very small delay in the sending application thread will cause QUIC to reset its cwnd when not pacing. IMO we need to define an interval for this which could be a function of kGranularity or as PTO. FWIW in TCP the idle period for cwnd restart is defined as one retransmission timeout (reference https://tools.ietf.org/html/rfc5681 Section 4.1).

**Comment by ianswett** [comment]
However, this still has the problem that if I don't pace and I have a window of 100 packets, I can burst 100 packets into the network.  This seems suboptimal from both the sender and the network's perspective.

Now that I think about it, I think the concept of limiting the size of a burst is the key here, not so much idleness, and I think defining idle more accurately is both not necessary and likely to be difficult.  Ideally you would send no more than max(10, BW * kTimerGranularity) packets into the network at once.

**Comment by pravb** [comment]
@ianswett pacing or limiting burst is the right idea. TCP RFC limits the burst to IW but it says do that after an idle period of an RTO. Presumably the authors and community considered that period to be small enough that network capacity / conditions hadn't changed drastically. 

Implementation wise how would we do this without a timer? If not pacing, when would one decide to cut cwnd back to restart cwnd (say IW)?

**Comment by ianswett** [comment]
Your interpretation of RFC5661 looks correct and is different from what's in the QUIC recovery doc.  But the implications are that it's ok to send an unlimited sized burst into the network as long as you only drained the pipe very recently.  I think that recommendation is a poor one unless the window sizes are fairly small(in which case they'd be close to IW10 anyway).

The sender is bursting packets into the network, which previously did not cause loss because they were ack-clocked, but one or more buffers on the network doesn't have enough space for the full CWND.  It seems likely this could cause losses for other flows sharing the link as well.  This could happen frequently in HTTP applications such as DASH video playback.

NewCWV is already referenced for decaying CWND after idle.  I could change the text to say nothing about reducing CWND to IW upon full idle and instead say you shouldn't burst more than IW into the network at once ever, and senders may use pacing, ACK-clocking, and/or timers to accomplish that?

https://tools.ietf.org/html/rfc7661 may also be relevant to this topic?

**Comment by pravb** [comment]
I guess the bigger question is what are we attempting to document in this draft. Is it whats in the TCP standard RFCs OR what most current TCP implementations do OR what the Linux kernel implementation does? By documenting NewReno instead of CUBIC we've chosen to not document the state-of-the-art and erred on the side of simplicity. In the spirit of that I think handling idle period and app limited states are optimizations for better network citizenship on cetrtain type of networks and not a hard requirement.

For this particular issue I'd like to point out that the Windows TCP implementation has worked fine without handling the idle period (not capping cwnd burst and neither pacing). The idle cwnd restart knob in Windows is off by defualt and I believe Google TCP turns it off on Linux as well.

Yes RFC 7661 is relevant and I think I cited it on the application limited case handling issue. I think there is a fine balance between managing burst size and taking advantage of TSO like optimizations. For example in WAN and DC bulk flows it might better to burst higher than IW with TSO for CPU efficiency than to pace and on the Internet pacing might be better.  

But I like your direction on this since it sidesteps what is meant by "idle". How about framing it as a suggestion and not a requirement. Something along the lines of:

Bursts of more than IW into the network at once may cause losses. Implemementations should consider using pacing, ACK-clocking, and/or timers to minimize bursts.

Paging @janaiyengar to this issue as well.

**Comment by ianswett** [comment]
My goal is to document the best practices and reference existing RFCs whenever possible.  And yes, my understanding is that everyone disables slow start after idle, so I'd like to come up with something I think is more likely to be deployed.

When QUIC was started, Cubic wasn't an RFC, which is the other reason we documented Reno instead of Cubic, FYI.

I'll write up a PR based on your suggestion and hopefully we can get some text we all think is acceptable.

**Comment by janaiyengar** [comment]
RFC7661 is already cited in the section, and it was added there to defer to it so we didn't have to delve into details in this doc.

I think what we're really discussing here is whether we need the MUST in the sentence "When sending data after becoming idle, a sender MUST reset its congestion window to the initial congestion window".  I'm in agreement with what I'm sensing here -- that we don't need a requirement, but we can discuss the implications of various decisions here and current best practices.

Higher-level note, yeah, we always wanted to document current best practices, rather than what was in TCP or even linux TCP.  I think most things came from linux TCP because that was what we were familiar with.

FWIW, agreed that Cubic wasn't an RFC at the time, but it was close to becoming one, and we did discuss it.  We decided that it was too complex and adds a ton more complexity to this document. We wanted to have something simple but good enough that implementations could have as a starting point, and then move on to more esoteric algorithms as deployments needed.

(I'll disagree that Cubic is the best known CC at the moment -- unless you're talking about DC environments, it's not.)

**Comment by ianswett** [comment]
Thanks for the discussion, I updated #2605 based on this, though I'm a bit concerned that SHOULD is too weak in regards to bursts into the network.  Then again, if that's what Windows is doing, maybe we have to accept the reality of current deployments?

**Comment by mirjak** [comment]
Given that I think that the general guidance for QUIC is "use pacing", I think a "MUST reset to IW if not paced" is actually the right thing to do to support that pacing gets implemented with QUIC from the start.

**Comment by pravb** [comment]
@mirjak pacing may be implemented and controlled outside of the transport. I have two new concerns about text around bursting packets on network:
1. Many CDNs and edge deployments will tweak IW to be a higher value. In Windows TCP we allow config of up to 64 MSS. So if the network admin knows what they are doing and can swallow bursts then we shouldn't discourage the practice. 
2. UDP segmentation offload is reality now and for high throughput flows using hardware offload to reduce CPU will mean larger bursts trading off against pacing. We shouldn't preclude this either.

**Comment by mnot** [comment]
Discussed in Montreal; people to review the PR.

**Comment by larseggert** [comment]
Discussed in Cupertino, @pravb to review #2675 and determine whether that addresses (or partially addresses) this issue.

**Comment by janaiyengar** [comment]
@larseggert @mnot: This issue was supposed to be closed by #2675, but it was waiting for feedback. It's been long enough -- can we close this issue?
