### ISSUE TITLE
Is path validation a SHOULD or a MUST -- pick one!

### ISSUE THREAD

**Issue by igorlord** [quicwg/base-drafts#2580]
Section 9 (Connection Migration) says:

> [...] an endpoint SHOULD perform path validation (Section 8.2) if it detects a change in the IP address of its peer.

Section 9.2 (Responding to Connection Migration) says:

> In response to such a packet [a packet from a new peer address containing a non-probing frame], an endpoint MUST start sending subsequent packets to the new peer address and MUST initiate path validation (Section 8.2) to verify the peer’s ownership of the unvalidated address.

So:

1. Is performing path validation (Section 8.2) a SHOULD or a MUST?  I would prefer "a MUST, unless the endpoint has other means validate the validate the new path"

2. If sending subsequent packets immediately a MUST?  Not even a "MUST after validation"?

**Comment by larseggert** [comment]
This is almost an editorial issue, except that we need to agree on MUST vs. SHOULD. Please comment, folks.

**Comment by ianswett** [comment]
I think Igor's suggestion of "a MUST, unless the endpoint has other means validate the validate the new path" seems sensible, but either way this needs a PR.

**Comment by janaiyengar** [comment]
I like @igorlord 's suggestion, but I suspect @erickinnear's upcoming PR that addresses #2582 (and #2579) will cover this too. Let's wait for that one first, since it should have more context and rationale.

**Comment by mikkelfj** [comment]
I intuitively like MUST, but what would the implications be of SHOULD? Would it broaden the attack surface? Probably. Implications of MUST: could an attacker force validation work by injection? How bad could that get?

**Comment by erickinnear** [comment]
I think elsewhere we had a "MUST, unless" for some of this, so sticking with that would be great (to second Igor and Ian's comments).

Re: SHOULD, agreed that it would potentially broaden the attack surface, since some of the mitigations (the reason for the MUST in 9.2) rely on validation being performed.

The attacker can cause you to generate validation packets by injection, but I think the discussion in #2582 should attempt to consider the implications of what happens when you end up validating on every incoming packet (the worst possible case here, and definitely a good thing to think about).

My intent here is to put the non-editorial changes in a small PR to get the normative language right and then potentially follow with a larger PR that's (hopefully) purely editorial that rearranges these to get rid of some of the confusion around having requirements split across the sections.

**Comment by larseggert** [comment]
FWIW, a "MUST, unless" is exactly what a SHOULD is

**Comment by igorlord** [comment]
@larseggert, SHOULD is a lot weaker than "MUST, unless" because SHOULD allows skipping the behavior even if the "unless" part is not performed.

"MUST A, unless B" is a syntactic sugar for "MUST A or B".

**Comment by larseggert** [comment]
From 2119:
```
3. SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.
```
And those circumstances should be discussed, which is the "unless" part.

**Comment by igorlord** [comment]
@larseggert, I think is could be taking us a bit on a tangent, but by understanding of the quoted description of SHOULD is that "valid reasons [..] to ignore" may exist but not enumerated in the draft.  In "MUST A, unless B", B is explicitly named and hence this becomes "MUST A or B".
