### ISSUE TITLE
Bring back AEAD_AES_128_CCM_8 now that we pad the plaintext

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/base-drafts#2581]
As discussed in #2019, we did not originally have a good way to make AEAD_AES_128_CCM_8 work in QUIC, because it needs a 16 byte sample for header protection but only produces an 8 byte auth tag. However, since then we have merged #2030, and it's therefore easy to pad short packets by 8 extra bytes when using CCM_8. There might be QUIC use-cases that could benefit from the shorter tags, and it would be nice to have QUIC support all the original TLS 1.3 cipher suites.

**Comment by LPardue** [comment]
+1

CCM_8 is big in environments like broadcast production

**Comment by mikkelfj** [comment]
This just adds an odd error-prone special case for padding, and the key benefit of being short is lost on short packets due to padding.


________________________________
Fra: Lucas Pardue <notifications@github.com>
Sendt: tirsdag, april 2, 2019 1:20 AM
Til: quicwg/base-drafts
Cc: Subscribed
Emne: Re: [quicwg/base-drafts] Bring back AEAD_AES_128_CCM_8 now that we pad the plaintext (#2581)


+1

CCM_8 is big in environments like broadcast production

**Comment by kazuho** [comment]
I think we can accommodate this in QUIC v1.

The change has zero impact on implementations not supporting CCM8. Code can be left as-is.

Specification-wise the required change would be to alter the definition of minimal payload size from 4 to `pn_sample_size - aead_tag_size + 4`).

**Comment by kazuho** [comment]
> the key benefit of being short is lost on short packets due to padding.

I disagree. It's only the very short packets that do not have the benefit. Longer packets do not require additional padding, and will benefit from the use of the shorter tag.

**Comment by martinthomson** [comment]
I don't think that we need this.  The reasons offered thus far amount to "because we can".  I'd like to see some analysis suggesting that shorter authentication tags are OK in the general case.  Or text explaining constraints on deployments that choose to use a shorter tag.

I understand the benefits of CCM over GCM; I understand that this includes an ability to have a shorter tag, unlike GCM which fails badly.  I understand the desire to save bits.  But it isn't really that many bits, and the shorter tag changes the odds of an invalid packet being accepted fairly significantly.

**Comment by DavidSchinazi** [comment]
@martinthomson can you elaborate on what makes QUIC different from TLS that suggests AES_128_CCM_8 is useful in TLS but not in QUIC?

**Comment by RyanAtGoogle** [comment]
It's worth remembering that QUIC packet sizes are (typically) smaller than TLS record size which means that the consequences of saving bytes are larger in QUIC than in TLS.

**Comment by ekr** [comment]
Well, we generally discourage the use of CCM_8 in TLS as well. We mostly
only added it for IoT purposes.

**Comment by DavidSchinazi** [comment]
@ekr QUIC is also applicable to IoT, CCM_8 should be supported but discouraged here as well.

**Comment by janaiyengar** [comment]
Is there a strong argument to diverge from existing TLS practice here?

**Comment by mikkelfj** [comment]
CCM_8 is better suitet for a separate QUIC version for IoT where header protection and padding is also dropped and where the traffic volume is low. A cheaper habdshake would also be needed.

Someone said CCM_8 is commonly used with video AFAIR.

**Comment by DavidSchinazi** [comment]
@mikkelfj I don't think encouraging protocol fragmentation is a good idea. The reason TLS 1.3 has CCM_8 is to allow IoT use-cases to use TLS 1.3 instead of making them develop new protocols. The same argument applies to QUIC.

**Comment by ianswett** [comment]
Q: Should we allow it for QUIC, but not allow it for HTTP/3?

**Comment by mikkelfj** [comment]
No, the application layer shouldn't deal with transport security. If the security properties changes, it should be a new QUIC version.

**Comment by DavidSchinazi** [comment]
I agree with @mikkelfj on this one. HTTP/2 doesn't disable CCM_8 when run over TLS 1.3.

**Comment by mikkelfj** [comment]
But if I argue that CCM_8 changes security properties, you might disagree since that would move CCM_8 to a new QUIC version.

**Comment by ekr** [comment]
@DavidSchinazi this doesn't seem like a very persuasive analogy, given that HTTP/2 has a long list of rules about disabling ciphers that were present in TLS 1.2:

https://tools.ietf.org/rfcmarkup?doc=7540#section-9.2.2

The reason that it doesn't have that in TLS 1.3 is because (1) TLS 1.3 post-dates HTTP/2 and (2) the suites were chosen according to the same principles

Second, as a practical matter, most browsers do not support CCM_8, and I suspect that will continue to be true for most stacks, partly because performance is not awesome (as it requires computing CBC). If, as @RyanAtGoogle implies, we want to have a cipher with a shorter authentication tag (I'm undecided on this topic myself at present) for general use then we should consult CFRG for one, rather than just use the one that happened to be the one that IoT devices supported.

**Comment by DavidSchinazi** [comment]
I would personally have preferred to include AES_128_CCM_8 in the QUIC spec to have parity with TLS 1.3, but I can live with the text from #2743 because that allows someone to write a one-page spec on how to use AES_128_CCM_8 in QUIC without risking interoperability issues. I'm OK with closing this issue with no further action at this point.
