### ISSUE TITLE
Use short headers for stateless reset

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2599]
We don't want to prohibit the use of long headers in other versions - in case they want to share the stateless reset design, but there is no sense in sending long headers.

**Comment by mikkelfj** [comment]
While I agree with the issue, the PR says that other versions might want to reset with a long header and therefore the receiver must inspect long headers anyway. I can see this, but given that, I think it is pointless to require the current version to only send resets for short headers. A general advice ought to suffice since the MUST is not enforceable anyway.

**Comment by martinthomson** [comment]
The requirement exists to protect those packets from detection.

**Comment by mnot** [comment]
Please don't close issues until AFTER consensus is declared (not just called).

**Comment by ianswett** [comment]
I suspect Martin was confused because this issue was tagged has-proposal 15 days ago.

**Comment by mnot** [comment]
Right. The trigger is `has-consensus`, not `has-proposal`.

**Comment by ianswett** [comment]
But it's understandable Martin would have assumed this was one of the issues that was sent out in the batch of issues a week and a half ago, given this has been tagged with has-proposal for 15 days.
