### ISSUE TITLE
Define "under-utilization" of cwnd

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#2630]
#2605 changed the discussion in recovery from idle behavior and app limited periods to  periods of under-utilized cwnd. This is great, but a precise definition of when the cwnd goes under-utilized is still missing.

**Comment by gorryfair** [comment]
Defining "under-utilised cwnd", seems conceptually the right thing, but we struggled with that term and the term "fully utilized the congestion window" when writing RFC7661, because ACKs can arrive in bursts and apps can do their work in bursts: Does that mean it's more than some threshold for some period time?

**Comment by janaiyengar** [comment]
@gorryfair : That is a question. Maybe we can get away from that by saying that a sender only increases its cwnd if it knows that it was fully utilized since the last cwnd change? Meaning that at some point since the last cwnd change, inflight >= cwnd happened at least once.

I have a separate question, one that was being discussed in #2554, and I think is still left open. If we need the entire cwnd to be used before increasing it, we lose out on 1 RTT of growth during slow start. Both Windows and Linux TCP compensate for this by doing something like increase it when > 1/2 cwnd is used... we need to write something here that's at least as performant, and not just "when inflight >= cwnd".

**Comment by janaiyengar** [comment]
@pravb, thoughts?

**Comment by gorryfair** [comment]
This seems to be digging in the correct place. I think we would agree the aim of some form of cwnd-validation is to stop cwnd growth when there is no growth of inflight data by the upper layer. And I think we'd agree tussle comes when the CC is trying to expand the cwnd - because the upper layer has more data to send, but that doesn't mean cwnd was necessarily fully utilised last RTT.

When would in-flight > cwnd ?

**Comment by ianswett** [comment]
@janaiyengar Good point about the in_flight > 1/2 CWND check in Linux.  In BBR, that only applies to the first doubling of IW, and after that it's fully bandwidth based, FWIW.

We could add a similar constraint that this rule can be applied when the window was not fully used at the time of sending, but was at the time of acknowledgement as long as the window is < 2*IW?

One clear goal of mine is I don't want the handshake alone increasing the congestion window(assuming IW10 and a moderately sized handshake).

**Comment by maolson-msft** [comment]
Putting this discussion into a concrete algorithm:

-Keep an in-flight high watermark, InFlightHigh, that's reset on each CWND change.
-When considering growing the CWND, only let it go as large as InFlightHigh*2.
-Justification for the "*2": it allows base-2 exponential growth, which is the fastest growth we ever want.

**Comment by pravb** [comment]
Possible expiration events: persistent congestion, ssthresh changes, app idle.

**Comment by ianswett** [comment]
Discussed in London, we'd like to avoid specifying this in pseudocode and the exact math, as it may be implementation dependent, but instead focus on improving the existing text.
