### ISSUE TITLE
Packet-threshold loss detection poorly interacts with packet coalescing

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#2653]
Packet threshold uses difference in packet number as a proxy for datagrams, which is not true with packet coalescing. 

Fortunately, coalescing is only used during the handshake, and packet-threshold detection is not very useful for Initial and Handshake packets. One proposal is to not use packet-threshold detection for detecting losses of Initial or Handshake packets.

**Comment by ianswett** [comment]
Can you be more specific about the issue you're seeing and how packet coalescing is relevant, because I don't understand the issue.

If you were allocating packet numbers from a single space when doing multiple PN spaces, then unless you adjust for that, you could become very sensitive to reordering, but that is implementation specific and doesn't involve coalescing.

We could disable packet threshold for Initial and Handshake PN spaces, and it likely wouldn't matter during the handshake since it's rare to have 3 packets outstanding at once anyway, so time threshold is likely to kick in sooner.

**Comment by janaiyengar** [comment]
Yes, I think you're right that there's no issue here. Having separate packet number spaces makes this concern moot.
