### ISSUE TITLE
Prohibiting server-initiated bidirectional streams for h3

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2711]
> HTTP/3 does not use server-initiated bidirectional streams; clients MUST omit or specify a value of zero for the QUIC transport parameter initial_max_bidi_streams.

I don't think that we need the MUST here.  An extension might want to use those streams.  It should be enough to note that these aren't used.

**Comment by LPardue** [comment]
Would thescope of this change include adding text on how core HTTP/3 implementation should treat the reception of data on these streams?

**Comment by martinthomson** [comment]
It probably has to, yes.  That's something we generally do with most of our MUST statements anyway.

**Comment by kazuho** [comment]
This might be a transport question, but how should a client respond to a server trying to open a server-initiated bidirectional stream?

Assuming that the client's initial_max_streams_uni is zero, a server would send a STREAMS_BLOCKED frame. In response, the client would send a MAX_STREAMS frame with the value set to zero. However, IIUC, this MAX_STREAMS frame merely indicates that the resource is temporary unavailable. That means that the server would be blocked.

To rephrase, the transport does not provide a way for an endpoint to reject a stream, without letting the peer to actually send a STREAM frame. Are we fine with that?

If we think it as a problem, maybe we should change the definition of initial_max_streams TP. For example, we could specify that the omission of the initial_max_streams TP indicates rejection of the corresponding type of streams being opened (instead of interpreting the omission as "zero").

**Comment by mikkelfj** [comment]
I don't think the transport should police what streams are opened beyond managing resource consumption. It may well be, in some other app protocol, that a server is free to open bidi streams, but only if they start with a certain header, or none at all. The  app protocol should make both endpoints agree and what is permitted and police accordingly. An application layer could have credits similar to MAX_STREAMS to permit opening certain streams with or without a header. The transport need not deal with this.

**Comment by martinthomson** [comment]
Right.  The transport only needs to concern itself with policing stream limits.  The question here is more about how the use of h3 constrains future extension.  As Mikkel says, if there is a use for the server-initiated streams, we shouldn't constrain that.

**Comment by MikeBishop** [comment]
On the other hand, an extension could modify this requirement, too.  Much of what's in the base spec is for the unextended protocol, and I think this is an instance of that.

However, this is a MUST which we don't permit the server to enforce, which argues for making it a SHOULD instead.  Maybe SHOULD omit/zero, "unless an extension which defines their use is being offered."?

**Comment by mikkelfj** [comment]
MUST not accept any bidirectional streams that are not explicitly permitted by extensions.

I'm not sure about stream header formats here - it would be easy to create conflicts across extensions.

**Comment by vasilvv** [comment]
I'd suggest we define those to be the same format as client-initiated ones, and use a column in IANA registry for listing which party can be the initiator.  This way, extensions get a uniform way of defining those streams.

**Comment by MikeBishop** [comment]
Discussed in London; spec shouldn't prohibit or require any particular value, but should say that these streams have no meaning in the protocol and can only be used by negotiation.  If you get one without having negotiated their use, it's a connection error.
