### ISSUE TITLE
Unclear conditions in long header descr.

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#2719]
https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#long-header

> Long headers are used for packets that are sent prior to the establishment of 1-RTT keys. Once both conditions are met, a sender switches to sending packets using the short header (Section 17.3). 

What are these "both conditions"?

Also, can there be made a clear statement such that: all packets prior to Application PN space use long headers, and all packets in application PN space uses short headers?

And, the table of frames with section references, would it make sense to add PN space columns with an X where a frame is applicable?

**Comment by MikeBishop** [comment]
Multiple issues listed here.  Please consider opening separate issues rather than lumping them all together.

(1) This is old language we agreed to in Chicago.  The requirement to shift to short headers was 1-RTT key availability and version agreement, to accommodate versions where the final keys might be available immediately (i.e. out-of-band agreement) but version negotiation still had to complete.

However, that's a principle for the invariants or such a version, not a requirement of this QUIC version -- and the version negotiation language this referenced is gone now.

(2) What is "Application PN space"?  0-RTT and 1-RTT?  If so, then no -- 0-RTT packets carry application data but are long-header packets.

(3) Unrelated editorial suggestion -- please open a separate issue.

**Comment by mikkelfj** [comment]
(3) see  #2721
