### ISSUE TITLE
Coordinating spin

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2763]
When multiple connections share the same network path or multiple connection IDs are used for the same path, using the spin bit is complicated by the difficulty in correlating forward and reverse flows.  There is currently text that uses RFC 6919 language in the draft recommending coordination of the spin to avoid this problem.

However, as [some have observed](https://github.com/quicwg/base-drafts/pull/2751#pullrequestreview-244603953), this coordination seems difficult and therefore unlikely.  It also creates a strong signal that indicates that all the connections on the path are terminated at the same endpoint on both ends.  Maybe we don't want to be generating that signal.

Also, because this coordination can't be guaranteed, the on-path observer is forced to build code for correlating/segregating measurements by connection ID in the case where there is no coordination.

Maybe it's best just to remove this recommendation entirely.

**Comment by kazuho** [comment]
+1 to removing the recommendation, or changing the statement to just a caution (e.g., if you are to coalesce connections that spin, then you'd better be aware of ...).

> It also creates a strong signal that indicates that all the connections on the path are terminated at the same endpoint on both ends.

FWIW I am not sure if I agree with this observation. IIUC, the connections sharing a 5-tuple will be terminated by the same endpoint on both ends; it is impossible for a middlebox to coalesce multiple QUIC connections. It is impossible because CIDs can change mid-connection, and a middlebox cannot determine to where the packets containing the new CID must be sent.

**Comment by martinthomson** [comment]
There definitely needs to be a degree of coordination between the middlebox and the endpoints, but that doesn't mean that you can't use something like the quic-lb stuff on either end (or both ends).

**Comment by mikkelfj** [comment]
Yes, I think it is better to remove that recommendation, but perhaps replace it with a note to observers.
