### ISSUE TITLE
Skipping packet numbers

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#287]
According to @marten-seemann, they occasionally skip a packet number.  This might mess with congestion control if it is done too often, but it seems like a perfectly reasonable thing to do.  The draft currently forbids this.  Maybe it shouldn't.

**Comment by ianswett** [comment]
The sender is skipping packet numbers and also doing congestion control, so it shouldn't have any adverse side effects, since it knows which numbers were skipped.

Where is it forbidden in the draft?  In 7.2 it says "A sender MAY intentionally skip packet numbers to introduce entropy into the connection, to avoid opportunistic ack attacks."

**Comment by martinthomson** [comment]
Nope, you are right, I misread.
