### ISSUE TITLE
Avoid using Public Reset where possible

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#289]
The draft currently says:

> In this case, an endpoint SHOULD send a Public Reset packet to indicate the failure. 

(This is in the context of discovering that the MTU is too small.)

Given that it doesn't take much to send an authenticated CONNECTION_CLOSE in a packet that won't risk breaking even the minimum IPv4 MTU, I think that this suggestion too much.  I would change this to "treat this as a connection error of SOME_ERROR_CODE" either defining a new MTU_TOO_SMALL error code, or reusing an existing one.

**Comment by RyanAtGoogle** [comment]
Completely agree. I think Public Reset should be used as sparingly as possible. Perhaps only the case when a server receives a packet for a connection ID it has no state for.

**Comment by mcmanus** [comment]
sorry about the dup - it seems I still have trouble mining the github issue system effectively.

While we're at it the language in 6.4 that allows an endpoint to send a public_reset at any time to abruptly terminate an active connection should be significantly tightened or removed.. we don't want this to become the mechanism to ending things.

**Comment by ianswett** [comment]
Agreed, I think it's important to clarify when connection closes should be sent and when public resets are sent.  I think there's a lot of agreement around this, but there's not much text clarifying it yet.

The rules on processing them could be clarified as well.  ie: Should public resets before handshake completion be ignored, because there's no reason to ever send them?
