### ISSUE TITLE
Why is Min RTT kept for the connection lifetime?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/base-drafts#2908]
Section 5.2 of draft-ietf-quic-recovery:

(1)   the minimum value observed over the lifetime of the connection

- Why a minimum specified over the entire lifetime? There are paths where the initial RTT may the lower, I am unable to see why that artefact should have a long-term impact on the connection. Even if it is just a change in traffic sharing the path’s bottleneck, it still isn’t something that needs to have impact for the lifetime of a connection. Can’t we decay the value somehow, so that it reflect the recent min_RTT.

draft-ietf-quic-recovery, and here is why a smaller than current min_RTT is problematic:
(2)  MUST NOT apply the adjustment if the resulting RTT sample is
      smaller than the min_rtt.  This limits the underestimation that a
      misreporting peer can cause to the smoothed_rtt.

- How do I understand this works with paths exhibiting varying path delay?  I still can’t fathom what will happen when the lowest RTT in recent time is much larger than the min_RTT, because the RTT floor has increased (e.g. because of a change at L2). I see some rather strange behaviour in traces of QUIC when there is large long-term jitter. At present, I think this results in making inappropriate adjustments?

**Comment by ianswett** [comment]
min_rtt is used to reject implausible SRTT samples due to large max_ack_delays, which we can clarify.  It should be over the lifetime of the path, not the connection.  We could clarify what it means to reset a context, but assuming a new context is easier to reason about.

What if min_rtt decreases or increases?  Decreases it should follow, Increases causes QUIC to loosen the sanity check.

**Comment by erickinnear** [comment]
(Editorially I would specify a congestion control context rather than a path)
