### ISSUE TITLE
Does any portion of the QUIC framing require 4 byte alignment?

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#292]
@martinthomson Wrote up a public header proposal that implies 4 byte alignment is an important goal of the public header.

Is it necessary, as it does constrain the design space substantially?  And if there are environments it's necessary, is it only a requirement for non-endpoint devices(aka middleboxes), so only applies to the non-protected portion of the packet.

**Comment by martinthomson** [comment]
The answer is no.  That was an emergent property only.

**Comment by janaiyengar** [comment]
I don't think we need this. I'd like to close this issue since I didn't / don't see anyone asking for it.

**Comment by ianswett** [comment]
I misinterpreted Martin's proposal as asking for it, so closing this.

**Comment by martinthomson** [comment]
For the record, since the person who reported this to me didn't follow up as I requested they do...

At the meeting in Chicago, I was approached by someone (and my apologies to this person for forgetting their name), who said that they do hardware implementations of protocols and not having 4 octet alignment would be a huge hassle for them.  I'm not reopening the issue, but I wanted to record this as a data point in case this comes up again.
