### ISSUE TITLE
Confused about Fixed Bit in Version Negotiation Packet

### ISSUE THREAD

**Issue by Ainiroad** [quicwg/base-drafts#2995]
Fixed Bit Must set to 1:
> Fixed Bit:
The next bit (0x40) of byte 0 is set to 1. Packets containing a zero value for this bit are not valid packets in this version and MUST be discarded.

the first byte in Version Negotiation Packet
```
+-+-+-+-+-+-+-+-+
|1|  Unused (7) |
```
there is 7 bits unused, including Fixed Bit.

> The value in the Unused field is selected randomly by the server. Clients MUST ignore the value of this field. Servers SHOULD set the most significant bit of this field (0x40) to 1 so that Version Negotiation packets appear to have the Fixed Bit field.

It's said that `Clients MUST ignore the value of this field.` and `Servers SHOULD set the most significant bit of this field (0x40) to 1`. 
If Client must ignore the value(including Fixed Bit), why server should set Fixed Bit?

I'm confused about the describe. I think maybe it want to express it like this:
> Clients MUST ignore the value of this field *except Fixed Bit(0x40)*. Servers SHOULD set the most significant bit of this field (0x40) to 1 .......

Do I have any misunderstanding? thanks a lot

**Comment by mikkelfj** [comment]
A version negotiation packet is not version specific so the rule you refer to does not apply.

**Comment by Ainiroad** [comment]
> A version negotiation packet is not version specific so the rule you refer to does not apply.

I'm confused about the describe.
If Client must ignore the value(including Fixed Bit), why server should set Fixed Bit?

**Comment by martinthomson** [comment]
>  If Client must ignore the value(including Fixed Bit), why server should set Fixed Bit?

Because this might allow us - in future - to depend on that behaviour.  We might assign semantics to a non-zero value.  A client that doesn't understand that bit will continue to consume the packet and ignore the semantic difference.  If servers set the value any way they please, then we can't.  (It's a SHOULD, so we won't be able to rely on it exclusively, but we might still be able to do something with it.  That said, I consider it a write-off, but this is a general protocol design hygiene matter.)

My proposal for this issue is to do nothing.  This is a little complex, but I don't think that the required behaviour is unclear in any way.

**Comment by Ainiroad** [comment]
Thanks
