### ISSUE TITLE
Encrypting Retry token

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3274]
In Singapore, we reached an impasse regarding the use of encryption on Retry.

From that discussion, there were two outcomes considered:

* "encrypt" using a fixed key and nonce and don't encrypt the token; put the original destination connection ID in the AAD along with the entire packet

* encrypt the token using the fixed key and a nonce that takes the first 8 bytes of the original destination connection ID; the AAD only includes the connection IDs and version

The first can be reduced to running GHASH with a fixed XOR on the final tag if you really want to save effort.  I've implemented and measured that.

The second can be implemented naively, just by building a new AES key for every record.  That's not terribly slow at 2.8x slower.  With some nasty tricks, I was able to get the AES version under 1.7x slower.  Given the relative cost of these functions, I think that this is an acceptable cost.

There's no guarantee that this is correct - I haven't even checked that these programs produce the right output, but the count of operations is approximately right, so I'm posting this issue.  My code can be found at [martinthomson/quic-retry-tag](https://github.com/martinthomson/quic-retry-tag/blob/master/bench.c) in case reproduction or validation thrills you.

Here's the output of a sample run on my old machine with about 1Mb of Retry packets fed through the different implementations, which takes about 32 seconds to complete:

```
Measuring best of 1000 iterations
ghash:          22450242
aes_gcm_slow:   60070152
aes_gcm_fast:   35240211
```

Now, obviously this is a microbenchmark.  The rest of the cost will be elsewhere, but I tried to isolate the variable.  Hopefully this helps the decision-making process.

**Comment by martinthomson** [comment]
Since I did this, I've realized that even this was an overly pessimistic outcome.  By precomputing the XOR stream for CTR protection, it should be possible to make an even faster version of the protected form here.

The result should be to narrow the gap between the GHASH-only and encrypted variant further.  The difference should be limited to performing an XOR with a fixed value and a single AES operation (which in my experience is marginally cheaper than an extra GHASH operation, though the addition of ODCID to the AAD is rarely a full block, so it's hard to predict the exact outcome).

**Comment by kazuho** [comment]
@martinthomson 
> Since I did this, I've realized that even this was an overly pessimistic outcome. By precomputing the XOR stream for CTR protection, it should be possible to make an even faster version of the protected form here.

I might be missing something, but I wonder if you can precompute the XOR streams for all the nonces (2<sup>64</sup> bits).

**Comment by kazuho** [comment]
Regarding the numbers, Martin, thank you for collecting them.

I think that the benchmark confirms our expectation that the cost of running AES (based on fixed key, with different nonce) does not matter when a conventional CPU with AES offloading is used.

Though I think the other question might be if we can require all the DDoS mitigation boxes to be capable of running AES fast.

**Comment by martinthomson** [comment]
> I might be missing something, but I wonder if you can precompute the XOR streams for all the nonces (2<sup>64</sup> possibilities).

Oh, and I realized again why I didn't do that yesterday: 2<sup>64</sup> lots of precomputation is a little too much :)  Forget that bit.  The numbers are basically correct.

**Comment by martinthomson** [comment]
Here are the results from a different system (ignore absolute values and concentrate on relative values):

```
Measuring best of 1000 iterations
ghash:           5825976
aes_gcm_slow:   18750874
aes_gcm_fast:    8619132
```

**Comment by martinthomson** [comment]
From @huitema:

> I went on to compare the time to encrypt 64 bytes versus the time to just authenticate 64 bytes. Results are below for two implementations of AES128 GCM, one from OpenSSL crypto library and another from Windows Bcrypt library -- both measured using 64 bit code on my Windows laptop:

   | encrypt | decrypt | authenticate | verify
--  | -- | -- | -- | --
bcrypt  | 0.35751 | 0.22602 | 0.24687 | 0.20189
openssl 1.1.1c | 0.30211 | 0.23956 | 0.24296 | 0.23926

> The times are measured here in microseconds -- these are the average on 100,000 operations. We see that the times are fractions of microseconds in both cases. The encryption operation is more expensive than a simple authentication, 45% more with brcrypt, 24% more with openssl. The decrypt operation is 12% more expensive than the simple authenticate with brcypt, almost the same with openssl.

**Comment by DavidSchinazi** [comment]
These results are making me lean towards encrypting the token using the original connection ID as a nonce, but I don't feel overly strongly. I'll let folks share their thoughts here and if I don't hear back I'll add encryption to #3120.

**Comment by martinthomson** [comment]
It's possible that the values @huitema produced for just authentication are high.  Most GCM implementations will still run the AES operation necessary to calculate the mask for GHASH.  With a fixed key and nonce, that operation can be replaced with a simple XOR.  Doing that additional optimization is not obvious, and it requires breaking the AEAD box open, but I expect that this will happen if implementations REALLY care about every cycle.

That would increase the difference a little, maybe as much as my 1.7x (or 1.5x on the newer CPU).

**Comment by ekr** [comment]
I think at this point we need to see some data that supports the argument that encrypting the token is too slow. @nibanks, i think this was your view?

**Comment by dtikhonov** [comment]
What about the cost to the recipient of the Retry packet?  Currently, it is as simple as [looking up the token in a hash](https://github.com/litespeedtech/lsquic/blob/7ee4152504cba5b0a4b79ed9eab2cf8134128975/src/liblsquic/lsquic_engine.c#L1211).  IIUC, encrypting the token would replace the hash lookup with a decryption operation?

**Comment by ekr** [comment]
This seems like an insignificant cost, given that any successful QUIC
connection will involve quite a lot more cryptography.

**Comment by nibanks** [comment]
I'm working with our hardware vendor that does DoS mitigation for Azure. Give me a little time and I'll try to get back to you with data.

Also, as far as the cost to the client for Retry, IMO, the higher the better. The goal in this scenario is to make it more expensive for attackers who are spamming initial packets. For a normal client creating a single connection, the cost is insignificant as ekr points out.

**Comment by nibanks** [comment]
Here's a quote from our hardware partner:

> Here's some preliminary numbers. Due to code and library complexities, my team could not do the AES testing, but we could generate some results with the ghash.
> 
> The main thing is, encryption vs no encryption.
> Using no encryption as base (1x),  with ghash calculated, the CPU usage is roughly ~2.5x higher.
> 
> And if we expect AES to be 1.7x to 2.8x slower than ghash, we're looking at 4.25x to 7x slower for no encryption vs AES encryption.

And a bit more details in follow up:

> Again, these are preliminary numbers, and since we use ghash as benchmark base, the factor with different cpu generation & AES support is a little bit reduced here...
> 
> And, of course, the code is not tuned to the optimal, as we just took from the libraries mentioned by the link. (And I don't know how much of room left to tune the ghash & aes)
> 
> Attached is a little bit more details:
```
No ghash
------------------------------------------------------------
CPU Usage
Data1   14%   12%   11%   14%   12%

Port   InPPS   InBPS   OutPPS   OutBPS   
--------------------------------------------------------------------------
1   21738.64   22651666.98   0.00   0.00  
2   0.40   23.98   21738.64   22651666.98  

Ghash
------------------------------------------------------------
Data1   21%   29%   26%   27%   30%

Port   InPPS   InBPS   OutPPS   OutBPS  
--------------------------------------------------------------------------
1   20850.42   21725742.72   0.40   23.98   
2   0.40   23.98   20850.02   21725718.74  
```

I'm still of the opinion that, since the Retry packet is almost purely a DoS mitigation mechanism, our view should be what's the absolute simplest design we can take and still get what's absolutely necessary, not nice to have; instead of what else can we squeeze into this feature and hopefully not make it "too expensive".

**Comment by janaiyengar** [comment]
I'm in agreement with @nibanks. My interest here is to detect corruption of Retry packets, and a ghash (equivalent) is adequate. Everything else is a nice to have... and I don't care much for these.

**Comment by huitema** [comment]
I think I agree with Nick's reasoning. We started this issue by looking only at corruption during transmission. If we focus on that, a simple checksum would be sufficient. We can now start spin-bitting the checksum: crc64, fnv1a, 0-keyed aesgcm, md5... In fact, for curiosity, what is the spec of ghash?

**Comment by DavidSchinazi** [comment]
@huitema I don't think we need to bikeshed the checksum. We already agreed in Cupertino that we'd use GMAC (which some people seem to call GHASH apparently?) which is equal to AES-128-GCM with an empty plaintext.

**Comment by pravb** [comment]
I too think anything more than a checksum is unnecessary here. For a corner case scenario where there is NATting, we should not make the common case expensive. Given this is a DoS protection scenario when the system is deemed to be under attack, the mechanism we pick must be the least CPU intensive. My vote is to just keep simple checksum. Anything more is unnecessary because no need has been demonstrated for it.

**Comment by ianswett** [comment]
Agreed, let's stick with a checksum(GMAC/GHASH) as agreed in Cupertino

**Comment by mikkelfj** [comment]
If it's not clear, GHASH is the underlying hash algorithm for GCM and addition to the AES encryption track, but it somehow needs a key and a way to specify content and somewhere to place the result. GCM provides the framework for that hence GMAC is additional authenticated data without encrypted plaintext. Since there is no encryption in GMAC, GMAC is essentially GHASH, but with a clear way to specify the input/output parameters. There is probably an extra AES block encryption in GMAC to derive the GHASH key, and possibly an extra AES block encryption on the output, compared to raw GHASH, but I do not remember exactly.

**Comment by mikkelfj** [comment]
Using raw GHASH over GMAC would avoid the need for an AES module in hardware and only require carryless multiplication (CLMUL) for efficient operation, but I can't imagine where that case would be very relevant. Even on low-end microcontrollers it is more likely you have SHA-256 and AES hardware than CLMUL, at least for now. From that perspective Poly1305 would be more efficient, but given the nature of Retry and the dependence on AES-GCM elsewhere in the protocol, GMAC or GHASH makes more sense. GMAC is much simpler than GHASH because it can use existing libraries. If GHASH were to be used directly one would have to ensure that it is safe in the applied context and with the supplied key whereas GCM is well understood even if it costs a few block encryptions extra.

**Comment by martinthomson** [comment]
As the PR proposes, GMAC is what we are using. A simple implementation can then just use GCM. Someone looking to save one AES operation can run GHASH with an XOR.

This saves on the number of primitives, and for someone willing to build silicon, it can be implemented fairly efficiently.

There is some odd middle space with software implementations on low end hardware that might be a little worse off, but they win because they need fewer primitives. A low end device probably needs external help with DoS, so maybe we can say that this is a net win.

To be clear,  Nick's situation isn't ideal either. Implementing GMAC in hardware is certainly not free, falling back to software is not fast, and this style of standalone DoS protection is otherwise relatively simple. But there are a number of competing concerns that need to be balanced.

**Comment by mikkelfj** [comment]
I don't think you can avoid the AES for GMAC, at least not if both endpoints are to verify the MAC. This is because GCM first receives a "master" key which it then splits into two keys, one for encryption and one for GHASH. This key split is done with an AES operation. So unless both endpoints agree on the GHASH key directly, you need to use AES to derive the GHASH key.

**Comment by mikkelfj** [comment]
I'm not sure if it is safe to use a fixed key for GMAC because the collision restance of GCM is the same as for GHASH, which limits traffic to roughly 2^32 bytes and places requirements on non-reuse.

**Comment by martinthomson** [comment]
Yes, this is not "secure" in the sense that it would meet IND-CCA.  After all, we are publishing the key in an RFC.  The point is to reduce this to a checksum.

The arguments about "encryption" all amount to a desire to make accessing the Retry more difficult for a casual observer.  Someone with a copy of the RFC will obviously have no trouble.

**Comment by kazuho** [comment]
My +1 goes to just doing GMAC, due to the reasons others have laid out.

I'd also note that it is unlikely that middleboxes will ossify on the fact that the values of the token fields in Retry and Initial packets are equivalent, based on the behavior those developers see on the wire. This is because Retry is expected to be used *only* when there is an attack. Or, if those developers read the spec, the token will get ossified regardless of if it's encrypted in the Retry packet.

**Comment by martinduke** [comment]
+1 to GMAC, though I care much more about resolving this (as one of the few remaining wire image issues) prior to draft-25 than what the actual outcome is.

I think it's important that draft-25 be the last wire image change for a while.

**Comment by janaiyengar** [comment]
This thread got poorly forked from #3014. We've already marked #3014 as proposal-ready, and I'm marking this proposal-ready as well.

**Comment by ekr** [comment]
I don't really agree with the reasoning here, but I'm willing to concede I
am in the rough.
