### ISSUE TITLE
WINDOW_UPDATE parameters

### ISSUE THREAD

**Issue by ddragana** [quicwg/base-drafts#329]
> Byte offset: A 64-bit unsigned integer indicating the absolute byte offset of data which can be sent on the given stream. In the case of connection-level flow control, the cumulative offset which can be sent on all streams that contribute to connection-level flow control.

Can we clarify what "the cumulative offset which can be sent on all streams" means? It reads as cumulative amount of data that can be sent on all streams including data already sent, and not an increment like in h2. 
I think this should be an increment similar to h2.

**Comment by ianswett** [comment]
We considered that, but incremental differences are problematic when combined with reordering and loss.  Cumulative has no such problems, and the receiver can ignore old WINDOW_UPDATE values.

The only benefit I can think of for incremental would be slightly smaller encoding on the wire, but it's expected these messages are relatively infrequent, so that seems like a premature optimization.

Is there a benefit to incremental you have in mind?

**Comment by ddragana** [comment]
The reason why I wrote this is that 2^64 is the limit to how much data can be sent on a connection, if the cumulative window updates are used.

This number is really large, therefore we do not need to change this.
I will close the issue.

Is there an error code when the connection flow control reaches 2^64 limit? or will it wrap around and start from 0? 
Is it "QUIC_FLOW_CONTROL_INVALID_WINDOW (0x80000040): : The peer received an invalid flow control window.", the explanation does not sound right?
Sorry if I miss that in the draft.

**Comment by martinthomson** [comment]
FWIW, we could allow the limit to wrap, but that adds complications and it would be a rarely used feature.

**Comment by MikeBishop** [comment]
It's a good reason for a host to send a GOAWAY and spin up a new connection, though.  The problem is going to be how much margin you give yourself.  The closer you come, the more risk you run that the last streams you allow through will collectively need to use all the space remaining in your WINDOW_UPDATE value range.  Having to RST a nearly-complete download because you can't send the necessary WINDOW_UPDATE frame seems like an unfortunate corner to be able to back yourself into, even if it's rare.

**Comment by ddragana** [comment]
This is probably going to be the first limit that a connection will hit, not the packet ids limit.
We could also scale the offset, I do not think that the update needs to be per byte, it can be 1000Bytes as well. I do not think that we need granularity of a byte.

**Comment by ianswett** [comment]
I agree, this is almost certainly the first limit we'll hit at this point.

Scaling by 1024 or a similar value seems reasonable.
