### ISSUE TITLE
Remove mention of round-trip time in HTTP/3

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#3346]
On #3343 @kazuho proposes a change to GOAWAY that reduces the exposure of the QUIC API to HTTP/3.

The paragraph in question also suggests behaviour that relies on exposure of QUIC transport information: `allowing time for any in-flight requests (at least one round-trip time)`.

This seems to be the only occurence of round-trip time in the HTTP/3 document. I think we can editorialize ourselves out of this. For some HTTP/3 implementations, the RTT could be readily accessible, for others maybe not.

**Comment by kazuho** [comment]
The other issue of the last two sentences (quoted below) is that they do not suggest how an endpoint should choose last Stream ID of the second GOAWAY frame.
> After allowing time for any in-flight requests (at least one round-trip time), the server MAY send another GOAWAY frame with an updated last Stream ID. This ensures that a connection can be cleanly shut down without losing requests.

**Comment by kazuho** [comment]
Regarding how we should change, maybe something like below would be sufficient. My observation is that we can drop "at least one round-trip time" because the text that directly precede that implies that already.

"After allowing time for any in-flight requests to reach the server, the server MAY send another GOAWAY frame that carries the greatest request stream ID it has seen. This ensures that a connection can be cleanly shut down without losing requests."

**Comment by MikeBishop** [comment]
The text implies a little bit of interaction with the QUIC Stream ID space.  Because we had to change GOAWAY to signal the first *unprocessed* Stream ID, the HTTP layer needs to be able to get "the next" stream ID from QUIC in a given space.

But as to the general issue, I don't object to removing the specific dependency; anyone reading should be able to conclude that you need to allow an RTT for the requests to arrive, and if they have access to that value, they'll use it.
