### ISSUE TITLE
Does the amplification limit apply to PTO packets?

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3413]
From @gorryfair in #3214, this is not a nit:

>> Prior to validating the client address, servers MUST NOT send more
than three times as many bytes as the number of bytes they have
received.

> So, let me understand - does that include retransmissions? or is this constrain within the PTO or something?

I think that the intent was that the server limit its sending, including PTO.

**Comment by larseggert** [comment]
Discussed in ZRH. Proposed resolution is "yes".

**Comment by ekr** [comment]
Repeating what I said earlier: it's not clear to me that not being able to arm the PTO timer when at the limit implies that PTO packets count against the amplification limit. The reason is that you could have *already* armed the PTO timer at the time you hit the limit. E.g., you might be streaming 0.5RTT and so send Initial, Handshake, arm timer, <wait> 0.5RTT.

**Comment by ianswett** [comment]
@ekr the PTO should be updated when an ack-eliciting packet is sent, since the right edge moves, so that case should already be handled correctly.  I'll write an editorial PR to try to make all this extra clear.
