### ISSUE TITLE
0-RTT status of new transport parameters

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3433]
We've added new transport parameters since we wrote section 7.3.1.  The following TPs are neither MUST NOT remember nor MUST remember:
- max_idle_timeout
- max_packet_size
- max_ack_delay
- disable_active_migration

**Comment by marten-seemann** [comment]
In my opinion, the only one that the client SHOULD remember is max_packet_size. This is an interesting special case since the server doesn’t need to remember this one (nor store it in the session ticket).
I don’t see any motivation for remembering the other three TPs.

**Comment by ianswett** [comment]
Remember ing max_ack_delay is useless I believe, because Initial and Handshake packets use an max_ack_delay of kAlarmGranularity.

I would not want to remember disable_active_migration or max_idle_timeout if at all possible.

**Comment by martinthomson** [comment]
As max_idle_timeout and disable_active_migration can only ever apply after the handshake is complete, remembrance is unnecessary.

max_ack_delay is annoying because it implies a particular acknowledgment schedule for 0-RTT that might not be compatible with the path, but setting it to the absolute minimum is problematic also.

**Comment by martinthomson** [comment]
See also #3434.

**Comment by martinduke** [comment]
I don't read the text this way. In the fourth paragraph it says that "A client that attempts to send 0-RTT data MUST remember all other transport parameters used by the server." [i.e. all but a short list of obviously insane TPs listed in the previous paragraph.

I suggest we close with no action.

**Comment by MikeBishop** [comment]
@martinduke, that's a good point that the list doesn't have to be exhaustive.  The text says clients MUST NOT remember certain parameters and MUST remember all others.  So perhaps the more apt question is whether any of these unmentioned TPs belong in the MUST-NOT list.

**Comment by MikeBishop** [comment]
@martinduke, that's a good point that the list doesn't have to be exhaustive.  The text says clients MUST NOT remember certain parameters and MUST remember all others.  So perhaps the more apt question is whether any of these unmentioned TPs belong in the MUST-NOT list.

**Comment by martinthomson** [comment]
So I'm reviewing this and the only case I'm concerned about is max_ack_delay for 0-RTT.  The server's values might be remembered by the client and applied to its logic.  But I can't see any reason why this might cause actual problems as long as the client adjusts its value when it can.

If the server increases this value, then any increase might accrue to the RTT estimates that are received before the client installs the new value.  But the client won't be generating RTT estimates based on application data, so this is a wash.  And the effect on the PTO duration has no effect because you don't arm PTO because the recovery draft [forbids it](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#section-5.2.1-5).

So, I see three valid choices:

1. Say nothing.  Let people work out that max_ack_delay has no effect prior to the handshake completing on their own.

2. Explain this.  Probably just by saying "Note that max_ack_delay has no effect during the handshake therefore cannot be violated by a client sending 0-RTT data." OR something along those lines.

3. Explicitly forbid remembering this parameter, by adding it to the [MUST NOT use remembered values](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-7.3.1-3) list but don't explain it.

I'm inclined toward number 3 here, if only to save people the effort of working through this one.

**Comment by ianswett** [comment]
I agree with your analysis and your recommendation(3) that clients MUST NOT remember it.  We're pretty clear that the max_ack_delay is 0 until you receive the value in TPs, and this fits with that model.

**Comment by LPardue** [comment]
The proposed resolution in PR 3545, although short and sweet, categorises a TP as a MUST NOT. In the interest of process, I'm marking this issue as design. Since there is a proposal things should make the next round of consensus call, unless some objections are raised in the meantime.

**Comment by LPardue** [comment]
Accidental close, sorry.
