### ISSUE TITLE
Inconsistency of QPACK static table

### ISSUE THREAD

**Issue by kazu-yamamoto** [quicwg/base-drafts#3562]
Entry 52 has a space after `;`, ie `text/html; charset=utf-8`.
But entry 54 does not, ie `ext/plain;charset=utf-8`.
This is intentional? The other entries always have a space after `;`.

**Comment by MikeBishop** [comment]
IIRC, it's deliberate, albeit regrettable.

The values were compiled from real-world header use, and while the space is not semantically meaningful, we opted to go with the most common variant of each to get the most benefit on encoders which would do a strict string comparison to the value in the table instead of checking for equivalent values.

**Comment by LPardue** [comment]
Since the text is as intended, I believe we can close with no action.

**Comment by kazu-yamamoto** [comment]
It would be helpful if a comment of "no space is intentional" was added.

**Comment by afrind** [comment]
I'll add a comment to prevent this issue from coming up again

**Comment by kazu-yamamoto** [comment]
@afrind Thanks!
