### ISSUE TITLE
Prohibit TLS middlebox compatibility mode

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3594]
This came up in interop testing.  This mode causes the TLS stack to generate a ChangeCipherSpec message, which caused our server to crash.  That's a bug on our end, but it's still a problem.

We need to decide whether this mode is acceptable.  Right now, we only say that it is "redundant".  A prohibition this mode would be easier all around.  It would avoid spending 32 bytes for both endpoints too.

Unfortunately, this is a design change.

**Comment by DavidSchinazi** [comment]
I'm not sure what this change would get us. Isn't it simpler to ignore CCS on receipt instead of requiring the receiver to check for CCS and fail the handshake?

**Comment by martinthomson** [comment]
So yes, one answer is to ignore it and move on.  But we should say that and require that implementations do so.

The answer I prefer is prohibition.  This is wasted bytes.

**Comment by DavidSchinazi** [comment]
If this were purely a QUIC matter, I would agree. This one is slightly trickier because it puts additional requirements on TLS stacks and not all QUIC implementers control their TLS stack. Additionally, is this a principled approach? Should we also be banning TLS padding (RFC7685) because it is similarly redundant?

**Comment by ianswett** [comment]
Practical question: Is there anyone for whom this restriction would be onerous?

Ideally there would be a day we'd be able to get rid of compatibility mode for TLS 1.3 entirely, so prohibiting it from QUIC seems like the first step.  As a corollary, it seems like TLS implementations should have a knob to enable/disable it, otherwise compatibility mode becomes the de-facto only mode.

**Comment by martinthomson** [comment]
Our client has a switch that defaults to off.  Apparently picotls had no switch, but @kazuho already [fixed it](https://github.com/h2o/picotls/pull/305).

**Comment by kazuho** [comment]
Just to be clear, picotls has had the switch, but it has been sending a 32-byte legacy_session_id even when the switch was off. That was a violation of a MUST in RFC 8446, purely implementation bug.

@DavidSchinazi 
> I'm not sure what this change would get us. Isn't it simpler to ignore CCS on receipt instead of requiring the receiver to check for CCS and fail the handshake?

In QUIC, it is impossible to send CCS, because the CRYPTO streams of QUIC can only carry handshake messages. CSS is not a handshake message, it's a TLS record. Therefore, it is my understanding that this issue is an editorial clarification.

**Comment by martinthomson** [comment]
Just to close the loop (and discuss on the issue): Having a SHOULD on the server reaction is fine with me.

**Comment by larseggert** [comment]
Sounds like design?
