### ISSUE TITLE
5-tuple routing and SPA

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3608]
Offshoot from #3536 review.  Servers behind a load balancer, and the load balancer isn't CID-aware.  Each server gives out an IP:port per client in the `preferred_address`  parameter.  _If_ the client moves to the SPA, then future migration is fine -- it will continue to talk to the same server using the preferred address.  If the client doesn't move, those future migrations will break.  There's currently no way to set `disable_active_migration` to "only if you don't use my preferred address".

Similarly, if the primary connection is to an anycast address, if the client fails to move to the preferred address, subsequent migration will likely break.

Should we blanket recommend that clients not actively migrate if they ignore / are unsuccessful in using the SPA?  Or should there be a way for the server to indicate that?

**Comment by ianswett** [comment]
Good question.  This brings up a related question for me about disable_active_migration.  Given a server can decide not to give out any additional connection IDs, doesn't that give it a mechanism for disabling active migration?

Ironically, given recent decisions on connection CIDs and SPA, if an SPA is supplied, then the client always has a second connection ID it can use on any path, not just the SPA.  So my suggestion of not giving out extra CIDs fails for the original path, but not the SPA.

**Comment by erickinnear** [comment]
What we’ve said for this so far is that SPA is limited to offering a minimum of a single additional CID that needs to work in both places, the original server and the preferred server.

As Ian says, the original server should not issue the client any more CIDs (if you have some that are deployment specific) until after they’ve successfully migrated to the new endpoint, at which point the preferred server can handle that issuance.

And as he notes, you still have to deal with the fact that there are two CIDs that the client could use, from any incoming address. 

It seems as though the full way to solve this is to define potentially disjoint sets of TPs that different servers could set to match their particular requirements (around more than just migration). In that world, if you had an initial server that couldn’t handle migration and a preferred server that did handle migration, you could set different TPs to indicate that. It goes well beyond that though, any other TP might have a different values for the original server and then have those be different with the preferred server. But that does feel an awful lot like something that goes with full server migration.

In the limited form that we have now, if you want to be able to push someone off to a different server, there are some limitations that you need to deal with, like being able to set up enough of a shared configuration for the two that the same TPs work with both. 

=================

In practice, I think this means we end up with the following situation: 

The client either moves to the requested address or it doesn’t. 
- If it does, then you’re in good shape, in theory you gave it TPs that matched what the server wanted and everybody is happy.
- If it doesn’t, then you’re unhappy, since in theory you had a reason you asked it to move in the first place. You might choose to close it down more aggressively than you would on the preferred server to save resources, or give it smaller limits for flow control, etc. 

When you’re in the “client didn’t move” state:
- If the client then tries to use the original 2nd CID that you gave, from the same IP address/port, then a non-CID aware load balancer should be fine.
- If the client then tries to use the original 2nd CID that you gave, from a different IP address/port, then a non-CID aware load balancer will not be happy. 

Of course, the problematic case is even narrower, since if the client is probing the new path they’ll see it as though there isn’t any connectivity, just like they will if there’s anything else on the new path that prevents their connection from working — this is always a risk when migrating, so they should be unsurprised and stick with their current path. 

If they’re forced to move for whatever reason, then it will be just as though they didn’t have connectivity over the new path (which they don’t) and whether or not you disable migration you’ll see the same outcome — the connection is closed.

Interestingly, I’m not actually seeing a difference from the client’s perspective in terms of outcome whether you let them try with that CID and fail or if you told them to not try.

**Comment by erickinnear** [comment]
In very much shorter terms: isn’t this a situation that all clients already need to be able to handle for other reasons?

**Comment by kazuho** [comment]
@MikeBishop 
> Should we blanket recommend that clients not actively migrate if they ignore / are unsuccessful in using the SPA? Or should there be a way for the server to indicate that?

I do not like the first option, because IMO banning migration on the original address is a premature optimization based on what we have now, has negative effect on what we would have in the future.
My assumption is that the majority of the server deployments would be CID-aware, especially in the long term, especially in terms of traffic volume. Note that the volume of traffic is more important than the number of server deployments, as migration is about (improving) end-user experience.

IMO there are two ways forward:
* (a) State that disable_active_migration TP only applies to the original address. Per-definition, server-preferred address is an address that is capable of receiving packets from any address. There is no need to prohibit clients doing migration when connected to SPA.
* (b) Do nothing. Clients are RECOMMENDED to implement SPA, and this issue is about a small fraction of deployments that rely on non-CID-aware load balancers. We can ignore the problem.

**Comment by MikeBishop** [comment]
> This brings up a related question for me about disable_active_migration. Given a server can decide not to give out any additional connection IDs, doesn't that give it a mechanism for disabling active migration?

IIRC, we had that conversation when deciding whether to add `disable_active_migration` in the first place.  The short version is that taking this approach prevents the client from rotating CIDs on the primary path; if we want the client to be able to rotate CIDs but not migrate, they need to be distinct signals.

@erickinnear, in a way you're correct that clients will have to deal with the fallout regardless of what the server says.  However, the actual use of `disable_active_migration` is likely to trigger a little more than just "don't do that" -- a client might PING more actively to prevent NAT rebindings, for example.  I think it's this hinting aspect that's actually more valuable, since as you note, clients need to be prepared for attempted migrations to fail even with servers that tacitly support them.

> Per-definition, server-preferred address is an address that is capable of receiving packets from any address.

I don't think this is necessarily true, though I agree that we're talking about smaller and smaller fractions of server space.

**Comment by kazuho** [comment]
@MikeBishop 
>> Per-definition, server-preferred address is an address that is capable of receiving packets from any address.
> 
> I don't think this is necessarily true, though I agree that we're talking about smaller and smaller fractions of server space.

While I agree that it might not necessarily be true at the moment, I might argue that it is going to be true.

The basis of the resolution for #3559 and #3565 (both on consensus call) is that servers using preferred address would not be using the server's address for distinguishing between connections. We also know that a server cannot use client's address (unless there is out-of-band knowledge), because clients are not required to use the same 2-tuple when migrating to a different address (and also because there are NATs).

The outcome is that the server has to rely on CID when using SPA. And therefore I might insist that servers using SPA would always be capable of handling further migration.

**Comment by ianswett** [comment]
@kazuho So your suggestion is that disable_active_migration applies only to the original address and the SPA must always support active migration, because it has to use CID routing?

I don't think that'd be a problem for our use cases, but I'm not sure about others.

**Comment by kazuho** [comment]
@ianswett 
> So your suggestion is that disable_active_migration applies only to the original address and the SPA must always support active migration, because it has to use CID routing?

Exactly. I think that that would be the correct thing to do, if we are to make changes.

I agree that existing clients might be applying `disable_active_migration` after migrating to SPA, and that they do not want change. But they can remain as they are, because the change in spec does not lead to interoperability issues.

To paraphrase, I think making the aforementioned change is strictly better than doing nothing, because it would be an improvement to some, while not hurting anybody.

**Comment by martinthomson** [comment]
A truth table might help here.

... | migration supported (no signal) | disable_active_migration set | 
---|---|---|
no preferred address | normal (migrate as you like);  | don't migrate |
preferred address | normal (migrate at your leisure) | don't migrate |

Right now, our definition of disable_active_migration is a simple "don't migrate".  But the argument here says that the server that provides a preferred address is *probably* capable of handling migrations on the basis that it has to support one.  We might insist on the source address not change, but the fact is that some NATs (those with address-dependent mappings) will change the source address.

Changing to a definition where disable_active_migration is instead "don't move to a new address unless you use a preferred address" is a little more complicated, but doable.

Is it worth the extra complexity this late in the process?  Is that complexity justified when it would be trivially possible to define another extension that said "I support migration on my preferred address"?

**Comment by ianswett** [comment]
I'd like to minimize changes, but I believe the status quo is that disable_active_migration applies to both the original address and SPA.  As such, all suggestions above seem like a change.

There is a mechanism to disable migration on the SPA, which is don't give out any more CIDs once they migrate.  I don't expect any hosts to support migration on the original path and not the SPA, so I don't think that's a use case worth supporting(or encouraging).

**Comment by martinthomson** [comment]
My proposal is that we defer the ability to signal "I support migration, but only on my preferred address" to an extension.

**Comment by ianswett** [comment]
@martinthomson And leave the current behavior of disable_active_migration applies to both the original address and SPA?

I'm a bit concerned that makes SPA somewhat useless.  Is this issue a candidate for parking and we can come back to and see if we can live with the status quo?

**Comment by MikeBishop** [comment]
> There is a mechanism to disable migration on the SPA, which is don't give out any more CIDs once they migrate.

Which, again, not only disables migration, it disables the ability to rotate CIDs.  That's not something we want servers to be doing.

@kazuho's argument is convincing that it's improbable for something which supports SPA to not be able to uniquely identify connections (whether by CID or because the SPA endpoint is unique).  Therefore, I'd support scoping disable_active_migration to the handshake address, and defer the ability to disable it on the SPA to an extension.

Loosening this definition doesn't make any current clients break, so I suspect it's bearable despite the schedule.

**Comment by ianswett** [comment]
If we're going to make a change, I support @kazuho and @MikeBishop direction of scoping disable_active_migration to the handshake address.

And I agree that I don't expect this breaks many existing clients.

**Comment by DavidSchinazi** [comment]
I personally find the proposed change confusing. I'm not sure I find the use-case of "my original address doesn't support migration but my preferred address does" compelling. Since this can be easily solved by an extension with no downside over it being in the core docs, I don't see a reason to change the spec at this point in the process.

**Comment by martinthomson** [comment]
As this has sat here a while, I'll reiterate my proposal again: we defer the ability to signal "I support migration, but only on my preferred address" to an extension.

Which means that disable_active_migration applies to both the original address and SPA, so answer the question (sorry Ian, I missed that).

I realize that you could change the meaning of disable_active_migration to apply to the address the server uses in the handshake, but there are interesting corner cases and I don't think we need to concern ourselves with those.  For instance, if you connect over V4 and get disable_active_migration and server_preferred_address.  If that SPA includes a V6 address you can't use, along with the same V4 address, what then?  Does the server really support migration?

I know that the current situation is unappealing, and I think that disable_active_migration is not good for the protocol.  But it exists for very good reasons.  Trying to limit the scope is admirable, but as we haven't seen a concrete proposal, I think we need to move on.

**Comment by kazuho** [comment]
@martinthomson 
> I realize that you could change the meaning of disable_active_migration to apply to the address the server uses in the handshake, but there are interesting corner cases and I don't think we need to concern ourselves with those. For instance, if you connect over V4 and get disable_active_migration and server_preferred_address. If that SPA includes a V6 address you can't use, along with the same V4 address, what then? Does the server really support migration?

If this example is concerning, I'd argue that is an issue that already exists, orthogonal to what we are discussing here. I am still not convinced that limiting the scope of disable_active_migration to just the original address is going to cause any _new_ issue.

That said, if nobody needs this change, I'm more than happy to move on with status-quo.

**Comment by ianswett** [comment]
I've thought about this, and I don't believe we need this change, but I also think the change @kazuho suggested makes the current behavior better overall.

A server that supports migration on the SPA(ie: unicast) and not on the handshake address(ie: anycast) will end up not disabling migration and hoping that most clients migrate to the SPA or don't support migration of any sort.  That seems like a plausible hope, though I'm a bit leery of hope based protocol design.

**Comment by ianswett** [comment]
Thinking about this more, a statement like:
"Migration is never guaranteed to succeed.  For servers that advertise a preferred address, it's expected migration is more likely to be successful when using the preferred address than the handshake address."

**Comment by janaiyengar** [comment]
This conversation has made it clear to me that an address, and not a server, is the thing that supports client migration. Which makes sense -- migration support at the server is entirely a question of routability, and it makes sense that it would be tied to the address in question and not the endpoint. So *if* we were to do anything, I think I would propose: 
- scoping disable_active_migration to the handshake address, and
- adding two disable_active_migration flags to the preferred_address TP, for the two addresses in the TP.

That said, this is a clean enough extension. A new extension can define a new TP that provides this granular interpretation of the three server addresses. A server that wishes to support this can send both the SPA and this newSPA TPs, with the SPA TP (with the current scoping of disable_active_migration applying to all server addresses) providing cover for legacy clients.

Also I expect that clients are likely to switch to using the SPA if provided. A server that has different routability properties for the two addresses can wait for some deployment and make decisions on whether to risk allowing migration based on data of what it sees as client behavior with SPA.

I would argue for doing nothing now. Experience will teach us the right way forward. If necessary, this extension will be easy enough to do, and importantly, the current interpretation of disable_active_migration gives us the right kind of cover in the meantime.

**Comment by DavidSchinazi** [comment]
I would rather not make the change in #3670. It assumes that migration is more likely to succeed when attempted to the preferred address as opposed to the handshake address. While this assumption might hold in some server deployments, it is not a fact. I'd rather we didn't bake this assumption into the core spec. I'd prefer to see this feature as an extension.

**Comment by kazuho** [comment]
@DavidSchinazi 
> It assumes that migration is more likely to succeed when attempted to the preferred address as opposed to the handshake address. While this assumption might hold in some server deployments, it is not a fact.

Would you mind elaborating why a server, accepting connections on a preferred address, might not be able to disambiguate connections using CIDs?

As stated previously, when a client migrates to the preferred address, the client's address port tuple can change due to the existence of NATs. A server using preferred address need to take that into consideration. That means that a server has to disambiguate connections based on the CID, which in turn means that the server would be possible to support migration.

**Comment by DavidSchinazi** [comment]
Hmmm thanks for that note @kazuho. Looking at things under that light, I agree that the assumption I described above is already part of the protocol. Please disregard my comment above https://github.com/quicwg/base-drafts/issues/3608#issuecomment-631867975 .
