### ISSUE TITLE
max_udp_payload_size during the handshake

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/base-drafts#3638]
The `max_udp_payload_size` transport parameter (formerly known as `max_packet_size`) instructs the receiving endpoint that it should try to avoid sending packets bigger than that number. However, some packets are sent before the transport parameters are received. Should the draft contain some guidance about what value to use during the handshake? Our implementation currently uses a default value of 1350 until the transport parameters have been received, and I wonder if that may lead to interop issues if some Web servers implement QUIC but drop packets larger than 1300 for example. One could consider using the minimum possible value (1200) during the handshake but I fear that this would negatively impact performance.

**Comment by kazuho** [comment]
This is a good issue.

If we are to provide guidance, my preference goes to stating that an endpoint should not send datagrams that are larger than its first flight, unless that endpoint implements PMTUD.

The rationale is that we should avoid packets starting to get dropped mid-connection.

First flights getting dropped is fine, because clients can do happy-eyeballing. Even if they only use QUIC, not starting a transaction is much better than a transaction inflight getting lost.

**Comment by martinthomson** [comment]
I'm with @kazuho here.  As a client, if you send at 1350 and those are all dropped, that reduces to "the path doesn't support UDP".  The real risk is if you send at 1200 and then increase that later without first probing.

I'm happy to take this as editorial, but would prefer to confirm that no one wants a substantive change.

**Comment by janaiyengar** [comment]
I agree with @martinthomson : I'm happy with clarifying that this will look like an MTU issue.
