### ISSUE TITLE
New packet format used before it is defined

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/base-drafts#3673]
#3573 introduced a new bespoke packet format. I don't have issues with the format itself, but as I reviewed [draft-ietf-quic-invariants-08](https://tools.ietf.org/html/draft-ietf-quic-invariants-08) I was surprised to see it used there without any explanation as to how to decipher it. I think it would be nicer if each document that uses this format either:
- References the "Notational Conventions" section from draft-ietf-quic-transport
- Has a "Notational Conventions" section of its own explaining this format

**Comment by martinthomson** [comment]
> This document uses terms and notational conventions from [QUIC-TRANSPORT].
-- https://quicwg.org/base-drafts/draft-ietf-quic-invariants.html#section-2-2

There is a lot more that the document leans on than the packet format grammar, so any expansion of this might explode.  I tend to think that this is adequate.

**Comment by MikeBishop** [comment]
I agree that the reference is sufficient, except for one aspect:  We do want the invariants drafts to be readable without needing to get into the v1 spec, because the target audience is people who need to handle QUIC without regard to versions.

I think it's wrong that the reference to QUIC-TRANSPORT is normative instead of informative, and this reference for conventions and definitions is the only reference in the doc that actually needs to be normative.  I'm almost be more inclined to move the notation definition across, just as we ultimately did for the definition of VN, and let -transport refer to -invariants for it.
