### ISSUE TITLE
Are both types of CONNECTION_CLOSE frames permitted during the handshake?

### ISSUE THREAD

**Issue by rpaulo** [quicwg/base-drafts#3713]
I think the spec is ambiguous when it says in section 17.2:

> PING, PADDING, and CONNECTION_CLOSE frames are also permitted. An endpoint that receives an Initial packet containing other frames can either discard the packet as spurious or treat it as a connection error.

and:

>Handshake packets MAY contain CONNECTION_CLOSE frames.

But CONNECTION_CLOSE can mean 0x1c or 0x1d.  Are both permitted during the handshake?

**Comment by janaiyengar** [comment]
@rpaulo: In this case, the intent is to allow both. Unless explicitly specified, I would read the text to mean both types of CONNECTION_CLOSE frames.

**Comment by rpaulo** [comment]
Okay, if more people think that way, we can close with no action.

**Comment by martinthomson** [comment]
So on the surface, there is no inconsistency: the two sections permit CONNECTION_CLOSE.

But the question about the different types of CONNECTION_CLOSE is more relevant than @janaiyengar's response might imply.  We currently require that CONNECTION_CLOSE of type 0x1d (application close) is not sent in Initial or Handshake packets.  So that's a drafting error, and we might reasonably take this as an editorial issue.

However, if the question is about what a reaction to receiving an application CONNECTION_CLOSE in one of those packets, we might consider a different posture.

If you get an application CONNECTION_CLOSE in an Initial packet that is otherwise valid, you probably want to drop the connection.  And you probably don't want to start sending CONNECTION_CLOSE in response every time, because that leads to madness.  But this is a general problem: if you detect and error and that error keeps being repeated, it probably isn't a good idea to generate a CONNECTION_CLOSE in response to every infraction.

**Comment by kazuho** [comment]
The question is directly addressed in the TLS specification. It says _CONNECTION_CLOSE frames signaling errors at the QUIC layer (type 0x1c) MAY appear in any packet number space. CONNECTION_CLOSE frames signaling application errors (type 0x1d) MUST only appear in the application data packet number space._ (https://quicwg.org/base-drafts/draft-ietf-quic-tls.html#section-4-4.2).

This was the outcome of several issues that we discussed recently, #3440 was the fix that we applied.

I agree that there is ambiguity in the transport draft and that we'd better have an editorial refinement.

**Comment by martinthomson** [comment]
I'm going to re-close the can of worms I half-opened in my earlier comment and take this as editorial.

From memory, the larger question of how to deal with junk is something we've discussed several times.  If anyone wants to take that up, I'm happy to do that, but let's at least correct the obvious error.

**Comment by rpaulo** [comment]
It does make sense that we only allow 0x1c during the handshake.

**Comment by janaiyengar** [comment]
@rpaulo : Apologies, I misspoke -- I was speaking to interpretation of text, rather than the actual question itself.
