### ISSUE TITLE
QUIC Transport - sending after final size?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/base-drafts#3721]
Section: Stream Final Size 
/An endpoint MUST NOT send data on a stream at or beyond the final size./
- It seems reasonable not to send after the Final Size , but why is this a “MUST NOT”?
The need to require this is not stated, and the reaction of the receiver appears to be ignore. Is this requirement justified?

**Comment by MikeBishop** [comment]
Because the Final Size is used to synchronize flow control consumption.  If the Final Size is not, in fact, the last data ever sent on a stream, the two sides will disagree about how much flow control credit has been consumed.

The reaction of the receiver isn't to ignore; in the very next paragraph:

> A receiver SHOULD treat receipt of data at or beyond the final size as a FINAL_SIZE_ERROR error, even after a stream is closed. Generating these errors is not mandatory, but only because requiring that an endpoint generate these errors also means that the endpoint needs to maintain the final size state for closed streams, which could mean a significant state commitment.

**Comment by gorryfair** [comment]
Aha, I knew there must be a reason - could we add something like this sentence? "This is used to synchronize flow control consumption between the endpoints."
