### ISSUE TITLE
Defer the definition of closing and draining states

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#3843]
I understand why you might want to cover closing and draining states before covering the types of close, but I think it would actually be clearer pedagogically to cover the types of close and point to closing and draining states, putting that later.

**Comment by martinthomson** [comment]
I agree with this, but it will require some updates to other drafts.

**Comment by MikeBishop** [comment]
Given that closing/draining states *only* occur after immediate close, it might make more sense to move 10.1 to be 10.[3->2].2

**Comment by MikeBishop** [comment]
Actually, poking at it a bit, that works -- but a lot of the content in current-10.1 duplicates content in current-10.3.  Rather than merely moving the text to be a sub-section, we should probably try to condense it a bit; either move all the close/drain requirements into the new subsection, or fold the two sections together.
