### ISSUE TITLE
How long is a validated address good for?

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3880]
There are a few cases where we don't have continuous validation of a peer address.  A long idle timeout might still be short enough that this isn't a concern.

1. A path migration that returns to a previously-used path might happen over a relatively long period of time.

2. NEW_TOKEN can be good for a considerable time.

Right now, the time limit is entirely undefined.  That might be the right answer, but maybe we should say that we don't know.

If we do think that a time limit makes sense, then we need to pick a value.  I wouldn't even dare to suggest a number right now.

**Comment by kazuho** [comment]
I do not think that we need to recommend a particular value. I might even ask if there is a need to have a time-bound.

The reason we have the 3x limit prior to address validation is because it is an DDoS attack vector. Compared to that, it is much harder to use old validated paths as an attack vector. Compared to the difficulty, the benefit that the attacker gains is rather small.

For the NEW_TOKEN case, the amplifier is 10x + alpha (assuming that IW is 10 packets), less than a magnitude different from the 3x limit.

For the path migration case, the amplifier becomes maybe two magnitudes greater, but the effectiveness of the attack is limited by the idle timeout, as path migration works only when the connection is kept alive.

**Comment by ianswett** [comment]
I'd suggest we do nothing about this, since I don't have a good answer.

To quote Roberto: "A server's gonna do what a server's gonna do."

**Comment by LPardue** [comment]
I'm not seeing support for this idea...

**Comment by janaiyengar** [comment]
I think this nicely fits in the bucket of "Future Work" :-)

**Comment by martinthomson** [comment]
This is a design issue, but only if we decide to do something.  Personally, I'm happy to defer this.  But this is not my issue; this was raised in a WGLC email from @gloinul.

**Comment by larseggert** [comment]
Proposed resolution is to close with no action, consensus to be confirmed

**Comment by larseggert** [comment]
Labelling as such.

**Comment by gloinul** [comment]
I am fine with for future consideration and that the WG has an understanding of the boundaries of potential impact.
