### ISSUE TITLE
Offloads should not delay ACKs

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#4001]
The existing text mostly covers this, but I don't think it's always as clear as it could be.

If one is doing various offloads(pacing/crypto/etc) and those cause the sender to decide to send a batch of packets at once, with release times that are over a few milliseconds, the sender should not have to wait until all those packets are released to send an ACK.

A simple example at the receiver is an ACK arrives with PN 10, then PN 9 arrives.  I do not believe PN 9 should not be considered 'out-of-order' and trigger an immediate ACK.  Recovery is designed with this case in mind, but when re-reading this text, I thought it was unclear.

The simple way to think about this is "ACK-only packets don't affect acknowledgement behavior", which matches with TCP and most of our existing text.

I think this will end up being editorial and I believe the only clarification necessary is #4000 but I'd appreciate other peoples thoughts on whether this is something worth thinking about and whether there are any other changes necessary.

**Comment by kazuho** [comment]
I share the view that this has been the intent, and that it is editorial.

Loss recovery is an interaction between sender sending data vs. receiver sending acks. We might have two endpoints doing loss recovery at the same time, when both sides are sending data. But that should not affect how loss recovery works.

**Comment by kazuho** [comment]
In https://github.com/quicwg/base-drafts/pull/4000#issuecomment-674638169, @martinthomson asks:
> How do you tell if the absent packets are ack-eliciting? I mean, most scenarios we use this definition are for the receiver, which can't know whether a missing packet is ack-eliciting.

I think we need to think about two possibilities: an ack-eliciting packet overtaking ack-only packet, and an ack-only packet overtaking an ack-eliciting packet.

If the former happens, the receiver can do nothing but send an immediate ack, because it cannot tell if the yet-missing packet is ack-only. But in the opposite case, the receiver can tell that it was an ack-only packet, because it has already received that packet.

IIUC, @ianswett's point is that we'd frequently see the latter when pacing is used, and therefore that we should address the issue.

IMO, this issue is an artifact of us using one packet number space for loss recovery in both directions. The problem cannot be cleanly solved unless we use different packet number spaces for ack-eliciting packets and ack-only packets. That said, I do think that it is a good idea to minimize the impact of the problem, and that the proposed clarification works fine in that respect.

**Comment by martinthomson** [comment]
That's a reasonable analysis of this situation.  That is also consistent with what our stack implements.  That is, we only ever send an immediate acknowledgement when we receive ack-eliciting packets.  I can't see how you would do otherwise, frankly.

However, I think that attempting to define "out-of-order" is the problem.  I just searched the transport document for this and we don't use the definition.  Therefore, I suggest that we say what we mean when it comes to describing how to immediately acknolwedge packets.  That is,

> An endpoint SHOULD generate and send an ACK frame without delay when it receives an ack-eliciting packet either:
> * when the packet has a packet number less than any other ack-eliciting packet that has been received; or
> * when the packet has a packet number larger than any other ack-eliciting packet that has been received and there is an apparent gap between that other packet and this packet.

Or something like that.

The out-of-order definition can go.

**Comment by ianswett** [comment]
Good thought on getting rid of 'out-of-order', that should help.

**Comment by MikeBishop** [comment]
I was about to say we could simplify the second bullet, but that would miss the case of:
- N-3:  last received ack-eliciting packet
- N-2:  lost
- N-1:  ACK-only packet
- N:  Newly received

We want to send an immediate ACK on receipt of N, but not N-1.  Nor do we want one on the late receipt of N-2.

**Comment by LPardue** [comment]
border-Borderline design, let's run the process for visibility
