### ISSUE TITLE
Implying sequencing

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4018]
(Broken out of #3214.)

> frames in multiple packets in order to make
- Could be read as implying sequencing, I suggest removing /in order/ or saying /to ensure that

**Comment by MikeBishop** [comment]
Context:  Where is the text in question?

**Comment by martinthomson** [comment]
I can't find this text at all.  Even by searching for a substring "frames in mu" or "order to make".

**Comment by larseggert** [comment]
@gorryfair?

**Comment by gorryfair** [comment]
This particular text appears to have been edited, thanks.

There's still other uses of "in order" that the editors may like to address to avoid potential misunderstanding:

/Servers SHOULD be able to read longer connection IDs from other QUIC versions in order to properly form a version negotiation packet./ ... this might be misread as an ordering requirement, but I think is intend to be: /Servers SHOULD be able to read longer connection IDs from other QUIC versions to properly form a version negotiation packet./

and
/Servers SHOULD be able to read longer connection IDs from other QUIC versions in order to properly form a version negotiation packet./ ... seem like /Servers SHOULD be able to read longer connection IDs from other QUIC versions to properly form a version negotiation packet./ 

This also is potentially misread: /An adversarial sender might intentionally send fragments of stream data in order to cause disproportionate receive buffer memory commitment and/or creation of a large and inefficient data structure./ and could be /An adversarial sender might intentionally send fragments of stream data that cause disproportionate receive buffer memory commitment and/or creation of a large and inefficient data structure./

and perhaps this also: 
/An adversarial receiver might intentionally not acknowledge packets containing stream data in order to force the sender to store the unacknowledged stream data for retransmission./ would be clearer as /An adversarial receiver might intentionally not acknowledge packets containing stream data so that it forces the sender to store the unacknowledged stream data for retransmission./

**Comment by larseggert** [comment]
@gorryfair, you *please* need to open new issues for these things, one for each.

**Comment by gorryfair** [comment]
The current text no longer exists, so this issue can be closed.

However, this was a generic editorial comment to the editors ... and several instances still exist. I'll follow the recommendation to raise 4 issues to address the 4 cases I currently see.
