### ISSUE TITLE
This seems like tuning

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4020]
(Broken out of #3214.)

> Servers that do not support a particular version
>   are unlikely to be able to decrypt the payload of the packet.
>   Servers SHOULD NOT attempt to decode or decrypt/
- This seems like tuning? Or is the intention to protect the endpoint from an attack, please explain the SHOULD.

**Comment by MikeBishop** [comment]
> The first packet for an unsupported version can use different semantics and
encodings for any version-specific field.  In particular, different packet
protection keys might be used for different versions.  Servers that do not
support a particular version are unlikely to be able to decrypt the payload of
the packet.  Servers SHOULD NOT attempt to decode or decrypt a packet from an
unknown version, but instead send a Version Negotiation packet, provided that
the packet is sufficiently long.

I'm having trouble seeing what's needed here.  The endpoint has received a packet professing to be in a version it does not understand.  It can't know the semantics or encoding of any field there -- and the paragraph already explains that.  Yes, I'm sure there are potential attacks in interpreting a packet of unknown provenance and unknown semantics against a different set of semantics and expectations, but I'm not convinced we need to explain them.  The text recommends sending a Version Negotiation packet, which seems like the only sensible response.

**Comment by marten-seemann** [comment]
This refers to [5.2.2 Server Packet Handling](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-server-packet-handling).

**Comment by larseggert** [comment]
@gorryfair?

**Comment by gorryfair** [comment]
I'm looking for two things:

(i) I think this ought to clarify the intention for the SHOULD, I suspect it is clear to those working on this part, but not clear to me why this is a recommendation - i.e., specifically can you give me a use-case of why the Server would otherwise *USE* information from a packet from an unknown version, unless the intention is to say the server shouldn't waste resources to do try to do this? 
(ii) I think this implies understanding of Section 14.1 later in the spec, and a ref would help.

So...
* Is it equally true that..  
"Servers MUST NOT use the contents of a packet with an unknown version, and SHOULD NOT decrypt this packet, but instead send a Version Negotiation packet, provided that
the packet is sufficiently long (see Section 14.1)."?

* Or perhaps simply explain something like: 
"Servers SHOULD NOT commit resources to attempt to decode or decrypt a packet from an
unknown version, but instead send a Version Negotiation packet, provided that
the packet is sufficiently long (see Section 14.1)."?

**Comment by MikeBishop** [comment]
Fundamentally, it's a caution against assumptions which could prove incorrect, such as "this looks like an unencrypted TLS ClientHello, so I can go find the field that contains...."  The server will either process information in a way that could be used maliciously, or the server will generate a response that won't be understood by the client.  Ideally, this would be a MUST, except that it's entirely unenforceable by the client what the server does internally.

Perhaps the right solution here is to remove the normative language with regard to that piece:

> The first packet for an unsupported version can use different semantics and encodings for any version-specific field. In particular, different packet protection keys might be used for different versions. Servers that do not support a particular version are unlikely to be able to decrypt the payload of the packet. Servers SHOULD respond with a Version Negotiation packet, provided that the ~~packet~~ **datagram** is sufficiently long.

**Comment by gorryfair** [comment]
That approach seems fine.
