### ISSUE TITLE
Client that does not PAD does not negotiate?

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4021]
(Broken out of #3214.)

> The size of the first packet sent by a client will determine whether
>   a server sends a Version Negotiation packet.  Clients that support
>   multiple QUIC versions SHOULD pad the first packet they send to the
>   largest of the minimum packet sizes across all versions they support.
>   This ensures that the server responds if there is a mutually
>   supported version.

- Are you saying a client that does not PAD does not negotiate? If so: What is the logic behind that design decision?
- I don’t read that as it assures what it say. To me, the padding assures the client can send this side of packet to the remote endpoint.
- Does this agree with what is written in section 8.1 on padding? and Section 14?

**Comment by MikeBishop** [comment]
Yes, a client that does not pad to at least the minimum packet size for some version the server supports will not receive a Version Negotiation packet in response.  The corresponding server text is in 5.2.2:

> If a server receives a packet that indicates an unsupported version but is large enough to initiate a new connection for any supported version, the server SHOULD send a Version Negotiation packet as described in Section 6.1. A server MAY limit the number of packets to which it responds with a Version Negotiation packet. Servers MUST drop smaller packets that specify unsupported versions.

This is both to prevent an attack vector from spoofed packets, and to reduce the risk that a non-QUIC packet will trigger Version Negotiation in response.  There is a slight risk that the client might only support version of QUIC with smaller minima and the connection attempt will time out instead of discovering via VN that there are no mutually supported versions.  However, if there is any overlap, compliance with this SHOULD enables the client to trigger the server's VN response.

Yes, this aligns with the guidance in Section 8.1:

> Clients MUST ensure that UDP datagrams containing Initial packets have UDP payloads of at least 1200 bytes, adding padding to packets in the datagram as necessary.

and Section 14:

> A client MUST expand the payload of all UDP datagrams carrying Initial packets to at least the smallest allowed maximum packet size (1200 bytes) by adding PADDING frames to the Initial packet or by coalescing the Initial packet; see Section 12.2.
> ...
> A server MUST discard an Initial packet that is carried in a UDP datagram with a payload that is less than the smallest allowed maximum packet size of 1200 bytes.

However, those are in regards to a packet from *this* QUIC version, while the text you're asking about regards packets when the peer's QUIC version is unknown as of yet.

**Comment by martinthomson** [comment]
Not seeing any action here.  As Mike says, the text describes sender requirements and explains why.

**Comment by larseggert** [comment]
@gorryfair?

**Comment by gorryfair** [comment]
I agree with the logic in this thread, but this seems far too subtle/clever and others will be confused at this point. However, I read this as the remote checks that the minimum size is sufficient. That means not padding this breaks the protocol. Why doesn't that require a MUST for any version (sec 14). If it doesn't then this doesn't yet explain under what cases the present "SHOULD" can be violated.

**Comment by MikeBishop** [comment]
Not padding breaks the protocol, so there's a MUST in Section 14.  That MUST *does* apply to all versions that the client supports; the client obviously can't know the details of versions it doesn't support, including any the server supports, so that's all it can reference.  There's no minimum first-packet size in the invariants.

The server SHOULD send Version Negotiation in response to a packet of unknown version but an appropriate size; if it doesn't, the client won't know what versions it supports, but it might choose not to do so every time.  (Hence the "MAY limit" in the next sentence.)

Is the thing that's missing for you a linkage between "SHOULD send" and "MAY limit"?

**Comment by gorryfair** [comment]
All of this makes sense, but it was the sentence in section 6 which I found unclear, which says: "Clients that support multiple QUIC versions SHOULD pad the first packet they send to the largest of the minimum packet sizes across all versions they support." That made me ask what happens when they support a version and didn't pad to the min size required by that version?

**Comment by larseggert** [comment]
Then they are violating the requirements of that version and won't get a response.

**Comment by larseggert** [comment]
@gorryfair?

**Comment by gorryfair** [comment]
So if this confused me (a little), I am assuming it could confuse others, so one way to make this clear is add a sentence (albeit a little long) after the SHOULD in section 6 that says what happens and explicitly includes a forward ref to Section 14.1 i.e.

AFTER THIS CURRENT TEXT:    “The size of the first packet sent by a client will determine whether    a server sends a Version Negotiation packet.  Clients that support    multiple QUIC versions SHOULD pad the first packet they send to the    largest of the minimum packet sizes across all versions they support.    This ensures that the server responds if there is a mutually    supported version.” 

ADD SOMETHING LIKE:     "If a client sends an Initial packet (see section 14.1) less than the smallest allowed  packet size for the version of QUIC supported at the server  (e.g., when this size is not permitted by the local interface),  the server would not reply with a Version Negotiation packet and the connection attempt will time out.

**Comment by martinthomson** [comment]
> A server might not send a Version Negotiation packet if the datagram it receives is smaller than the minimum size specified in a different version.
?

**Comment by gorryfair** [comment]
I think you know what to  expect, to me the text just needs to explain what you expect can happen.

**Comment by larseggert** [comment]
@gorryfair does #4058 resolve this issue for you?
