### ISSUE TITLE
Try again to use ECN?

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4029]
(Broken out of #3214.)
>   Even if validation fails, an endpoint MAY revalidate ECN on the same
>   path at any later time in the connection./
- That’s possible, meaning try again to use ECN? I think the text needs to be clearer, that this can be used to enable ECN to be used within the connection.

**Comment by larseggert** [comment]
@gorryfair are you OK with #4037?

**Comment by gorryfair** [comment]
I think PR 4037 needs surgery. The intent seems pretty clear. I believe root cause of the comments originate from text that isn't perfected. There's lots of colloquial terminology mistakes wrt ECN, some repetition, a few para ordering problems  and few sentences needing polish. If we fix all these then maybe (nearly) all the issues will disappear. 

@martinthomson ... can I offer to edit the PR text in this section?

**Comment by martinthomson** [comment]
Suggestions for text would be greatly appreciated.

**Comment by larseggert** [comment]
@gorryfair could you send text soon, please?

**Comment by gorryfair** [comment]
This text is being discussed in a PR #4059

**Comment by larseggert** [comment]
@gorryfair since #4059 is merged now, can we close this issue?

**Comment by martinthomson** [comment]
Let us do that, yes.
