### ISSUE TITLE
Misleading advice on stream-related errors

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#4123]
The spec says:
> Errors that result in the connection being unusable, such as an obvious violation of protocol semantics or corruption of state that affects an entire connection, MUST be signaled using a CONNECTION_CLOSE frame (Section 19.19). An endpoint MAY close the connection in this manner even if the error only affects a single stream.

First of all, I have no idea what a "corruption of state" is supposed to be.
More importantly, the second sentence seems to suggest that if an error only affects a single stream, it might not be required to send a connection-level error. I'm thinking of a stream-level flow control violation.

**Comment by LPardue** [comment]
The challenge here is that the transport doesn't define how streams can be used by application layer protocols, but seems to want to strongly encourage how an application uses error codes. An example of "corruption of state" is something like a QPACK error that renders the HTTP/3 connection unusable because the QPACK state cannot be assured. In contrast, an application might treat receiving a header with an uppercase field name as a stream error that otherwise would not affect the rest of the H3 connection.

**Comment by larseggert** [comment]
Anything remain to be done here?

**Comment by marten-seemann** [comment]
It seems like @LPardue is interpreting this sentence as only applying to application protocol errors. If that's the intention, we should make that clear:
> Errors that result in the connection being unusable, such as an obvious violation of application protocol semantics or corruption of application protocol state that affects an entire connection, MUST be signaled using a CONNECTION_CLOSE frame (Section 19.19). An endpoint MAY close the connection in this manner even if the error only affects a single stream.

**Comment by MikeBishop** [comment]
It's not exclusive to the application.  Another example of corrupt state at the transport layer is CRYPTO_BUFFER_EXCEEDED -- you had to drop some bytes, so now your TLS handshake state is corrupted.

As to the second piece, I think you're reading that backward.  A stream error MAY always be promoted to a connection error if the implementation decides it's severe enough; it doesn't say anything about deciding to downplay errors if they're localized.  If an error is defined to be a connection error, it's a connection error.  If it's defined to be a stream error, however, you're always allowed to decide it's the last straw and walk away.

**Comment by ianswett** [comment]
QUIC transport does not have stream-level errors, though applications can.  As such, the last sentence references a circumstance that does not exist in the transport draft.  So the best solution seems to be to remove the last sentence.

**Comment by janaiyengar** [comment]
@marten-seemann : to your two points:
- "corruption of state that affects an entire connection" is clear that if the connection state is affected then it should result in a connection error
- agree that the second sentence seems unnecessary entirely, since stream-level errors are always treated as connection errors within the transport.
