### ISSUE TITLE
Recovery-31: Use of <CODE BEGINS> and <CODE ENDS> tags

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#4177]
The recovery draft have significant amount of pseudo code. Per the IETF trust legal provision (TLP) (https://trustee.ietf.org/license-info/IETF-TLP-5.pdf) code components have a specific license. The TLP is also clear that anything enclosed in `<CODE BEGINS>` and `<CODE ENDS>` is to be considered code components. Thus for clarity of identification I would propose that the psudocode in this document uses these tags.

**Comment by larseggert** [comment]
Does this also apply to pseudocode? Because the TLP defines code as "intended to be directly processed by a computer", which this pseudocode cannot be.

**Comment by janaiyengar** [comment]
I have the same question as Lars. https://trustee.ietf.org/license-info/Code-Components-List-4-23-09.txt does not seem to include pseudo code.

**Comment by MikeBishop** [comment]
However, that list *does* include ABNF and TLS Presentation Language, which raises the question of whether it applies to our bespoke packet layout language.

**Comment by martinthomson** [comment]
The provisions specifically say:

> Text  in  IETF  Contributions  and  IETF  Documents  of  the  types identified in Section 4.a above shall constitute “Code Components”.

So we don't need to annotate any ABNF or TLS Presentation language this way.  It's automatically licensed as code.

For the pseudocode, explicitly licensing it under the code license would be good.  Using the annotations would not be.  There has to be a better way.  Perhaps we could use words.  Or, we could ask for a change to the XML format so that any block of preformatted text could be annotated with a code license.  I'm sure that would be popular.

@MikeBishop, we could ask the trust to add the packet layouts to their list, but it is explicitly and deliberately not code:

> The purpose of this format is to summarize, not define, protocol elements.

**Comment by janaiyengar** [comment]
The license might provide some extra protection, but do we think the pseudo code needs this? @martinthomson: Can you say more about why you think explicitly licensing the pseudo code is good?

FWIW, we don't have to do the tags, we can simply call it out in the pseudo code section:
```
b. Identification. Text in IETF Contributions and IETF Documents of the types
identified in Section 4.a above shall constitute “Code Components”. In addition, any text found
between the markers <CODE BEGINS> and <CODE ENDS>, or otherwise clearly labeled as a
Code Component, shall be considered a “Code Component”.
```

**Comment by martinthomson** [comment]
The license terms for text aren't that great.  The code license is intended to allow for extraction and modification in ways that the text does not.  As the pseudocode has already been extracted and modified (and deployed based on that), we should probably ensure that the more liberal license formally applies.

So yes, let's just add text saying "the pseudocode in this document is licensed as a "Code Component", see [blah]."

**Comment by janaiyengar** [comment]
We'll need to include the BSD boilerplate, right?

**Comment by martinthomson** [comment]
I feel like I'm doing a bad impersonation of a lawyer now...

4.e says "it is permissible", not "it is required", so I assume that the 6.d quote is not required in order to relicense.  My reading of 4.c is that the simplified BSD license applies with or without that notice:

> In  addition  to  the  licenses  granted  under  Section  3, unless  [...],  such Code  Components  are  also  licensed  to  each  person  who  wishes  to  receive such a license on the terms of the “Simplified BSD License", as described below.

So it is, I believe, sufficient to identify the pseudocode as a Code Component.

**Comment by MikeBishop** [comment]
The boilerplate text already includes the license reference:

> This document is subject to BCP 78 and the IETF Trust's Legal Provisions Relating to IETF Documents (https://trustee.ietf.org/license-info) in effect on the date of publication of this document. Please review these documents carefully, as they describe your rights and restrictions with respect to this document. Code Components extracted from this document must include Simplified BSD License text as described in Section 4.e of the Trust Legal Provisions and are provided without warranty as described in the Simplified BSD License.

So you simply need to identify the section in question as a Code Component, I think.

**Comment by janaiyengar** [comment]
@gloinul : Can you see if #4189 is adequate?

**Comment by gloinul** [comment]
@janaiyengar I think so.
