### ISSUE TITLE
Specify how new connection IDs will be supplied to a connection

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#427]
When a client experiences a "privacy preserving(or theatening) event", it may want to change connection id and start with a non-linkable packet number.

I suggest we add a frame to allow the server to supply new connection IDs, and include an indication that the server requests the client change it's connection ID immediately.

The document must also specify how the IV for the new connection ID should be constructed, in order to ensure the IV is not re-used and both peers agree on the IV.

**Comment by RyanAtGoogle** [comment]
I thought that packet number was always the IV. Since two different
messages must not be encrypted with the same key/IV, this means that the
same packet number must not be used for different messages. As such, I
assumed that the new packet number would need to be larger than the
previously used packet number. Are you thinking we'd use different keys for
the new connection ID?

**Comment by mcmanus** [comment]
dup of #232 ?

**Comment by ianswett** [comment]
Closed as dupe of #232
