### ISSUE TITLE
Two paras are quite confusing

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4271]
>  QUIC depends upon a minimum IP packet size of at least 1280 bytes.
  This is the IPv6 minimum size ([IPv6]) and is also supported by most
  modern IPv4 networks.  Assuming the minimum IP header size of 40
  bytes for IPv6 and 20 bytes for IPv4 and a UDP header size of 8
  bytes, this results in a maximum datagram size of 1232 bytes for IPv6
  and 1252 bytes for IPv4.
>
>  The maximum datagram size MUST be at least 1200 bytes.

The previous two paras are quite confusing. I think the first para refers
to the max packet size in the network layer, but the second para is not clear,
nor is the next para.

**Comment by martinthomson** [comment]
The paragraph preceding the first is this:

> The maximum datagram size is defined as the largest size of UDP payload that can be sent across a network path using a single UDP datagram.

So it is clear what the second paragraph means.  QUIC doesn't operate if the network is incapable of carrying a datagram payload of 1200 bytes.  I think that rewording that way might help.

What is less clear is where the extra 32 (or 52) bytes go.  In that we've been very generous in providing for header extensions or UDP extensions.  But I don't see a need to explain that aspect.

**Comment by Ralith** [comment]
I found this to still be very confusing, FWIW. It's unclear why the limit would be 1200 bytes when the text very clearly explains that at least 1232 can be relied upon, or alternatively why the text claims "QUIC assumes a minimum IP packet size of at least 1280 bytes." when in fact it appears to only mandate a 32 bytes smaller figure. It reads like someone forgot to update a constant.

@martinthomson above suggests that this was intentional, to leave space for unspecified future use by lower layers. I think *some* allusion to this is justified, just to clarify the otherwise seeming inconsistency.
