### ISSUE TITLE
Reclaiming is very hard

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4275]
>22.1.1.  Provisional Registrations
>
>  Provisional registration of codepoints are intended to allow for
  private use and experimentation with extensions to QUIC.  Provisional
  registrations only require the inclusion of the codepoint value and
  contact information.  However, provisional registrations could be
  reclaimed and reassigned for another purpose.

Experience in other WGs suggests that reclaiming is very hard. We really
needed to do this in MPLS where we had a 16 value field and found it impossible.

**Comment by martinthomson** [comment]
This is not an issue.  I agree that it could be hard, but that doesn't mean that we shouldn't allow for the option.  And we expect the need for reclamation to be low.  I suggest that we close this with no action.

**Comment by StewartBryant** [comment]
Given that you do not think it is likely to be used, and given that in MPLS we tried this and found it to be very hard, why not remove the text?

**Comment by martinthomson** [comment]
We have been successful in recovering the port number that this protocol uses.  So we have a clear example of where reclamation was successful and useful.

That was made much harder due to a lack of an understanding about reclamation.  Being clear up front should help avoid problems.

Proposing no action here.

**Comment by StewartBryant** [comment]
On 5 Nov 2020, at 23:04, Martin Thomson <notifications@github.com<mailto:notifications@github.com>> wrote:



We have been successful in recovering the port number that this protocol uses. So we have a clear example of where reclamation was successful and useful.

That was made much harder due to a lack of an understanding about reclamation. Being clear up front should help avoid problems.

Proposing no action here.


The degree of difficulty depends on the scale of heterogeneous implementations and the scale of deployment.

Leave the text in if you wish, we will see what happens.

In MPLS we wanted to reclaim a reserved label. There are only 16 of them and so they are valuable. We had one that was barely deployed and was in disuse that we wanted to repurpose., Although we tried hard we were unable to reclaim it.

Stewart

**Comment by janaiyengar** [comment]
We have far more values, so in practice this should not be an issue. I agree that we don't want to close out the possibility of reclaiming.

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel. 

Hearing no pushback, I'm closing this.
