### ISSUE TITLE
Port 443 and IANA ports

### ISSUE THREAD

**Issue by zwoop** [quicwg/base-drafts#428]
While discussing QUIC with some network vendors, a concern was brought up that technically, port UDP port 443 is already assigned. From

https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=8

```
https	443	tcp	http protocol over TLS/SSL	[Kipp_E_B_Hickman]	[Kipp_E_B_Hickman]						
https	443	udp	http protocol over TLS/SSL	[Kipp_E_B_Hickman]	[Kipp_E_B_Hickman]		
```

Yes, seems silly and nit picky, but I'm wondering if it'd make sense to try to get 443:UDP assigned to HQ ? The vendor concern is that adding support for special handling of UDP packets on port 443 would have to be absolutely guaranteed to be QUIC. At least that's what I've been told.

The other option would be to add an identifier to every QUIC packet, such that they can uniquely identify it as such.

**Comment by ianswett** [comment]
IETF QUIC will be HTTP over TLS 1.3 on UDP 443, so I believe that would fit into the current IANA spec?

**Comment by zwoop** [comment]
I think the concern was (but I can check again) that we're sort of hijacking this :). I can't think of anyone or anything that would have used "HTTP over UDP" before, but technically I think they are right in that the port was reserved for that.

I think what might appease these guys is if the RFC explicitly specifies that from hereon, QUIC UDP:443 is "HTTPS over UDP" as registered years ago by the IANA. :)

**Comment by larseggert** [comment]
As @ianswett said, QUIC's use of 443/UDP is inline with the current registration. And we're not hijacking this. Just because [Kipp E.B. Hickman](http://home.mcom.com/people/kipp/) is the assignee here does not mean nobody else can use the port for the given protocol. (443/TCP is also assigned to him, and nobody is worried that H2 over TCP has a problem.)

If we *wanted* to, we could see if he is still around and willing to return the ports to be assigned to the IESG. I suspect it is an individual assignment (and not one to the IESG), because the assignment likely predates the first RFC on SSL way back when.

**Comment by MovGP0** [comment]
The port number is defined by the transport layer protocol (ie. UDP+TLS has port 443). QUIC is an application layer protocol and therefore does not define or effect the port number.

**Comment by bemasc** [comment]
I think we can avoid this problem by not implicitly recommending a fixed port number: https://github.com/quicwg/base-drafts/pull/424

There's no need for a fixed port number anyway, due to the Alt-Svc bootstrap.

**Comment by larseggert** [comment]
There is no problem with running QUIC on UDP/443, and there is no issue with saying that this is recommended or allowed.

**Comment by MikeBishop** [comment]
#424 should have a corresponding issue, and this could be it.  As I read it, the goal is to avoid ossification of the HTTP/QUIC port number by advocating that origins *not* use a consistent port number.  Since Alt-Svc can point you to any port number, unless we have evidence that UDP port numbers are already highly ossified, I don't see an issue with not using 443 for most use-cases.

We would want a default port associated with a new scheme (#253), but we don't yet have that and that wouldn't be the common case regardless.

**Comment by martinthomson** [comment]
I think that both @ianswett and @larseggert covered this.  It will be HTTP on port 443.  However, we should try to officially claim that registration, or at least acknowledge it.

#424 suggests a very different outcome.  It suggests that 443 is at best a convenience, and at worst a horrible error on the part of Google.  On the latter, that would be because the ossification has already happened (I'm not sure if this is true, or that the choice of 443 was unwise, but you can see the logic that leads to that conclusion).

**Comment by larseggert** [comment]
I will contact IANA and see what the options are to get the port assigned to QUIC.

**Comment by mnot** [comment]
FYI: I'm in a discussion both with the current assignee and the IESG about this. Stay tuned.

**Comment by Habbie** [comment]
Any news on this?

**Comment by larseggert** [comment]
Yes, it's assigned to the IESG now: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=443
