### ISSUE TITLE
It would be helpful to explain why

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4293]
>  The server includes a connection ID of its choice in the Source
  Connection ID field.  This value MUST NOT be equal to the Destination
  Connection ID field of the packet sent by the client.

It would be helpful to explain why

**Comment by martinthomson** [comment]
In short, this allows us to ensure that a middlebox can't spoof Retry packets.

That's a simple explanation, but to write that down is tricky because in a specification you then need to explain *how* the different pieces fit together to achieve this.  That draws in a bunch of other bits.  This includes the particulars of connection ID negotiation and the function of the connection ID transport parameters.  In this case, we determined that the cost of including the justification exceeds the value.

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel. 

Hearing no pushback, I'm closing this.
