### ISSUE TITLE
Identifier of the form "31 * N + 27"

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4294]
>18.1.  Reserved Transport Parameters
>
>  Transport parameters with an identifier of the form "31 * N + 27" for
  integer values of N are reserved to exercise the requirement that
  unknown transport parameters be ignored.  These transport parameters
  have no semantics, and may carry arbitrary values.

Which hat did that come out of? It would be helpful to the reader to
explain the rational.

**Comment by marten-seemann** [comment]
That would be me. I made them up.
No hidden message here, sorry to disappoint!

**Comment by MikeBishop** [comment]
Multiples of 31 ensures that they don't have a consistent bit signature but instead cycle through all of them; the 27 offset jumps over the region where we're defining things used in the core spec.

But the point is actually that the reader not need to understand the rationale, because the recipient should simply ignore unknown values like they're defined to.  Only the sender needs to be able to generate these, and this formula is a simple way to generate a value.

**Comment by StewartBryant** [comment]
Why not add a note of the type that you provide in the first sentence so that other readers do not similarly wonder?

**Comment by janaiyengar** [comment]
The rationale here is weak enough that it could be considered to have come out of a hat, which is quite fine for this use. If we had chosen a different expression, we would have slightly different transport params.

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel. 

Hearing no pushback, I'm closing this.
