### ISSUE TITLE
secdir review of -recovery

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4324]
Derrell Piper writes:

> Reviewer: Derrell Piper
> Review result: Ready
> 
> I have reviewed this document as part of the security directorate's ongoing
> effort to review all IETF documents being processed by the IESG.  These
> comments were written primarily for the benefit of the security area
> directors.  Document editors and WG chairs should treat these comments just
> like any other last call comments.
> 
> The summary of the review is: Ready, with an optional nit.
> 
> This document is QUIC's Loss Detection and Congestion Control and is part of
> QUIC Last Call.
> 
> Pp. 7, "after the epoch starts is acknowledged" should maybe be singular,
> unless the intent is literal and I'm missing what a "starts" is.
> 
> There's no explicit security going on here, other than in the larger picture
> of QUIC itself, namely that in QUIC-TLS and QUIC-TRANSPORT; this is only its
> congestion control.  However, Security Considerations correctly highlights
> some of the major traffic analysis concerns with QUIC and congestion control
> in general, and there are some, but these are not unique to QUIC, nor would
> they likely be addressed inside of congestion control, so this is okay.  It
> seems well written and based on a practical understanding of existing TCP
> congestion control along with current academic research on this topic.

**Comment by martinthomson** [comment]
The one nit here regards this sentence:

> QUIC starts a loss epoch when a packet is lost and ends one when any packet sent after the epoch starts is acknowledged.

This seems right to me.  You might rewrite this as:

> QUIC starts a loss epoch when a packet is lost. A loss epoch ends one when any packet sent after the start of the epoch is acknowledged.

But I don't think that is appreciably better.  I think we can close this with no action unless we get some enthusiasm for rewording.

**Comment by MikeBishop** [comment]
I think the issue is that "epoch starts is" looks like either an extra word or subject/verb agreement error.  It's not actually; if you diagram the sentence out, "after the epoch starts" is in a dependent clause and "any packet ... is acknowledged" is correct agreement.

That said, the rewording is easier to read because it doesn't *look* wrong and you don't have to try different possible parsings in your head before you find the one which works.  We've tried to avoid trial decryption; let's avoid it in grammar, too.
