### ISSUE TITLE
Reserve fewer codepoints for greasing

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#4387]
I just sent [an email](https://mailarchive.ietf.org/arch/msg/quic/0wt2N8v7GHX_6vRRRH2uSy4T4LE/) suggesting that we adopt a different formula to the one we currently use for identifying grease codepoints.

The current formula, `27+31N` takes a lot of codepoints.  This means that if someone deploys real code that depends on this value, the odds of a collision between that usage and real grease might be too low.  A different scheme with a higher risk of collision might avoid accidents that might ultimately render greasing ineffective.

**Comment by LPardue** [comment]
I believe this would require a design change. I've not seen enough support yet to take it on board as a design issue.

**Comment by huitema** [comment]
I wonder whether changing the formula would make any practical difference. One of the motivations for Martin's message is pushback from IANA, who apparently are not too happy about having to check a formula during the registration process. But replacing the formula by a different one would not be a big relief for IANA. We also don't want to just declare ranges of code point used only for greasing, because that would defeat the idea of greasing.

I think the simplest solution is to not change the formula, but place the onus of checking it to the registrant instead of IANA. For example, if a registrant is foolish enough to ask for codepoint number 3127, IANA will just assign it, but the registration will not have much value.

**Comment by ianswett** [comment]
Lower odds of collision are a mixed blessing.

One modification to consider is making N >= 2, since that leaves all the 1 byte codepoints unused, and those are particularly valuable.

**Comment by larseggert** [comment]
If people want to argue for that change, they need to do so now.

**Comment by martinthomson** [comment]
I'm prepared to let this lie in favour of making progress.

**Comment by janaiyengar** [comment]
Don't have a good emoji for `sacrifice`, but found these - 🐐 🔪
