### ISSUE TITLE
tls: EndOfEarlyData in Initial/Handshake/1-RTT

### ISSUE THREAD

**Issue by kazu-yamamoto** [quicwg/base-drafts#4410]
Sec 4.5 says:

> Clients MUST NOT send the EndOfEarlyData message. A server MUST treat receipt of a CRYPTO frame in a 0-RTT packet as a connection error of type PROTOCOL_VIOLATION.

This does not specify how a server MUST do if `EndOfEarlyData` in Initial/Handshake/1-RTT is received. I think that a server MUST send the TLS alert of `unexpected_message`.

**Comment by marten-seemann** [comment]
Sounds reasonable to me.

**Comment by kazuho** [comment]
I'm not sure if we need to change, or if the proposed change is reasonable.

Doesn't RFC 8446 already state that the receiver MUST error-close the connection when it receives EndOfEarlyData in other epochs? Assuming that that is the case, I think that the current text is correct, because the section talks about "QUIC-Specific Adjustments to the TLS Handshake."

**Comment by kazu-yamamoto** [comment]
The draft also says:

> Endpoints MUST treat the receipt of a TLS KeyUpdate message as a connection error of type 0x10a, equivalent to a fatal TLS alert of unexpected_message.

What is the difference between KeyUpdate and EndOfEarlyData?

**Comment by kazuho** [comment]
@kazu-yamamoto I'd argue that the only way to interpret that text is that the KeyUpdate message cannot be used _even when permitted by TLS 1.3_ (i.e. in 1-RTT packets). The italic part is implied, rather than explicitly stated like the case for EndOfEarlyData.

If there's ambiguity, we can try to be explicit. I do not have a strong opinion on if we need to.

**Comment by kazu-yamamoto** [comment]
To let readers interpret the text as "cannot be used", we should simply use "cannot be used". If "MUST NOT" is used, the handling should be specified.

**Comment by kjsisco** [comment]
I do not think anything should change personally.

**Comment by kazuho** [comment]
FWIW I've filed #4412 that does not do anything regarding the original issue, but makes changes to the specification regarding KeyUpdate to clarify that it is not intended to respecify how TLS rejects that message during handshake.

**Comment by LPardue** [comment]
Marking as editoiral. If I'm wrong please speak up.
