### ISSUE TITLE
BLOCKED semantics

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#452]
It's possible that we don't care about the reliability of BLOCKED, but there is an inherent problem with the frame.

The quality of a signal like this is either in being able to capture the conditions that lead to it being generated, maybe in terms of looking at traces.  Or, it can be useful hollistically: by aggregating reports over a large set you can determine whether a change to flow control tuning was successful.

A sender of BLOCKED is currently obligated to retransmit lost BLOCKED frames.  That achieves the latter goal reasonably well, but it does little for the former because the state of the connection when BLOCKED was generated is unlikely to be the same when it is eventually retransmitted.  Even on the first transmission, the receiver of a BLOCKED frame still has to do quite a lot to work out what the state of the sender might have been.

BLOCKED would be more useful if it reported the limit that caused it to be generated.  That would also solve #451.

**Comment by mnot** [comment]
Is this close enough to #65 to be a dup?

**Comment by martinthomson** [comment]
No, #65 is "should we mandate the generation of BLOCKED".  This is "BLOCKED gives poor information and it could be improved".

**Comment by igorlord** [comment]
The text in #510 does not clarify whether retransmission of a lost BLOCKED frame is required or, if not, when it is allowed.  (Same applies to STREAM_BCLOKED.)  I can see three options:

1. _Retransmission is always required_.  This only makes sense, if the sending of BLOCKED is a MUST. Otherwise, it is inconsistent to require retransmission of an optional frame.  Required retransmission can help with aggregate statistics as to how much blocking there was during the lifetime of the connection. However, this may not give clear info to the receiver as to the current state of the stream/connection.

2. _Retransmission is required only if the sender is still blocked on the same data limit._  This also only makes sense, if the sending of BLOCKED is a MUST. This gives the receiver a bit better view into the state of the sender's stream but may lose "blocked" events.

3. _Retransmission is always allowed (not to required)_. This only makes sense, if the sending of BLOCKED is optional (and should probably be used with the same level of optionality -- SHOULD or MAY). This is probably the most confusing option -- the receiver cannot use this either for the view of sender's connection state or for accurate accounting of "blocked" events.

4. _Retransmission is allowed (but not required) only if the sender is still blocked on the same data limit._  This also only makes sense, if the sending of BLOCKED is optional. This will behaves like a debug frame, which may be helpful in traces.

Also, while we are at it, BLOCKED (and its cousens) could benefit from a field with an explicit value of the data limit that triggered the "blocked" condition.  It may also benefit from a field with the desired data limit (i.e. how much data the sender could send, if it were not blocked by the flow control).

**Comment by martinthomson** [comment]
BLOCKED is "retransmitted", because all frames that don't have retransmission rules are retransmitted.

You are right however to note that there is less value in indicating that you are blocked when that state ends.  That's a different problem to the one that I was attempting to address, though the solution that I suggest might go some way to addressing your concerns.
