### ISSUE TITLE
Use positive phrasing instead of double negative

### ISSUE THREAD

**Issue by sebdeckers** [quicwg/base-drafts#477]
The setting `SETTINGS_DISABLE_PUSH` is set to `false` by default. This double negation seems needlessly confusing. (*"Setting the push setting to true turns off push?"*)

Suggestion: Renaming it to `SETTINGS_ENABLE_PUSH` and default to `true`. This is easier to understand and matches the parameter defined by HTTP/2.

**Comment by MikeBishop** [comment]
The problem is that we've defined Boolean settings in general to be false if not sent, true if sent.  So to have it be "enable push," it either needs to default off or we need to change the polarity of all Boolean settings.  I don't think changing the polarity of settings is an acceptable option since HTTP allows definition of arbitrary settings by extensions, all of which would need to be off by default unless a client supports the extension.

I'm fine switching it back to ENABLE_PUSH and requiring that an extra few bytes be spent if you want things pushed to you, though.  Any objections?

**Comment by martinthomson** [comment]
Given that this is the client, which is expected to add padding in the relevant packet, the extra bytes won't be increasing the size of anything.
