### ISSUE TITLE
Éric Vyncke's QPACK Comment 1

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4774]
@evyncke said

> I have only one generic comment, did the WG look into the Static Context Header
> Compression out of the LPWAN WG ? As there are similarities.

**Comment by dtikhonov** [comment]
I do not believe we did.

**Comment by MikeBishop** [comment]
No, we didn't.  It's possible there would be some concepts we could have borrowed, but from a cursory examination, SCHC appears to be a framework for building a compression scheme rather than a concrete compression scheme.  Given the focus on reducing individual bits and bytes out, I'm not sure whether we would have adopted that framework.

Regardless, I don't believe this requests a change to the document.

**Comment by evyncke** [comment]
No changes are required indeed as it is way too late.

It is symptomatic though that WG are isolated one from the other. Sigh... Nothing specific to QUIC though

-éric

________________________________
De : Mike Bishop <notifications@github.com>
Envoyé : mercredi 20 janvier 2021 21:04
À : quicwg/base-drafts <base-drafts@noreply.github.com>
Cc : Eric Vyncke <eric@vyncke.org>; Mention <mention@noreply.github.com>
Objet : Re: [quicwg/base-drafts] Éric Vyncke's QPACK Comment 1 (#4774)


No, we didn't. It's possible there would be some concepts we could have borrowed, but from a cursory examination, SCHC appears to be a framework for building a compression scheme rather than a concrete compression scheme. Given the focus on reducing individual bits and bytes out, I'm not sure whether we would have adopted that framework.

Regardless, I don't believe this requests a change to the document.

**Comment by LPardue** [comment]
Given that QPACK's precursor, HPACK, was published in 2015 https://tools.ietf.org/html/rfc7541 I'm surprised to see that SCHC has no mention of it ;-)

**Comment by MikeBishop** [comment]
I agree, and it's one of the things that concerns me about certain WGs forgoing meeting during IETF week and having interims instead; there's even less awareness of what other WGs are working on and where they can overlap.  I do wish there'd been contact in either direction sooner, in case either group had ideas the other could have used.  But here we are.

**Comment by dtikhonov** [comment]
On the bright side, I don't think SCHC would be applicable to HTTP/3 (or at least not be an improvement over HPACK).

**Comment by LPardue** [comment]
Since we agree no action is required, closing the issue.
