### ISSUE TITLE
Murray Kucherawy's QPACK Comment 1

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4797]
@@mskucherawy said

> In Section 2.1.3, I suggest "SHOULD avoid writing" ought to be "SHOULD NOT
> write". (For that matter, I don't know why this isn't a MUST NOT.)

**Comment by afrind** [comment]
I think we can change to SHOULD NOT.  I'd rather not be so prescriptive here, since a QPACK implementation might well cut this corner and ignore flow control constraints and rely on higher levels of the stack to ensure the necessary flow control is available?  I guess I could be convinced otherwise.

**Comment by larseggert** [comment]
@mskucherawy?
