### ISSUE TITLE
Long and short packet type 00?

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#487]
Packet types start at `01` for packets with both long and short headers.

Is `00` reserved? If yes, the draft should say this and indicate so in the tables.

Or is this a bug and types should start at `00`?

**Comment by janaiyengar** [comment]
Yes, good point. I avoided 00 since I figured it might be special enough to
avoid warranting. I'll add some text.

**Comment by martinthomson** [comment]
I don't think that we want to reserve these.  Nor do I think that it needs special mention.  We just decided not to use them.

I hear that there are some deployments that route a packet containing a zero octet at the front to other places.  I don't think that we need to endorse that sort of behaviour, but avoiding `00` is cheap.

**Comment by larseggert** [comment]
Well, those deployments are going to have an issue if we ever assign packet type `00`. Hence it may be better to reserve? (Or are these deployments also using a custom QUIC version?)

**Comment by martinthomson** [comment]
They are currently using a custom version number.  Note that we moved the version number field in some pretty strange ways, so those folks will have a whale of a time sorting out an upgrade path.

**Comment by janaiyengar** [comment]
The case I'm familiar with is not a QUIC version but a different protocol that uses 00 in the first octet on the same port (443) as a classifier. Since it's specific to a listener on port 443 that receives this other protocol and also QUIC packets, it's easier to avoid 00. In general, my thinking is that 00 is always special to someone, and avoiding 00 in the first octet may be good sense.

**Comment by martinthomson** [comment]
OBE
