### ISSUE TITLE
Rename connection id

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#502]
@britram points out that this ceased to be an identifier some time ago. That doesn't mean that the name needs to change. We all seem capable of dealing with this minor disconnect, after all. But we might want to at least consider giving some thought to finding a more appropriate name. 

This is bike shed territory. I expect that editors will ultimately have to exercise discretion.

**Comment by britram** [comment]
Either way. I decided to mention it after a discussion with a student here doing some implementation. His design showed evidence of confusion about what this value was for, an effect of taking the implication of identifier semantics as literal and ironclad.

This is editorial, a document usability issue, but I think we have an opportunity here to influence the kinds of errors that will come up in implementations from the document.

**Comment by martinthomson** [comment]
You aren't the only one to have encountered the problem.

**Comment by janaiyengar** [comment]
I'll admit to not having encountered this problem. What do you think Connection ID is?

**Comment by martinthomson** [comment]
*I* think that the connection ID is just something you put in a packet that allows it to end up in the right place.  Other people attribute greater stability and significance to it.  That is that it identifies the connection.  It doesn't.

**Comment by janaiyengar** [comment]
There's nothing in the word "identifier" that suggests immutability or that it's the only one. Connection ID identifies connection state at the endpoints and the serving process at load balancers, so it'd be odd to call it anything else.

**Comment by martinthomson** [comment]
There's a common misconception that there is a one-to-one mapping between a thing and its identifier.  For instance, a legal name for a person.

An "address" has all the properties you describe, as does a "locator".  So does an MPLS flow label.  I'm not saying that these are better names, just that there are alternatives that don't have the same baggage.

**Comment by janaiyengar** [comment]
yes, agreed that they're not better - they all have baggage :-)

**Comment by larseggert** [comment]
The CID (or actually sequence of CIDs a connection may use) identifies the connection to the endpoints - but no longer to the network. Maybe stating that somewhere would be helpful?

**Comment by britram** [comment]
+1 to @larseggert -- "connection ID" can tend to imply more than we mean about what it's for.

<bikeshed> I'm a fan of "*something* token" for this design pattern, personally: it's a thing I give you which I expect you to give me back at some point, there's some contract that specifies what I do for you when you give it back to me, but otherwise what I do with it is completely opaque to you. I don't have any good, light-travleing suggestions for *something* though. :/ </bikeshed>

**Comment by larseggert** [comment]
Why is *something* not *connection*? I think the confusion may stem from the word *identifier*, not the word *connection*.

**Comment by britram** [comment]
Hm, indeed. Certainly much more confusion stems from "identifier". I'd be happy with "connection token".

**Comment by ekr** [comment]
I'm actually with Jana here.

If we move to a one-CID per packet, I might feel differently.

**Comment by janaiyengar** [comment]
You can have many identifiers for the same thing. There can't be collisions, and that's true of connection IDs. A connection ID maps to a sequence of n packets.

Different folks can imagine it becoming different things. You can think of it as Blah ID (since it identifies something -- a flowlet? a packet? -- we don't know what), or Connection Blah (since it is associated with the connection, we don't know exactly how... perhaps it identifies the entire connection, perhaps it doesn't.)

I think stating that it's a Connection ID, and a client MAY change it over the lifetime of a connection from none to several times is adequate signal to anyone thinking about how to use it.

**Comment by ianswett** [comment]
If we'd like to be a bit more accurate, it seems like Path ID would be a good option.  We could also head towards something like 'routing token', but that seems more confusing than helpful to me.

**Comment by ekr** [comment]
I suggest we hold off on this terminology issue until we resolve whether we are going to be having a big pile of conn ids. If, for instance, we have a new one for each packet, we might want a different name

**Comment by martinthomson** [comment]
It seems like we're getting attached to this name now, and it works more or less if you consider the right audience.  If it is still a problem later, we'll know and can open a new issue.
