### ISSUE TITLE
ACK frame syntax

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#507]
- largest acked need not be > 32 bits, since Packet Number is at most 32 bits.
- ditto for ack block lengths

**Comment by larseggert** [comment]
So we're going to to 8/16/32 and leave the `LL` codepoint `11` unassigned?

**Comment by janaiyengar** [comment]
For the time being, since it's just silly to have a largest acked of 48 bits when the max packet number size is 32. The ack block lengths also need to be fixed to at most 32 bits since if you can't use more than 32 bits for packet number, you won't be acking > 2^32 packet ranges.

Feel free to suggest better ideas.

**Comment by martinthomson** [comment]
Split the last acknowledged size from the block length size and find the points in that space that make sense, e.g.,

0 = the last acknowledged is 8 bits, block lengths are 8 bits
1 = the last acknowledged is 16 bits, block lengths are 8 bits
2 = the last acknowledged is 16 bits, block lengths are 16 bits
3 = the last acknowledged is 32 bits, block lengths are 16 bits

I can't imagine that needing to acknowledge a block of packets that is more than 64k packets long without a single gap is very common.  That's a massive BDP with fantastic loss characteristics.

**Comment by ianswett** [comment]
We need largest acknowledged to go to 64 bits, because it's an absolute value, not relative to anything else.  I'm not sure an 8 bit largest acknowledged is that useful, so we could do 16/32/64, but most other things are 8/16/32/64, so I'd favor consistency.

64k is large, but given MTU's aren't increasing as quickly as bandwidth, I think we should enable a 32 bit block length.  A gigabit connection with a 1 second RTT is 89,000 1400 byte packets.

I think we have plenty of space for other frames anyway, so I'd favor changing the 48 bit length to 64 bits in both cases, since I can't come up with a good reason for 48 bits.

**Comment by mikkelfj** [comment]
Why does it have to be absolute? Can there be more than 2^31 bytes in flight? It might be resonable to have 2GB in flight for long fat pipes - but have all other frame formats and semantics been verified to not introduce any limitation here, if that is the case?

**Comment by ianswett** [comment]
I think there are good reasons to make it absolute, particularly to support connection migration and/or multipath.

The in flight limit is 2^31 packets, so >2TB with typical packet sizes, which is why we decided not to add a code point for 8 byte packet numbers in the public header.

**Comment by mikkelfj** [comment]
yes, I got confused about packet numbers and bytes - the absolute value is probably beneficial as you suggest and does not apparent harm - I still wonder if the 2^31 constraint elsewhere makes the benefit pointless though, or put in another way - perhaps there are other places that need to allow 64 bit values.

**Comment by mnot** [comment]
#644 is the ACK frame tracking issue.

**Comment by ianswett** [comment]
Closed by #877
