### ISSUE TITLE
Cleartext integrity as version independent

### ISSUE THREAD

**Issue by mcmanus** [quicwg/base-drafts#568]
making the cleartext integrity checksum version independent would prevent a lot of version negotiation packets from being generated based on receipt of non-quic (and make it harder to use that as an amplification vector?)

**Comment by martinthomson** [comment]
If version negotiation is amplifying, something is badly wrong.

I believe that version negotiation should only be generated for packets that exceed a certain size (because the only packet that it makes sense to send version negotiation in response to is an initial client packet and those are guaranteed* to be pretty big*).  That is, for some version of a guarantee and some version of big.  Note however that we don't have that written down (or even agreed).

As for being able to distinguish noise from QUIC, that's a good reason.  We should discuss that.

**Comment by mcmanus** [comment]
re: amp - that's a versioning guarantee thing again.. a v1 initial client packet is pretty big.. but a >1 packet received by a v1 server? we have very few rules about the future.. maybe we need a few.

**Comment by martinthomson** [comment]
Yes, some constraints on future flexibility seem wise, as long as we can keep it light.

**Comment by martinthomson** [comment]
I think that we resolved this with invariants and #724.  @mcmanus, explain and reopen if you disagree.
