### ISSUE TITLE
Number of loss detection timers

### ISSUE THREAD

**Issue by siyengar** [quicwg/base-drafts#575]
From my reading of the loss recovery draft, we have 1 timer per conn and then every time we send a packet, we reset the loss timer.

However let's say we're on a path where ACK packets keep getting lost and the sender is trickling packets on the connection just before the timer fires, it seems like we will never hit RTO at all since

OnPacketSent() always invokes SetLossDetectionAlarm() which will always keep advancing the deadline of the RTO timer.

Should we have multiple timers per packet to avoid this?

**Comment by ianswett** [comment]
Are you thinking of the case when all acks are getting lost?  If so, we should hit the CWND limit pretty quickly and start timing out.  If only some acks are getting lost, it shouldn't matter.

There is a bug in the current text I believe which is that SetLossDetectionAlarm() is using now in cases when it should be using time_of_last_sent_packet.  This could cause acks to unnecessarily delay TLPs.  That is fixed in PR #923

**Comment by siyengar** [comment]
I was more thinking of a case where we don't hit the cwnd limit quickly, that is packets are being trickled into the network by the sender just as the timer is about to fire., however thinking about it some more, this is a case which should probably not be in the realm of the loss detection, but of connection termination, the idle timer would fire and close the connection.

**Comment by ianswett** [comment]
Agreed.  I'm going to close this and we can track other improvements to the timeout text in PR #923 and if we can't figure out something there, we can open a new issue.
