### ISSUE TITLE
is_retransmittable semantics

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#591]
In draft-ietf-quic-recovery-03 there appear to me to be an overloading of the use of the "is_retransmittable" flag. It appears to be used both for the purpose to indicate if there is a frame that can and need be retransmitted and if that frame should be counted as lost and impact congestion control. I think these two purposes should be separated and clarified as being two different ones. The reason is that if we create extensions that will not require retransmission of frames but needs to be included in the congestion control response a significant rewrite would be needed. I also think it would clarify things for some of the control frames also if they should be included or not, even if not regularly retransmitted.

**Comment by ianswett** [comment]
Agreed that these concepts need to be separated.

I replaced is_retransmittable with is_ack_only in PR #780, because padding is not retransmittable, but does count towards bytes in flight.  My intent is to make everything that is not an ack only packet count towards bytes_in_flight.

But I think there's still some more editorial work to clarify the separation you describe.

**Comment by gloinul** [comment]
This is still not clear in -10, will keep it open.

**Comment by ianswett** [comment]
The plan is to rename this to needs_acknowledgement as well, because QUIC rarely retransmits frames and never retransmits packets.
