### ISSUE TITLE
Variable-length integers

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#595]
It's a big pain to have to look at the flag byte to know how long something should be.

**Comment by mikkelfj** [comment]
It would also free up a lot of room in the flag byte.

**Comment by ianswett** [comment]
I like this(#877) at a high level because it also fixes #423 (at least well enough for now) and is fast, easy to implement and space efficient.  It also expands the stream_id space, which I think is a good idea anyway.

As I said on the PR, I prefer the "num blocks" approach to the 0 as a terminator approach.  I noted you prefer the 'total length' approach, but I think that could become a real pain, especially once ECN and/or timestamps are added back in, so the length may be non-trivial to compute.  

Given the rest of this PR is heading in a good direction, I'd rather keep the core format of the ACK frame as similar as possible for now by doing num blocks and then we can discuss a complete relayout of the ack frame in a different issue/PR.

**Comment by martinthomson** [comment]
Sure, the change to num blocks is trivial.  I figured that either approach was equally bad, so went with one that would allow the parser to move on faster, but I am willing to go either way on this one.

**Comment by mikkelfj** [comment]
I agree with Ian - there are complexities with going with a length based solution when dealing with optional sub-frames so as is, I prefer  any solution that is not length based.

But it is not unhead of to have a length based solution where each subframe exists if the length is longer than most recently parsed subframe, but obviously that necessitates a termination of that subframe. Thus, each subframe typically has its own length. One of the IoT protocols do this, perhaps it is MQTT. However, it is likely to consume more space.

In isolation, it is also not a good idea to add a length based solution. If it is done, all other frames ought to be revisited, which would be some additional work to ensure the length can be understood without understanding the full frame.

I would generally like to see a solution where a frame could be skipped by just reading its header as opposed to requiring a full stream parser. It forces implementations to separate parsing from actions which may be architecturally nice, but introduces temporary data structures to handle the parse output. But, it will likely consume more space overall.
