### ISSUE TITLE
Public Resets should be triggered by only QUIC packets

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#599]
We don't want an endpoint to send Public Resets in response to random non-QUIC packets.

**Comment by mcmanus** [comment]
related to the "we don't want an endpoint to send version negotiation in response to random non-quic packets" (that look like long headers of an unknown version)

**Comment by mikkelfj** [comment]
> related to the "we don't want an endpoint to send version negotiation in response to random non-quic packets" (that look like long headers of an unknown version)

It can be difficult to decide what is a valid version - if version negotation is protected with CCID validation when received, it cannot do much harm, also because initial packets are much larger. 

However, if no protection is present, a version negotation packet triggered by adversary can force connection close by returning a version that the true client is attempting to connect with.

**Comment by martinthomson** [comment]
@janaiyengar, can we close this in favour of #570?
