### ISSUE TITLE
Stateless Reject mechanism needs description

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#60]
Also, Martin Duke observes that it's not clear how QUIC would determine that the crypto handshake was incomplete after one message.

I note that this might be aided by #35.

**Comment by ianswett** [comment]
This needs to be described in detail, but if the entire client hello is received, then TLS or the QUIC stack should be able to determine if the handshake can be completed or not.  If it can't, either because the TLS handshake doesn't complete or the source address token(in the QUIC extension), then an appropriate reject can be sent so it can complete next time.

This issue somewhat spans the TLS and transport docs, so I'm not sure where it belongs.

How would #35 help this?

**Comment by martinthomson** [comment]
Hmm, I don't know what I was thinking.  It probably won't help.

**Comment by martinthomson** [comment]
Hmm, I don't know what I was thinking.  It probably won't help.

**Comment by martinduke** [comment]
I suggest we incorporate this issue into #169

**Comment by martinthomson** [comment]
I think that it remains separable from #169.  It's true that there are interactions, but they are separable at least to some degree.

**Comment by martinthomson** [comment]
There's a lot of overlap here with client address validation, and much of that text can be referenced when doing this.  I do need to explain how this works though.
