### ISSUE TITLE
Move stream close forward

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#628]
With MAX_STREAM_ID, the need to delay stream close is less needed.  We no longer need to track closed in order to support enforcing of the concurrent stream limit.  Endpoints can provide or withhold new stream identifiers as they are able or see fit.

This removes some of the pressure to choose a very late point in time to move to the closed state.  In fact, Google's QUIC implementation doesn't track state for streams past the point that all data is first sent.  Waiting for acknowledgment in that implementation is managed by a connection-level construct.

Making streams close on sending means that the state machine is simpler to explain.

Or, we could consider adding a state for the case where streams are draining.

**Comment by janaiyengar** [comment]
I don't think it makes sense for streams to be draining... the connection ought to handle that, IMO. (I'll check what GQUIC does and get back on when we close streams. The constraints are different though, since open streams in GQUIC count towards MAX_OPEN_STREAMS, whereas with QUIC we now don't have that trouble.)

**Comment by martinthomson** [comment]
Well, the nice thing about having a maximum stream ID is that it might not even matter how we define the stream states and closing behaviour.  We might just make a comment that the stream state is advisory.  In any case, this was resolved in one way in the current draft.  I intended to close this immediately, but forgot.  So here goes.
