### ISSUE TITLE
ACK frame

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#644]
There are MANY open issues on this.  Maybe we need to take a hollistic take on this.

**Comment by mnot** [comment]
Possibly included: #423 #230 #506 #507 #563 #601 #613

**Comment by mikkelfj** [comment]
#221 references 0RTT ACKs in TLS.
For other cleartext ACKs the text is a bit vague :

>An endpoint SHOULD use data from unprotected or 0-RTT-protected "ACK"
   frames only during the initial handshake and while they have
   insufficient information from 1-RTT-protected "ACK" frames.  Once
   sufficient information has been obtained from protected messages,
   information obtained from less reliable sources can be discarded.

Ignoring 0-RTT:
Does this mean cleartext ACK can remain valid after handshake? Considering constraints on cleartext content (stream 0 + ACK only), I don't think it is relevant anymore, but if it is relevant, would that not follow automatically: if a packet is not acknowledged and not retransmitted, that ack is relevant, otherwise it is not - same as any ACK?

If the text means remains relevant until handshake or sufficient information obtained - that would not be possible before handshake anyway?

**Comment by ianswett** [comment]
All the remaining ack issues this references are editorial, so I think it makes sense to close this.
