### ISSUE TITLE
Stream frame data length wording.

### ISSUE THREAD

**Issue by chocis** [quicwg/base-drafts#652]
In current draft there is sentence: "A STREAM frame MUST have either non-zero data length or the FIN bit set."
At least for me this was confusing if it refers to Data Length field + D bit. Wouldn't a better wording be something similar to:  "A STREAM frame MUST have either non-empty Stream Data payload or the FIN bit set." or "A STREAM frame MUST have either some Stream Data payload or the FIN bit set without payload"?

**Comment by mikkelfj** [comment]
The idea, I believe, is that generally a stream is closed as soon as possible with as much data as possible in a frame. The idea is not that FIN should be an empty frame. However, sometimes you don't know whether more data will arrive or not, so an empty frame with FIN is permitted. Other empty stream frames are not permitted to be empty because they can be used to abuse flow control limits.

**Comment by MikeBishop** [comment]
A stream frame's payload MUST NOT be empty, unless the FIN bit is set.
