### ISSUE TITLE
Stream closed state and acknowledgments

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#743]
We've prevaricated on this one, and I don't think that we have consensus on the outcome.

Does a stream become closed when all data is sent the first time, or when that data is acknowledged?  The same question applies to RST_STREAM: is the stream closed when RST_STREAM is sent, or when it is acknowledged?

With the move to maximum stream identifiers, this question matters less than it did previously, but I think that it still deserves an answer.

**Comment by MikeBishop** [comment]
Thinking modularly, I'd argue that it should happen when the frames are submitted for transmission; the stream state machine shouldn't be dependent on ACKs and retransmissions.  The receiver is necessarily going to lag a little bit due to those things, but the situation of there being a lag is not remedied by making the lagging party be the sender instead.  This also mirrors flow control, where the window is consumed as soon as the frames are submitted, even if they haven't been sent yet.

As you note, the reason we considered switching the lag was to make the sender more conservative about which streams are in which state to avoid accidentally violating max_concurrent_streams.  That's no longer an issue, since the receiver is the one controlling that now.

**Comment by martinthomson** [comment]
It depends on the model you assume.  That assumes a handoff between the stream and some transmit/retransmit machinery.

The other model, one that I prefer, is one where the transmission machinery pulls from available streams.  It uses priority to determine what to send, preferring data that has already been sent.  In that case, data on streams could remain attributed to the stream until it is acknowledged.  The advantage here is potentially better prioritization and the cost is a potential increase in the number of bytes that are outstanding without acknowledgment.

Neither model is more modular than the other, the line just appears in a different place.

**Comment by RyanAtGoogle** [comment]
If the question is specifically about when the stream is closed, doesn't
the state diagram make it clear that it's when the FIN is sent, not when
the FIN is ACK'd?

                            +--------+
                            |        |
                            |  idle  |
                            |        |
                            +--------+
                                 |
                        send/recv STREAM/RST
                             recv MSD/SB
                                 |
                                 v
                 recv FIN/  +--------+    send FIN/
                 recv RST   |        |    send RST
                  ,---------|  open  |-----------.
                 /          |        |            \
                v           +--------+             v
         +----------+                          +----------+
         |   half   |                          |   half   |
         |  closed  |                          |  closed  |
         | (remote) |                          |  (local) |
         +----------+                          +----------+
             |                                        |
             |   send FIN/  +--------+    recv FIN/   |
              \  send RST   |        |    recv RST   /
               `----------->| closed |<-------------'
                            |        |
                            +--------+

**Comment by martinthomson** [comment]
Yes, the document - in its current form - is quite clear on this.  The issue exists to determine whether this is *desirable* in addition to being documented, because we have in the past had some confusion on this point.

**Comment by RyanAtGoogle** [comment]
Ah, I see. Good point. Not surprisingly, I prefer the "closed when sent"
interpretation. This allows a relatively clean separation between the
"stream" layer (open stream accounting, flow control, etc) and the "packet
layer" (packet framing, retransmissions, etc). I agree with Mike that since
we no longer have max_streams it doesn't seem like there's a compelling
reason to require the FIN be ACK'd in order to consider the stream closed.

**Comment by martinduke** [comment]
I think the stream should remain open until full acknowledgment, for two reasons. One, per #765 the logical place to put in flight data is in the stream data structure, so I have to keep it around.

Two, a QUIC stream has roughly the semantics of a TCP close and it would be nice to adhere to those norms.

But I concede that it isn't a big deal either way.

**Comment by igorlord** [comment]
> Does a stream become closed when all data is sent the first time, or when that data is acknowledged?

Given that we've moved to max stream id, what difference does the answer to the question make?  Defining "closed" as "when FIN is sent" or "when FIN is requested to be sent" or "when stream.close() API function returns" makes for simpler state diagrams.  Defining "closed" as "when ACKs have been received for all data and the FIN" aligns better with possible implementations.

As far as possible implementations are concerned, "close" can be defined as when the implementation is free to forget all about the stream, except that it is "closed". That happens when "ACKs have been received for all data and the FIN" or when RST is sent.

**Comment by MikeBishop** [comment]
Separated state machines in #894 covers this.
