### ISSUE TITLE
Do we really need a "final offset" in the Reset Stream frame?

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#749]
Or, what is the node that receives the Reset Stream supposed to do with the Final Offset?

The text says, "discard immediately". That rules out any idea of receiving the bytes up to the final offset before closing. So, what's the point, exactly?

**Comment by martinthomson** [comment]
https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#edge-cases-and-other-considerations

**Comment by huitema** [comment]
Yes, OK. But then, a pointer from the reset stream description to these considerations would help.

**Comment by kazuho** [comment]
@martinthomson Could the requirement be abolished if we define the connection-level flow control window as the number of octets sent using STREAM frames (excluding stream_id=0), instead of defining it as the number of octets sent over the streams (excluding stream_id=0)?

I would argue that the bonus here is much more than removing the `final_offset` field. I think that we can get rid of the responding `RST_STREAM` frame as a whole if we change the way we calculate the connection-level flow control window.

**Comment by martinthomson** [comment]
@kazuho, you don't want to count retransmissions, because then you have different numbers on each side.  So I assume that you mean total bytes originally sent, which is basically what it is right now.

We discussed removing the limitation entirely and have any used up flow control on a stream credited back when you reset it.  The problem with that is that I can send you a very large stream over time, but if it is reset, that gives a huge and immediate increase to the connection flow control window.  I think that this design is fine.
