### ISSUE TITLE
GOAWAY review

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#757]
In reviewing GOAWAY I noticed a few things.  I don't think that these are controversial, but they probably need clarification.

* The QUIC stream ID MUST be a client-initiated frame.

* The QUIC stream ID can be lower than the ID of streams that carried requests, even completed requests.  If the stream carried a request that was successfully completed, then the fact that the stream was "cancelled" by the GOAWAY doesn't retroactively cancel that request.  Critically, completed streams can't be safely retried. See also #756.

**Comment by MikeBishop** [comment]
It does say that the frame "contains the stream identifier of **the last client-initiated request**", or "MAY be zero."  This seems sufficient, but you're welcome to convince me otherwise or suggest how to make it clearer.

The second one feels like a server error -- the GOAWAY frame declares that the requests weren't processed, yet you're positing that a response has already been generated.  I've added some text about this in #770, but it fundamentally feels like the server oughtn't be doing that.
