### ISSUE TITLE
Congestion feedback for rejected 0-RTT

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#762]
When 0-RTT is rejected, any packets protected with those keys will be discarded by the server.  0-RTT rejection means that the server pretends that it can't read 0-RTT.  As a result, servers cannot (MUST NOT actually) acknowledge rejected 0-RTT.

This needs discussion in the recovery draft.  What do we tell the congestion controller about these packets?  The current design seems to only take bytes sent and packet loss as inputs to the algorithm.  That leads to the controller assuming that the packet was received successfully, when we have no way of knowing whether that is true or not.  We certainly don't want the client to ignore the fact that it sent packets, so what do we recommend?

See also #761.

**Comment by martinthomson** [comment]
On the list, @janaiyengar says (and I think that this might reflect where we are going with this):

> The sender is not going to receive acks for these packets, so it's best to do a clean slate and start again with the initial window. The sender *could* do something more complicated, like wait "a while" to let the network drain, but without knowing what network bandwidth is,  the sender would still be in the dark about how long to wait. Any wait time here will be wrong, just as wrong as the initial window. So, I would reset the controller's state to initial state.

**Comment by mirjak** [comment]
So even if the rejected packets where not ack'ed, the server could still indicate to the client in the TLS handshake that the 0-RTT data was rejected and potentially even tell the client how many packets where rejected. That might be all you need to know for congestion control purposes because if some or all of the 0-RTT packets were lost you might want to reduce the congestion window even below the initial window (assuming the initial window was larger than the minimum window).

However, just resending the 1-RTT with the initial window is probably easier and should be fine in most cases, or in the worse case just delay your congestion control reaction by one RTT.

**Comment by ekr** [comment]
On Wed, Sep 13, 2017 at 6:12 AM, mirjak <notifications@github.com> wrote:

> So even if the rejected packets where not ack'ed, the server could still
> indicate to the client in the TLS handshake that the 0-RTT data was
> rejected and potentially even tell the client how many packets where
> rejected.
>

Well, you can say it was rejected, though you don't know how many packets
were rejected at this point.

-Ekr

**Comment by martinthomson** [comment]
Duplicate of #390.
