### ISSUE TITLE
Clarify Connection ID and Version number endianness

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#786]
It should be obvious, but we should make it clear since endianness matters, especially when we feed connection ID into the en/decrypters.

Also, version number should be treated as a uint. We should be explicit about this as well.

**Comment by RyanAtGoogle** [comment]
Two comments. First, I think you meant 64 bit not 32 :)

But second, my inclination is that for anything in the protocol which is vaguely numeric with should store it in memory in host-byte-order and write to the wire in network-byte-order. As such, I would argue that the connection id *should* be "an unsigned 64-bit number".

As to the QUIC version, I agree that the QUIC version should be "and unsigned 32-bit number". I believe that is already implied by the spec, but being explicit would be good.

**Comment by janaiyengar** [comment]
Yes, thanks for correcting, I meant 64-bit connection ID and 32-bit Version.

The most important thing here is that we agree on and explicitly specify an endianness to use (I've changed the title of this bug to reflect that). Your point is fair, and I'm fine with treating connection ID as a uint.

**Comment by siyengar** [comment]
It seems fairly weird to treat conn ids as 64 bit ints because load balancers are going to do bit twiddling on the connection id to either encrypt / store state in the connid. I can see the argument of being consistent with other fields, but it still seems like it will cause some strange bugs if we specify endianness for things that are not actually ints. My preference is to specifically treat connid as not an int.

**Comment by martinthomson** [comment]
@siyengar, nobody will know if you don't use htonll/ntohll.  Feel free to treat connection ID as flat octets, they are your octets to do with as you please.
