### ISSUE TITLE
What happens if you get a stream of the wrong parity?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#791]
The client has odd streams and the server even, so what happens if the client sends frame data on stream 2 before the server has opened it?

**Comment by mcmanus** [comment]
connection close w/ stream_state_error

**Comment by ekr** [comment]
@mcmanus: where do you think this is specified?

**Comment by mcmanus** [comment]
perhaps 10.1 needs to be tweaked to have a normative MUST, but otherwise I
think the framework is all there.

10.1.
<https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#rfc.section.10.1>
Stream
Identifiers
<https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#stream-id>

Streams are identified by an unsigned 32-bit integer, referred to as the
Stream ID. To avoid Stream ID collision, clients initiate streams using
odd-numbered Stream IDs; streams initiated by the server use even-numbered
Stream IDs.

*10.2*

In the absence of more specific guidance elsewhere in this document,
implementations SHOULD treat the receipt of a frame that is not expressly
permitted in the description of a state as a connection error (see Section
12
<https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#error-handling>
).
12.
<https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#rfc.section.12>
Error
Handling
<https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#error-handling>

An endpoint that detects an error SHOULD signal the existence of that error
to its peer. Errors can affect an entire connection (see Section 12.1
<https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#connection-errors>),
or a single stream (see Section 12.2
<https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#stream-errors>
).

The most appropriate error code (Section 12.3
<https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#error-codes>)
SHOULD be included in the frame that signals the error. Where this
specification identifies error conditions, it also identifies the error
code that is used.

**Comment by martinthomson** [comment]
Let's just make this really explicit.
