### ISSUE TITLE
Re-randomization for packet numbers

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#823]
The draft is pretty inconsistent about what packet number to use in response to version negotiation or stateless retry.  Since no one implements re-randomization, just move to an increment-by-one.

**Comment by tatsuhiro-t** [comment]
FYI, ngtcp2 client does re-randomization on Server Stateless Retry Packet.

**Comment by mcmanus** [comment]
I actually think the re-randomization requirement creates a bug because it can create 2 packets with the same number and the same cid but different contexts.

consider a client that sends out a CI (0) and a retransmitted CI(1) then receives a retry (0).. it will generate a new CI with a random number to honor the retry. it could be CI(1) again as its random.. if a retry(1) arrives it is ambiguous whether the retry applies to the first flight of CI or the second.
