### ISSUE TITLE
Need a way to send big values in stream 0

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#825]
Currently we have a set of bad properties:

- You can't MAX_STREAM_DATA in stream 0
- Stream 0 is stream-level flow controlled
- People have big certs

When you put these all together, we are going to have problems. There are a number of options:

1. Allow MAX_STREAM_DATA
2. Exempt stream 0 from flow control
3. Prohibit big certs
4. Have a fixed flow control window refreshed by the ACK.

**Comment by martinthomson** [comment]
Note that this is only a problem for the Server Cleartext.  Client Initial is fixed in size. Client Cleartext is sent after the 1-RTT keys are available, so the server can send MAX_STREAM_DATA.

The other idea was to split flow control for stream 0 across the handshake: MAX_STREAM_DATA can be sent by the client (and server) in the clear, but any flow control is reset once the handshake completes (the consumed flow control on the stream is reset, the final offset is set back to the initial value, and maybe also the stream offset goes back to zero).

**Comment by jpinner-lyft** [comment]
It seems like a minimal change here would be to add an additional transport parameter for max stream data on stream 0 that the client can send. This should be sufficient for a client to advertise a maximum size it for the server handshake it is willing to accept.

**Comment by MikeBishop** [comment]
OBE.  Stream 0 is not flow controlled during the handshake.  See #1082.
