### ISSUE TITLE
don't allow 0 as a packet number

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#832]
This would make implementations a lot easier (especially ACK generation).

**Comment by mikkelfj** [comment]
I agree

**Comment by nibanks** [comment]
Personally, I don't think it makes it easier. If we add this restriction, we would have to update our implementation to add **extra special case logic** for packet number randomization to not allow 0, and then on the receive side of things, always check to see if packet number was 0 and drop it.

**Comment by marten-seemann** [comment]
That's a little extra logic (one if for generating and one if for receiving). By allowing 0 with the probability of 2^-31 we lose the ability to check that `highest received packet number != 0`, which will already is problem for several implementations, and will produce some really nasty corner cases in the future.

**Comment by nibanks** [comment]
But why do you need this? Are you just trying to track if you have received any packet? If so, wouldn't a separate flag for that case work just as easily? Or a counter for number of packets received?

> the ability to check that the `highest received packet number != 0`

**Comment by marten-seemann** [comment]
Correct, the alternative would be creating bools to track if the first packet was already received, just to cover an extremely improbable corner case in the packet number randomisation.

**Comment by nibanks** [comment]
If you don't like using a Boolean, keep a counter, which could have other uses, such as a statistical measurement.

**Comment by ianswett** [comment]
Stats are useful, but it'd nice to keep my stats code separate from my framing code.  Marten's right, this is definitely annoying to deal with, probably on the send side as well, since our code initializes packet numbers to 0 everywhere under the thought that 0 is an invalid packet number.  

It's really nice to have an invalid packet number constant, and using 0 as an invalid packet number is a lot better than using some other value in my opinion(ie: 2^64-1)

**Comment by nibanks** [comment]
If we really must have an invalid packet number I would also prefer 2^64-1, as that would never be initialized to, since we use 32 random bits, and we would essentially limit the maximum number allowed by 1. Really, no additional logic required.

**Comment by ekr** [comment]
I agree with @nibanks, but it's worth noting that it's also easy to produce
a value that is nonzero:

33s | <30 random bits> | 1

**Comment by RyanAtGoogle** [comment]
I also completely agree with the idea that 0 is an invalid packet number to
simplify tracking.

**Comment by janaiyengar** [comment]
Zero should not be allowed. Zero is a special number, it should be treated as such.

**Comment by pravb** [comment]
Any special packet number precludes packet number wraparound in future.

**Comment by RyanAtGoogle** [comment]
Not really, it just requires careful handling.

**Comment by martinthomson** [comment]
1. s/largest_packet_number_I_will_automatically_discard/smallest_packet_number_I_might_accept/g
2. profit

Special values are almost never a good idea.  If we mandate 1, then we might have code that either can't properly handle a 0 if one is sent.  We certainly will have a lot of unused special case code for that number.

**Comment by mcmanus** [comment]
we have stream id 0 (though it is special for the connection - its not special for stream manipulation).. and offset 0.. and a connection id sequence number that starts at 0. 

If we go with martin's proposal re 62 bit integer encoding, there are billions of integers to use as sentinels in an implementation with a 64 bit int without overloading ones that can be transferred on the wire and cause interop pain.

**Comment by mikkelfj** [comment]
I see the argument of avoiding sentinels, but at least in the C programming language, there is a massive amount of boilerplate code to initialize various structs that could just have been zeroed. There there are numerous additional checks to see if a value is uninitialized instead of just comparing with the previously received value. A much simpler check is to ensure that whatever you receive is larget than what you have: it then becomes illegal to send zero. But it is also illegal to send something smaller in many cases, for example data limits. In this context treating 0 as special makes a lot sense. From an algebraic point of view, 0 also has special signficance amongst the countable objects.

**Comment by larseggert** [comment]
Maybe I'm too much of a TCP guy, but I had implicitly assumed that packet numbers were like TCP sequence numbers and operated on with modular arithmetic? Any reason this is not a good idea?

**Comment by martinthomson** [comment]
The packet number is input to the AEAD nonce.  If you wrap around, you use the same nonce twice.  That's basically fatal for the ciphers we use.  We could allow a wrap around, maintain a counter on each wrap around and concatenate the two, but these are really big numbers and maybe it's not worth it.  You would also need to rekey many times with some ciphers (AES) or the cipher essentially wears out.

**Comment by mikkelfj** [comment]
You could also consider a packet number wrap to be a rekeying event. Once you have new keys the AEAD nonce concern is gone.

**Comment by mikkelfj** [comment]
To be more specific - AES-GCM should only use the same key for at most 2^32-2 nonces, i.e. packet numbers and in praxis less than that due to some possible attacks on GCM tags (the hash is computed on plain text for maxium parallelization, but that apparently has a cost in security).

**Comment by ekr** [comment]
"To be more specific - AES-GCM should only use the same key for at most 2^32-2 nonces, i.e. packet numbers and in praxis less than that due to some possible attacks on GCM tags (the hash is computed on plain text for maximum parallellization, but that apparently has a cost in security)."

The limit we converged on for TLS is: 2^{24.5}
https://tlswg.github.io/tls13-spec/draft-ietf-tls-tls13.html#limits-on-key-usage

You can find the reference that led us to that here:
http://www.isg.rhul.ac.uk/~kp/TLS-AEbounds.pdf

**Comment by mikkelfj** [comment]
@ekr thanks for links. FWIW I thinks those limits on key usage in the TLS spec ought to be a MUST, not a SHOULD. Maybe 2^24.5 is conservative, but there is a point where GCM it falls apart more so than some ciphers. (GCM is fine, but only when respect its limits).

**Comment by janaiyengar** [comment]
@larseggert because there's no reason to repeat that mistake? It's annoying and bug-attracting to do modulo arithmetic everywhere in the code.

**Comment by larseggert** [comment]
There's that. And I'm OK if we do it otherwise, but then let's be very clear about it, to avoid confusing TCP-heads like myself.

**Comment by janaiyengar** [comment]
With the new packet number encoding, we end up needing only 62 bis for the packet number, which means you can use a signed int for representing it and < 0 as a sentinel value. I'll be ok with either 0 or 1 as the initial value.

Can we agree on something here and wrap this issue up? I'll be happy whichever way we go, but let's choose one and move on.

**Comment by janaiyengar** [comment]
To be clear: Given we can have a < 0 sentinel value, I'm fine with 0 as the initial number.

**Comment by pravb** [comment]
Let's explicitly disallow wraparound then with the recognition that we then put a limit on the amount of data a QUIC connection can transfer whereas there is no such limit in TCP. I think if a received packet causes a change in the connection state machine then we don't need a Boolean or stats counter to detect this and we do not need any sentinel values. Also I can't think of any other use cases for sentinel values so if anyone else has any ideas please speak out soon.

**Comment by janaiyengar** [comment]
Thinking about this a bit more and chatting with @ianswett, not randomizing will risk ossification of the initial packet number.  I'm wondering if it's valuable to randomize anyways, just to avoid issues, and in the interest of making more fields unpredictable. Thoughts?

**Comment by mikkelfj** [comment]
In the context of connection migration I just sent a mail to the QUIC WG list suggesting to avoid gaps such that the packer numbers cannot effectively be exhausted. One option is to encode/encrypt packet numbers, the other was to reset packet numbers during migration. Encoding would deal with ossification issues. Randomizing early would work against keeping the packet number space large, though not as much as for migrations since it is a one off.

**Comment by martinthomson** [comment]
The ossification question is why - I think - we added the randomization in the first place.  We should pick something.

Happy to prohibit wrapping as @pravb requests.

**Comment by janaiyengar** [comment]
Ok, we've chosen a random initial number now, and that includes 0 as a possible value. Given the recent discussion on this issue, I'm going to close it as resolved. If anyone has strong arguments, please re-open.
