### ISSUE TITLE
RTT Measurement for HelloRetryRequest

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#879]
In #817, @marten-seemann asks why the server can't send an ACK with its HelloRetryRequest.

I had assumed that this ACK would be pointless.  Obviously, the server can only acknowledge a single packet (the Initial packet), and this is implicitly acknowledged.  The only information that the packet might now contain is the ACK Delay field now that we removed the timestamps from the default ACK format.  That assumes that the server is delaying its response in any way or that its processing is somehow significant enough to be worth measuring.  I don't think that the server has any reason to delay the generation of a HelloRetryRequest, and the entire design depends on the processing time required to generate it is minimal.

Did I miss something?

**Comment by RyanAtGoogle** [comment]
It's possible for a client to underestimate the RTT to the server, send a ClientHello and then retransmit it. The server could receive the first ClientHello and send a HelloRetryRequest in response. But at this point the client may think that the HelloRetryRequest is in response to the second retransmitted ClientHello. So by sending an ACK, the client can learn if ClientHello 1 or 2 was the packet which elicited the HelloRetryRequest.

**Comment by martinthomson** [comment]
That's not a problem: the different packets containing ClientHello will include a different packet number, which is echoed in the packet carrying the HelloRetryRequest.

**Comment by marten-seemann** [comment]
There are two issues here:

1. Even if possible in theory, do we really want to introduce a separate way for RTT measurements independent of ACKs, which only applies for the first packet?
2. Do we really want to introduce extra logic to make sure that the HRR packet doesn’t include an ACK, and to verify that on the receiver side?

I think the answer to both questions is no. Including an ACK is cheap (just a few bytes) and all the ACKing logic is already in place. I think we should revert #817, or maybe even go a step further and make including an ACK with the HRR recommended.

**Comment by ianswett** [comment]
I think Marten outlines the issue well.

In GQUIC, we experimented with writing some handshake specific code for a while, but it never worked correctly, so we decided it was a lot easier to just use the existing ACK frame.

Whichever way we go, we should clarify how one is expected to obtain an RTT sample to feed into the next connection attempt.

**Comment by mcmanus** [comment]
no matter what we do there is going to be some cognitive dissonance.
Elsewhere we say "The client client .. discards all transport state" upon
receipt. So its not really a traditional ack in that sense either (i.e. if
the server did not send the ACK you would not keep transmitting the info of
the old CI which has been reset).

In short - I don't think it matters if its implicit or explicit, this will
be kinda ugly either way. I like implicit myself but whatever :)

**Comment by janaiyengar** [comment]
@mcmanus: The goal was to allow the sender to retain some state, esp. RTT,
across an HRR, but discard other state. This is very useful for the
handshake timeout, since there's really no other value to seed the timeout
with. Section 5.4.2 says what you wrote, but also says "The client MAY also
retain any observed RTT or congestion state that it has accumulated for the
flow, but other transport state MUST be discarded."

I agree with Marten -- it's unnecessary to create separate RTT logic for
this. What do we get for getting rid of ACKs here?

**Comment by ekr** [comment]
On Tue, Oct 17, 2017 at 10:19 AM, janaiyengar <notifications@github.com>
wrote:

> @mcmanus: The goal was to allow the sender to retain some state, esp. RTT,
> across an HRR, but discard other state. This is very useful for the
> handshake timeout, since there's really no other value to seed the timeout
> with. Section 5.4.2 says what you wrote, but also says "The client MAY also
> retain any observed RTT or congestion state that it has accumulated for the
> flow, but other transport state MUST be discarded."
>
> I agree with Marten -- it's unnecessary to create separate RTT logic for
> this. What do we get for getting rid of ACKs here?
>

You avoid creating situations where the ACK state of this record is
inconsistent.
As McManus says, you are implicitly ACKing the CI by sending this message.

**Comment by janaiyengar** [comment]
I'd still prefer having an ACK frame in there simply because that part of the code doesn't have to be special cased for an HRR being an ACK. PR #882 seems like a good compromise; it doesn't require an ACK be sent, so I'd like to see that be merged.

**Comment by ianswett** [comment]
I would like to never rely on the word 'implicit' in the QUIC spec.  One can use implicit information, but I don't think it should be critical to correctness.

I'm not hearing a clear argument about why this is harmful.  One certainly could create an ack frame that doesn't ack the correct packets, but that seems like a general bug, not one specific to this case.

**Comment by ekr** [comment]
On Tue, Oct 31, 2017 at 4:35 PM, ianswett <notifications@github.com> wrote:

> I would like to never rely on the word 'implicit' in the QUIC spec. One
> can use implicit information, but I don't think it should be critical to
> correctness.
>
> I'm not hearing a clear argument about why this is harmful.
>
It creates the possibility of inconsistencies between facts. Namely, it's
obvious the packet was received and you shouldn't be retransmitting, but
yet if there's no ACK.


> One certainly could create an ack frame that doesn't ack the correct
> packets, but that seems like a general bug, not one specific to this case.
>
I guess I see it differently. A topic for Singapore, I guess.


>

**Comment by ianswett** [comment]
The inconsistencies aren't a contradiction, so I'm still confused about the problem this causes.

**Comment by mcmanus** [comment]
(not specific to hrr) There is a general weirdness where you can send a client initial and then receive server cleartext but not an ack of the client initial leading to simultaneous (or even out of order) sending of more client initials and client cleartext. I think the HRR thing is similar. I don't react quite as strongly negatively to that as some other people, but either a mandatory ack or an implicit ack would solve it - while leaving it technically unconnected persists the problem.

**Comment by martinthomson** [comment]
In Handshake packets (I'll use the new names...), we allow - and even encourage - the presence of ACK frames.  Normal rules apply there.  Given that there might be multiple Handshake packets, there might be an ACK in some but not others, but that's all fairly standard logic.  In other words, Handshake packets don't need this special consideration.

This also doesn't apply to an Initial packet that is sent in response to a Retry packet, because we expect the server not to maintain state.  Though it could, we expect that it doesn't, and so it won't be starting its RTT measurement until it receives Handshake packets from the client, on the next go 'round.

This question is specific to the Retry packet, which is singular and contains a way to precisely identify the Initial packet (it echoes the packet number).  You do really need to ensure that you treat receipt of a Retry packet as an implicit acknowledgment, if only so that you stop sending the same Initial packet.  The question then is whether it is - for the purposes of priming RTT measurements - better to use the implicit acknowledgment information always, or to use the same ACK-handling pathways that would be otherwise used.

**Comment by RyanAtGoogle** [comment]
@martinthomson well said. I think you've clearly articulated the choices.

Not that we're voting, but your phrasing, "or to use the same ACK-handling pathways that would be otherwise used" is super compelling to me. If we always use the same ACK-handling pathway to deduce RTT, that makes implementations simpler. So that's definitely my preference.

But you are also totally right to observe that the implicit acknowledgement expresses the identical information and as such could clearly be made to work.

**Comment by marten-seemann** [comment]
I'd like to add some implementation experience to this issue, and make the case for not only allowing an ACK in the Retry packet, but for requiring it.

If you're using the same retransmission logic for the Initial packet as for all other packets (which is what the loss recovery draft implies we should do) you'll have to build a special case just to acknowledge the Initial packet. It's even more confusing, since the Initial packet that the server accepts will get ACKed, it's only the only triggering the Retry that needs special treatment.
If you forget that special case, the client will retransmit this packet indefinitely (since it's never acknowledged), and constantly interpret this as a loss signal.

**Comment by nibanks** [comment]
Personally, I like having the ACK in the retry packet and think we should allow it, though, not necessarily require it. But at the very least, the spec currently has conflicting info in the retry section [(5.4.2).](https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#rfc.section.5.4.2) At the very beginning it states:

> A Retry packet uses long headers with a type value of 0x7E. It carries cryptographic handshake messages **and acknowledgments**.

Then at the end it states:

> The payload of the Retry packet contains a single STREAM frame on stream 0 with offset 0 containing the server’s cryptographic stateless retry material. **It MUST NOT contain any other frames.**

I just encountered an interop issue because I only read the top and included an ACK frame in my Retry and found that ngtcp2 client didn't like it.

**Comment by martinthomson** [comment]
Marking as a duplicate of the newly-scoped #627.
