### ISSUE TITLE
Resume HTTP/2 TLS from QUIC ?

### ISSUE THREAD

**Issue by krasic** [quicwg/base-drafts#941]
Section 2 and 3 of the HTTP mapping describe the progression from HTTP QUIC advertisement to QUIC connection establishment.

For the very first time accessing an HTTP origin, typical progression is:
   o make initial request via HTTP/2
       - this involves TLS 1.3 handshake
       - client see response contains QUIC advertisement
   o subsequent request to same origin 
        - client tries QUIC, does QUIC TLS 1.3 handshake
        - so two RTTs before first QUIC request goes out.

Would it be possible for QUIC to instead of treating it as an initial TLS 1.3 handshake, but rather  treating the first QUIC request as TLS zero RTT, based on resuming the HTTP/2 TLS session (over QUIC)?   Saving 1 RTT for that case?

**Comment by siyengar** [comment]
Do you mean use the same session ticket from a TLS 1.3 connection over TCP for Quic 0-RTT? I don't think anything expressly prohibits x-protocol resumption right now, but we could do a security analysis on this.

**Comment by britram** [comment]
see also https://tools.ietf.org/html/draft-kuehlewind-taps-crypto-sep for some of the implication of the general space of cross-protocol resumption. Seems like it might be useful to allow for this capability in the design, or at least not gratuitously prohibit it.

**Comment by krasic** [comment]
siyengar@: yes.

**Comment by ianswett** [comment]
+1 to making this possible.  We could add a MAY resume with the session ticket from the TCP/TLS 1.3 connection if available?

It would be nice to know if the resumption was likely to work or if the TCP and QUIC TLS 1.3 resumption tokens were completely disjoint.  So possibly we either need to encourage applications to make resumption back and forth between QUIC and TCP work OR include some explicit indicator?

**Comment by davidben** [comment]
QUIC tickets need to include addition source-address information, right? That's not going to exist in TLS a priori. A TLS stack could put it in for you, but that's enough extra work that you probably shouldn't waste single-use tickets on that without an advertisement.

And then you've got the QUIC transport parameters that both sides need to recover for 0-RTT, but TLS over TCP is not going to negotiate that stuff. Though in https://github.com/quicwg/base-drafts/blob/master/draft-ietf-quic-transport.md#values-of-transport-parameters-for-0-rtt-zerortt-parameters, it looks like you all added an extension for the server to supply it independent of what the connection negotiated?

That would suggest the advertisement mechanism can just be the presence of quic_transport_parameters extension on TCP/TLS1.3 tickets. The server can send unsolicited NewSessionTicket extensions in TLS 1.3, so it can just advertise that on its own. Sending that over TCP implies the server has additionally put in whatever source-address information it wants and the client can reasonably expect the ticket to be usable for QUIC.

**Comment by siyengar** [comment]
@davidben ya i mentioned that in a previous comment that tls tickets would have to have the quic params in them :) A QUIC compatible server would be aware that clients would use TLS 1.3 + TCP connections to them and send them the same ticket. 

We should probably also have a MUST restriction that this sharing should only be limited to TLS 1.3 + TCP clients (and maybe TLS 1.2 with Extended master secret) otherwise we end up running into issues with the session ticket for TLS 1.2  being reusable for 1.3 creating the potential for triple handshake like attacks.

**Comment by ekr** [comment]
On Sun, Nov 19, 2017 at 5:06 AM, Subodh Iyengar <notifications@github.com>
wrote:

> @davidben <https://github.com/davidben> ya i mentioned that in a previous
> comment that tls tickets would have to have the quic params in them :) A
> QUIC compatible server would be aware that clients would use TLS 1.3 + TCP
> connections to them and send them the same ticket.
>
> We should probably also have a MUST restriction that this sharing should
> only be limited to TLS 1.3 + TCP clients (and maybe TLS 1.2 with Extended
> master secret) otherwise we end up running into issues with the session
> ticket for TLS 1.2 being reusable for 1.3 creating the potential for triple
> handshake like attacks.
>

I think we should just say TLS 1.3. I don't even know how to reason about
TLS 1.2 -> TLS 1.3 resumption, but I know it has non-awesome security
properties b/c of the key ladder.

**Comment by ianswett** [comment]
Agreed, TLS 1.3 only.

**Comment by martinthomson** [comment]
I realize that I was the one to be persuaded that this cross-protocol resumption is a good idea, but I've since concluded that unless we revise ALPN, this is unwise.

This is not a problem at all if you intend to do simple resumption without 0-RTT, but it gets complicated thereafter.

The way that TLS works assumes that the ALPN value is remembered by the server (note that remembering often means embedding it in the ticket, that detail doesn't matter here).  It uses this remembered value to decide what protocol the client is speaking.  If it accepts 0-RTT, it assumes that the protocol hasn't change.  The server also can't change the protocol if it accepts 0-RTT.

We created an equivalency between h2/TLS and hq/QUIC in the quic-tls draft.  That seems like a great idea until you consider the potential for a similar equivalency between h2 and hqv2 (or whatever we call the next version).  A client that makes a QUIC connection and resumes from h2 might advertise [hq, hqv2] in its handshake, and the server has to assume that the packets are hq.  In other words, the equivalency is 1-1.  That limits our ability to deploy new protocol versions.

The same considerations apply in the reverse direction.

I think that we should drop this feature and instead develop a new document that describes two things: 

* explicit advertisement of support for different protocols for 0-RTT.  That might use ALPN in the NewSessionTicket message, or a new extension.
* a means of the client signaling which of the selected protocols it is using for early data.  This might be as simple as saying that the first entry in ALPN is what is in use, or it could use a new extension.

That sort of design has the virtue of restricting the resumption to TLS 1.3 or higher as well.  (BTW, I thought that we had a hard rule about keeping the version the same for resumption.)

**Comment by davidben** [comment]
(Yeah, cross-version resumptions are already not a thing. OpenSSL historically didn't quite get this right, but it's since been fixed.)

**Comment by krasic** [comment]
I have been told this can be subsumed as part of https://github.com/tlswg/tls13-spec/pull/1080.

**Comment by martinthomson** [comment]
That's a similar problem, but not exactly the same.

**Comment by MikeBishop** [comment]
Is this still an issue?  It sounds like we've agreed that you can't do this, and the spec doesn't say that you can.

**Comment by kazuho** [comment]
Isn't cross protocol resumption between TLS 1.3 and DTLS 1.3 being allowed? Then, I do not see why it should be disallowed between TLS 1.3 and QUIC.

**Comment by kazuho** [comment]
Martin's comment https://github.com/quicwg/base-drafts/issues/941#issuecomment-352140849 regarding ALPN convinces me that it is not possible to use 0-RTT when switching from h2 to hq, even if we allow cross-protocol resumption.

**Comment by martinduke** [comment]
What would be the impact of changing the hq ALPN value to h2? Whatever we call it, it's basically HTTP/2 for QUIC, and on a QUIC connection there's no ambiguity as to what the client is asking for.

**Comment by LPardue** [comment]
At a conceptual level, we'd be defining the hq ALPN ID for Alt-Svc, that is never used for TLS ALPN :)

I guess this might come down to how implementations support mixed application layer protocols. I might build a dispatcher that operates on the protocol decided by TLS ALPN, deciding whether to invoke H2 or HQ handshake code. 

Right now, QUIC operates over UDP but I'd like to think we build HTTP over QUIC implementations that are functional any knowledge of the protocol under QUIC (e.g. QUIC over CAN bus).

**Comment by martinthomson** [comment]
> What would be the impact of changing the hq ALPN value to h2? 

Everything breaks, as

**Comment by martinthomson** [comment]
> What would be the impact of changing the hq ALPN value to h2? 

Everything breaks, as @LPardue describes.  I think that there is a way to do this, but we would need new signaling for alt-alpn.  I don't want to embark on that effort right now.

**Comment by martinduke** [comment]
> Right now, QUIC operates over UDP but I'd like to think we build HTTP over QUIC implementations that are functional without any knowledge of the protocol under QUIC (e.g. QUIC over CAN bus).

As defined in the spec, QUIC operates over UDP. The question, as I see it, is if servers are able to demultiplex an incoming connection to the correct TLS and application. It's evident to me that we can demultiplex on the protocol number (or, the protocol of the listening socket, if we don't have access to IP header contents).

This helps solve an immediate problem with adoption. I'm not sure that QUIC-over-something-weird is in the same class. If this is the only issue, we can always switch the ALPN code in v2 to support more complicated use cases, once browsers are routinely trying QUIC when they connect.

**Comment by LPardue** [comment]
I'm a bit confused which point your addressing @martinduke, my fault for throwing stupid ideas in. Is your line of thought that a dispatcher would two classes {h2, TCP} and  {h2, UDP} to make the decision. Exposing the protocol information seems like some layering leakage to me, but it is powerful so maybe warrants it?

The mismatch between advertising `hq` and then using `h2` seems like an avenue for interop issues. Perhaps one could define an Alt-Svc param that indicates the protocol type e.g. `Alt-Svc: h2=":443"; proto=udp`. A bog-standard HTTP/2 client would simply ignore the param and try TLS/TCP.

P.S. From direct experience, I've had quite a lot of success delivering QUIC wire-format packets in all sorts of weird ways and our HTTP/QUIC layer of code works amazingly well because it doesn't care how they were delivered.

**Comment by martinduke** [comment]
Please, I'm the one messing with stuff I barely understand. What I was missing is that the alt-svc name is the same as the ALPN name. Yes, that makes this quite difficult without rewriting other RFCs. Grrr.
