### ISSUE TITLE
Offset bit in stream frame

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#998]
With varints, we are the point where the offset bit is consuming several codepoints while saving the grand total of 1 byte per stream over the life of the connection. This seems profligate given that we got rid if the num-blocks flag in the ACK, which will usually save 1 byte per ACK.

**Comment by martinduke** [comment]
I'm happy to file a PR if no one strongly objects.

**Comment by ianswett** [comment]
This is actually saving 1 byte per stream, which if we're using lots of small streams, is a large-ish.  That being said, if we have a MESSAGE frame(Issue #814) that's optimized for sub-MTU payloads, maybe it doesn't matter.

So I'm a bit resistant at the moment, but could be convinced otherwise, especially if we have a MESSAGE frame or something similar.

**Comment by mikkelfj** [comment]
I'm in line with @ianswett here. I would strongly object unless an alternative solution is provided.

A very likely use case is to send lots of new stream frames for high speed signalling of unrelated short lived streams. You can have hundreds of streams in one MTU. Even a message frame that might not sort it out because each "message" or signal might occasionally be too long for one frame, or some of the streams turns out to not be as short-lived and more content will follow.

If anything, I would like the stream header more compressed, for example by storing stream ID's as deltas.

**Comment by mikkelfj** [comment]
If the type code space is tight, I would rather have a longer extension type for less frequently used frames.

**Comment by marten-seemann** [comment]
I don't think that saving frame type code points is something we need to aim for. Currently, we have plenty of space, and it seems unlikely that we'll add a significant number of new frames.
Since the frame type byte is version specific, we also don't need to be thrifty in order to be able to accommodate future changes.

If anything, I'd suggest that we go through all frames at some point, and see if we can save a byte here and there (for commonly used frames) by consuming more frame type code points.

**Comment by martinduke** [comment]
I guess I was the only one gratified to see the ACK Frame "num blocks" flag to go away. I'll close this issue.
